
CREATE TABLE nop_retry_policy(
  SID VARCHAR(32) NOT NULL    COMMENT '主键',
  NAMESPACE_ID VARCHAR(64) NOT NULL    COMMENT '命名空间ID',
  GROUP_ID VARCHAR(64) NOT NULL    COMMENT '组ID',
  NAME VARCHAR(100) NOT NULL    COMMENT '策略名称',
  STATUS VARCHAR(1) default '1'  NULL    COMMENT '状态',
  SAVE_RECORD_STRATEGY INTEGER default 2  NULL    COMMENT '保存记录策略',
  IMMEDIATE_RETRY_COUNT INTEGER default 0  NULL    COMMENT '立刻重试次数',
  IMMEDIATE_RETRY_INTERVAL_MS BIGINT default 1000  NULL    COMMENT '立刻重试间隔(毫秒)',
  MAX_RETRY_COUNT INTEGER NOT NULL    COMMENT '最大重试次数',
  BACKOFF_STRATEGY INTEGER default 1  NULL    COMMENT '退避策略',
  INITIAL_INTERVAL_MS BIGINT default 5000  NULL    COMMENT '初始间隔(毫秒)',
  MAX_INTERVAL_MS BIGINT default 60000  NULL    COMMENT '最大间隔(毫秒)',
  JITTER_RATIO DECIMAL(5,4) default 0.5  NULL    COMMENT '抖动比例',
  EXECUTION_TIMEOUT_SECONDS INTEGER NULL    COMMENT '执行超时(秒)',
  DEADLINE_TIMEOUT_MS BIGINT NULL    COMMENT '截止超时(毫秒)',
  BLOCK_STRATEGY INTEGER NULL    COMMENT '阻塞策略',
  CALLBACK_ENABLED VARCHAR(1) default '0'  NULL    COMMENT '启用回调',
  CALLBACK_TRIGGER_TYPE INTEGER NULL    COMMENT '回调触发类型',
  CALLBACK_POLICY_ID VARCHAR(32) NULL    COMMENT '回调策略ID',
  OWNER_ID VARCHAR(50) NULL    COMMENT '所有者ID',
  DESCRIPTION VARCHAR(4000) NULL    COMMENT '描述',
  VERSION INTEGER NULL    COMMENT '版本',
  CREATED_BY VARCHAR(50) NULL    COMMENT '创建人',
  CREATE_TIME DATETIME(3) NULL    COMMENT '创建时间',
  UPDATED_BY VARCHAR(50) NULL    COMMENT '更新人',
  UPDATE_TIME DATETIME(3) NULL    COMMENT '更新时间',
  RETRYING_TIMEOUT_MS BIGINT default 600000  NULL    COMMENT '执行中锁定超时(毫秒)',
  constraint PK_nop_retry_policy primary key (SID)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs;

CREATE TABLE nop_retry_record(
  SID VARCHAR(32) NOT NULL    COMMENT '主键',
  NAMESPACE_ID VARCHAR(64) NOT NULL    COMMENT '命名空间ID',
  GROUP_ID VARCHAR(64) NOT NULL    COMMENT '组ID',
  POLICY_ID VARCHAR(32) NULL    COMMENT '策略ID',
  IDEMPOTENT_ID VARCHAR(64) NOT NULL    COMMENT '幂等ID',
  BIZ_NO VARCHAR(64) NULL    COMMENT '业务号',
  TASK_TYPE INTEGER NULL    COMMENT '任务类型',
  STATUS INTEGER NULL    COMMENT '状态',
  RETRY_COUNT INTEGER NULL    COMMENT '重试次数',
  MAX_RETRY_COUNT INTEGER NULL    COMMENT '最大重试次数',
  NEXT_TRIGGER_TIME DATETIME(3) NULL    COMMENT '下次触发时间',
  PARTITION_INDEX INTEGER NULL    COMMENT '分区索引',
  EXECUTOR_NAME VARCHAR(512) NULL    COMMENT '执行器名称',
  REQUEST_PAYLOAD VARCHAR(4000) NULL    COMMENT '请求参数',
  CONTEXT_PAYLOAD VARCHAR(4000) NULL    COMMENT '上下文参数',
  VERSION INTEGER NULL    COMMENT '版本',
  CREATED_BY VARCHAR(50) NULL    COMMENT '创建人',
  CREATE_TIME DATETIME(3) NULL    COMMENT '创建时间',
  UPDATED_BY VARCHAR(50) NULL    COMMENT '更新人',
  UPDATE_TIME DATETIME(3) NULL    COMMENT '更新时间',
  SERVICE_NAME VARCHAR(200) NULL    COMMENT '服务名',
  SERVICE_METHOD VARCHAR(100) NULL    COMMENT '服务方法',
  constraint PK_nop_retry_record primary key (SID)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs;

CREATE TABLE nop_retry_attempt(
  SID VARCHAR(32) NOT NULL    COMMENT '主键',
  RECORD_ID VARCHAR(32) NOT NULL    COMMENT '记录ID',
  ATTEMPT_NO INTEGER NULL    COMMENT '尝试序号',
  STATUS INTEGER NULL    COMMENT '状态',
  START_TIME DATETIME(3) NULL    COMMENT '开始时间',
  END_TIME DATETIME(3) NULL    COMMENT '结束时间',
  DURATION_MS BIGINT NULL    COMMENT '持续时间(毫秒)',
  ERROR_CODE VARCHAR(50) NULL    COMMENT '错误码',
  ERROR_MESSAGE VARCHAR(500) NULL    COMMENT '错误消息',
  ERROR_STACK VARCHAR(4000) NULL    COMMENT '错误堆栈',
  CLIENT_ADDRESS VARCHAR(100) NULL    COMMENT '客户端地址',
  REASON VARCHAR(500) NULL    COMMENT '原因',
  REQUEST_PAYLOAD_SNAPSHOT VARCHAR(4000) NULL    COMMENT '请求参数快照',
  VERSION INTEGER NULL    COMMENT '版本',
  CREATED_BY VARCHAR(50) NULL    COMMENT '创建人',
  CREATE_TIME DATETIME(3) NULL    COMMENT '创建时间',
  UPDATED_BY VARCHAR(50) NULL    COMMENT '更新人',
  UPDATE_TIME DATETIME(3) NULL    COMMENT '更新时间',
  constraint PK_nop_retry_attempt primary key (SID)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs;

CREATE TABLE nop_retry_dead_letter(
  SID VARCHAR(32) NOT NULL    COMMENT '主键',
  NAMESPACE_ID VARCHAR(64) NOT NULL    COMMENT '命名空间ID',
  GROUP_ID VARCHAR(64) NOT NULL    COMMENT '组ID',
  POLICY_ID VARCHAR(32) NULL    COMMENT '策略ID',
  RECORD_ID VARCHAR(32) NOT NULL    COMMENT '记录ID',
  IDEMPOTENT_ID VARCHAR(64) NOT NULL    COMMENT '幂等ID',
  BIZ_NO VARCHAR(64) NULL    COMMENT '业务号',
  EXECUTOR_NAME VARCHAR(512) NULL    COMMENT '执行器名称',
  REQUEST_PAYLOAD VARCHAR(4000) NULL    COMMENT '请求参数',
  FAILURE_CODE VARCHAR(50) NULL    COMMENT '失败码',
  FAILURE_MESSAGE VARCHAR(500) NULL    COMMENT '失败消息',
  ERROR_STACK VARCHAR(4000) NULL    COMMENT '错误堆栈',
  FINAL_STATUS INTEGER NULL    COMMENT '最终状态',
  VERSION INTEGER NULL    COMMENT '版本',
  CREATED_BY VARCHAR(50) NULL    COMMENT '创建人',
  CREATE_TIME DATETIME(3) NULL    COMMENT '创建时间',
  UPDATED_BY VARCHAR(50) NULL    COMMENT '更新人',
  UPDATE_TIME DATETIME(3) NULL    COMMENT '更新时间',
  SERVICE_NAME VARCHAR(200) NULL    COMMENT '服务名',
  SERVICE_METHOD VARCHAR(100) NULL    COMMENT '服务方法',
  constraint PK_nop_retry_dead_letter primary key (SID)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs;


   ALTER TABLE nop_retry_policy COMMENT '重试策略';
                
   ALTER TABLE nop_retry_record COMMENT '重试记录';
                
   ALTER TABLE nop_retry_attempt COMMENT '重试尝试';
                
   ALTER TABLE nop_retry_dead_letter COMMENT '重试死信';
                
