
CREATE TABLE nop_datav_dashboard(
  DASHBOARD_ID VARCHAR(32) NOT NULL    COMMENT '看板ID',
  DASHBOARD_NAME VARCHAR(100) NOT NULL    COMMENT '看板名',
  DISPLAY_NAME VARCHAR(200) NOT NULL    COMMENT '显示名',
  DESCRIPTION VARCHAR(4000) NULL    COMMENT '描述',
  DASHBOARD_TYPE INTEGER NULL    COMMENT '看板类型',
  PUBLISH_STATUS INTEGER NULL    COMMENT '发布状态',
  PUBLISHED_VERSION BIGINT NULL    COMMENT '已发布版本',
  PUBLISHED_BY VARCHAR(50) NULL    COMMENT '发布人',
  PUBLISHED_TIME DATETIME(3) NULL    COMMENT '发布时间',
  LAYOUT_CONFIG VARCHAR(4000) NULL    COMMENT '布局配置',
  DEL_FLAG TINYINT NULL    COMMENT '删除标记',
  VERSION BIGINT NOT NULL    COMMENT '数据版本',
  CREATED_BY VARCHAR(50) NOT NULL    COMMENT '创建人',
  CREATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '创建时间',
  UPDATED_BY VARCHAR(50) NOT NULL    COMMENT '修改人',
  UPDATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '修改时间',
  REMARK VARCHAR(200) NULL    COMMENT '备注',
  PARAM_CONFIG LONGTEXT NULL    COMMENT '参数定义',
  constraint UK_NOP_DATAV_DASHBOARD_NAME unique (DASHBOARD_NAME),
  constraint PK_nop_datav_dashboard primary key (DASHBOARD_ID)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs;

CREATE TABLE nop_datav_export_task(
  TASK_ID VARCHAR(32) NOT NULL    COMMENT '任务ID',
  SOURCE_TYPE VARCHAR(20) NOT NULL    COMMENT '来源类型',
  SOURCE_ID VARCHAR(32) NOT NULL    COMMENT '来源ID',
  FORMAT VARCHAR(10) NOT NULL    COMMENT '导出格式',
  STATUS INTEGER NOT NULL    COMMENT '任务状态',
  PARAMS LONGTEXT NULL    COMMENT '导出参数',
  FILE_RECORD_ID VARCHAR(64) NULL    COMMENT '文件记录ID',
  ROW_COUNT BIGINT NULL    COMMENT '导出行数',
  ERROR_MSG VARCHAR(1000) NULL    COMMENT '错误信息',
  DEL_FLAG TINYINT NULL    COMMENT '删除标记',
  VERSION BIGINT NOT NULL    COMMENT '数据版本',
  CREATED_BY VARCHAR(50) NOT NULL    COMMENT '创建人',
  CREATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '创建时间',
  UPDATED_BY VARCHAR(50) NOT NULL    COMMENT '修改人',
  UPDATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '修改时间',
  REMARK VARCHAR(200) NULL    COMMENT '备注',
  constraint PK_nop_datav_export_task primary key (TASK_ID)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs;

CREATE TABLE nop_datav_screen(
  SCREEN_ID VARCHAR(32) NOT NULL    COMMENT '大屏ID',
  SCREEN_NAME VARCHAR(100) NOT NULL    COMMENT '大屏名',
  DISPLAY_NAME VARCHAR(200) NOT NULL    COMMENT '显示名',
  DESCRIPTION VARCHAR(4000) NULL    COMMENT '描述',
  SCREEN_WIDTH INTEGER NOT NULL    COMMENT '画布宽度',
  SCREEN_HEIGHT INTEGER NOT NULL    COMMENT '画布高度',
  ADAPTOR_MODE INTEGER default 10  NULL    COMMENT '适配模式',
  BACKGROUND_CONFIG VARCHAR(4000) NULL    COMMENT '背景配置',
  PUBLISH_STATUS INTEGER NULL    COMMENT '发布状态',
  PUBLISHED_VERSION BIGINT NULL    COMMENT '已发布版本',
  PUBLISHED_BY VARCHAR(50) NULL    COMMENT '发布人',
  PUBLISHED_TIME DATETIME(3) NULL    COMMENT '发布时间',
  DEL_FLAG TINYINT NULL    COMMENT '删除标记',
  VERSION BIGINT NOT NULL    COMMENT '数据版本',
  CREATED_BY VARCHAR(50) NOT NULL    COMMENT '创建人',
  CREATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '创建时间',
  UPDATED_BY VARCHAR(50) NOT NULL    COMMENT '修改人',
  UPDATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '修改时间',
  REMARK VARCHAR(200) NULL    COMMENT '备注',
  THUMBNAIL VARCHAR(4000) NULL    COMMENT '缩略图',
  constraint UK_NOP_DATAV_SCREEN_NAME unique (SCREEN_NAME),
  constraint PK_nop_datav_screen primary key (SCREEN_ID)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs;

CREATE TABLE nop_datav_chat_session(
  SESSION_ID VARCHAR(32) NOT NULL    COMMENT '会话ID',
  USER_NAME VARCHAR(50) NOT NULL    COMMENT '用户名',
  SESSION_TITLE VARCHAR(200) NULL    COMMENT '会话标题',
  DEL_FLAG TINYINT NULL    COMMENT '删除标记',
  VERSION BIGINT NOT NULL    COMMENT '数据版本',
  CREATED_BY VARCHAR(50) NOT NULL    COMMENT '创建人',
  CREATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '创建时间',
  UPDATED_BY VARCHAR(50) NOT NULL    COMMENT '修改人',
  UPDATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '修改时间',
  REMARK VARCHAR(200) NULL    COMMENT '备注',
  constraint PK_nop_datav_chat_session primary key (SESSION_ID)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs;

CREATE TABLE nop_datav_panel(
  PANEL_ID VARCHAR(32) NOT NULL    COMMENT '面板ID',
  DASHBOARD_ID VARCHAR(32) NOT NULL    COMMENT '看板ID',
  PANEL_NAME VARCHAR(100) NOT NULL    COMMENT '面板名',
  DISPLAY_NAME VARCHAR(200) NULL    COMMENT '显示名',
  PANEL_TYPE INTEGER NULL    COMMENT '面板类型',
  DATASET_REF_ID VARCHAR(32) NULL    COMMENT '数据集引用ID',
  TAB_ID VARCHAR(32) NULL    COMMENT '页签ID',
  SORT_ORDER INTEGER default 0  NULL    COMMENT '排序',
  PANEL_CONFIG VARCHAR(4000) NULL    COMMENT '面板配置',
  DEL_FLAG TINYINT NULL    COMMENT '删除标记',
  VERSION BIGINT NOT NULL    COMMENT '数据版本',
  CREATED_BY VARCHAR(50) NOT NULL    COMMENT '创建人',
  CREATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '创建时间',
  UPDATED_BY VARCHAR(50) NOT NULL    COMMENT '修改人',
  UPDATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '修改时间',
  REMARK VARCHAR(200) NULL    COMMENT '备注',
  constraint PK_nop_datav_panel primary key (PANEL_ID)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs;

CREATE TABLE nop_datav_tab(
  TAB_ID VARCHAR(32) NOT NULL    COMMENT '页签ID',
  DASHBOARD_ID VARCHAR(32) NOT NULL    COMMENT '看板ID',
  TAB_NAME VARCHAR(100) NOT NULL    COMMENT '页签名',
  DISPLAY_NAME VARCHAR(200) NULL    COMMENT '显示名',
  SORT_ORDER INTEGER default 0  NULL    COMMENT '排序',
  TAB_CONFIG VARCHAR(4000) NULL    COMMENT '页签配置',
  DEL_FLAG TINYINT NULL    COMMENT '删除标记',
  VERSION BIGINT NOT NULL    COMMENT '数据版本',
  CREATED_BY VARCHAR(50) NOT NULL    COMMENT '创建人',
  CREATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '创建时间',
  UPDATED_BY VARCHAR(50) NOT NULL    COMMENT '修改人',
  UPDATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '修改时间',
  REMARK VARCHAR(200) NULL    COMMENT '备注',
  constraint PK_nop_datav_tab primary key (TAB_ID)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs;

CREATE TABLE nop_datav_dataset_ref(
  DATASET_REF_ID VARCHAR(32) NOT NULL    COMMENT '数据集引用ID',
  DASHBOARD_ID VARCHAR(32) NOT NULL    COMMENT '看板ID',
  REF_DATASET_ID VARCHAR(100) NOT NULL    COMMENT '引用数据集ID',
  REF_DATASET_NAME VARCHAR(200) NULL    COMMENT '引用数据集名',
  PARAM_MAPPING VARCHAR(4000) NULL    COMMENT '参数映射',
  DEL_FLAG TINYINT NULL    COMMENT '删除标记',
  VERSION BIGINT NOT NULL    COMMENT '数据版本',
  CREATED_BY VARCHAR(50) NOT NULL    COMMENT '创建人',
  CREATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '创建时间',
  UPDATED_BY VARCHAR(50) NOT NULL    COMMENT '修改人',
  UPDATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '修改时间',
  REMARK VARCHAR(200) NULL    COMMENT '备注',
  constraint PK_nop_datav_dataset_ref primary key (DATASET_REF_ID)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs;

CREATE TABLE nop_datav_snapshot(
  SNAPSHOT_ID VARCHAR(32) NOT NULL    COMMENT '快照ID',
  DASHBOARD_ID VARCHAR(32) NOT NULL    COMMENT '看板ID',
  SNAPSHOT_VERSION BIGINT NOT NULL    COMMENT '快照版本',
  SNAPSHOT_CONTENT LONGTEXT NULL    COMMENT '快照内容',
  PUBLISHED_BY VARCHAR(50) NULL    COMMENT '发布人',
  PUBLISHED_TIME DATETIME(3) NULL    COMMENT '发布时间',
  DEL_FLAG TINYINT NULL    COMMENT '删除标记',
  VERSION BIGINT NOT NULL    COMMENT '数据版本',
  CREATED_BY VARCHAR(50) NOT NULL    COMMENT '创建人',
  CREATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '创建时间',
  UPDATED_BY VARCHAR(50) NOT NULL    COMMENT '修改人',
  UPDATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '修改时间',
  REMARK VARCHAR(200) NULL    COMMENT '备注',
  constraint UK_NOP_DATAV_SNAPSHOT_DASH_VER unique (DASHBOARD_ID,SNAPSHOT_VERSION),
  constraint PK_nop_datav_snapshot primary key (SNAPSHOT_ID)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs;

CREATE TABLE nop_datav_filter_state(
  STATE_ID VARCHAR(32) NOT NULL    COMMENT '状态ID',
  USER_NAME VARCHAR(50) NOT NULL    COMMENT '用户名',
  DASHBOARD_ID VARCHAR(32) NOT NULL    COMMENT '看板ID',
  STATE_CONTENT LONGTEXT NULL    COMMENT '状态内容',
  DEL_FLAG TINYINT NULL    COMMENT '删除标记',
  VERSION BIGINT NOT NULL    COMMENT '数据版本',
  CREATED_BY VARCHAR(50) NOT NULL    COMMENT '创建人',
  CREATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '创建时间',
  UPDATED_BY VARCHAR(50) NOT NULL    COMMENT '修改人',
  UPDATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '修改时间',
  REMARK VARCHAR(200) NULL    COMMENT '备注',
  constraint UK_NOP_DATAV_FILTER_STATE_USER_DASH unique (USER_NAME,DASHBOARD_ID),
  constraint PK_nop_datav_filter_state primary key (STATE_ID)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs;

CREATE TABLE nop_datav_share(
  SHARE_ID VARCHAR(32) NOT NULL    COMMENT '分享ID',
  SHARE_TOKEN VARCHAR(64) NOT NULL    COMMENT '分享令牌',
  DASHBOARD_ID VARCHAR(32) NOT NULL    COMMENT '看板ID',
  PASSWORD_HASH VARCHAR(200) NULL    COMMENT '密码哈希',
  EXPIRE_TIME DATETIME(3) NULL    COMMENT '过期时间',
  ENABLED TINYINT default 1  NULL    COMMENT '启用标记',
  DEL_FLAG TINYINT NULL    COMMENT '删除标记',
  VERSION BIGINT NOT NULL    COMMENT '数据版本',
  CREATED_BY VARCHAR(50) NOT NULL    COMMENT '创建人',
  CREATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '创建时间',
  UPDATED_BY VARCHAR(50) NOT NULL    COMMENT '修改人',
  UPDATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '修改时间',
  REMARK VARCHAR(200) NULL    COMMENT '备注',
  VISIT_COUNT BIGINT default 0  NULL    COMMENT '访问计数',
  LAST_VISIT_TIME DATETIME(3) NULL    COMMENT '最近访问时间',
  constraint UK_NOP_DATAV_SHARE_TOKEN unique (SHARE_TOKEN),
  constraint PK_nop_datav_share primary key (SHARE_ID)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs;

CREATE TABLE nop_datav_report_task(
  REPORT_TASK_ID VARCHAR(32) NOT NULL    COMMENT '报告任务ID',
  TASK_NAME VARCHAR(100) NOT NULL    COMMENT '任务名',
  DISPLAY_NAME VARCHAR(200) NULL    COMMENT '显示名',
  DASHBOARD_ID VARCHAR(32) NOT NULL    COMMENT '看板ID',
  CRON_EXPR VARCHAR(100) NOT NULL    COMMENT 'cron表达式',
  FORMAT VARCHAR(10) NOT NULL    COMMENT '导出格式',
  RECIPIENTS LONGTEXT NULL    COMMENT '收件人',
  NOTIFY_CHANNELS LONGTEXT NULL    COMMENT '通知渠道',
  PARAMS LONGTEXT NULL    COMMENT '报告参数',
  STATUS INTEGER NOT NULL    COMMENT '任务状态',
  GRACE_MINUTES INTEGER default 60  NULL    COMMENT 'grace期(分钟)',
  TEMPLATE_KEY VARCHAR(100) NULL    COMMENT '模板键',
  LAST_RUN_TIME DATETIME(3) NULL    COMMENT '最后执行时间',
  LAST_RUN_STATUS VARCHAR(20) NULL    COMMENT '最后执行状态',
  LAST_RUN_ERROR VARCHAR(1000) NULL    COMMENT '最后执行错误',
  DEL_FLAG TINYINT NULL    COMMENT '删除标记',
  VERSION BIGINT NOT NULL    COMMENT '数据版本',
  CREATED_BY VARCHAR(50) NOT NULL    COMMENT '创建人',
  CREATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '创建时间',
  UPDATED_BY VARCHAR(50) NOT NULL    COMMENT '修改人',
  UPDATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '修改时间',
  REMARK VARCHAR(200) NULL    COMMENT '备注',
  constraint PK_nop_datav_report_task primary key (REPORT_TASK_ID)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs;

CREATE TABLE nop_datav_screen_widget(
  WIDGET_ID VARCHAR(32) NOT NULL    COMMENT '组件ID',
  SCREEN_ID VARCHAR(32) NOT NULL    COMMENT '大屏ID',
  WIDGET_NAME VARCHAR(100) NULL    COMMENT '组件名',
  DISPLAY_NAME VARCHAR(200) NULL    COMMENT '显示名',
  COMPONENT_TYPE VARCHAR(50) NOT NULL    COMMENT '组件类型',
  DATASET_REF_ID VARCHAR(32) NULL    COMMENT '数据集引用ID',
  X INTEGER default 0  NOT NULL    COMMENT 'X坐标',
  Y INTEGER default 0  NOT NULL    COMMENT 'Y坐标',
  W INTEGER NOT NULL    COMMENT '宽度',
  H INTEGER NOT NULL    COMMENT '高度',
  Z INTEGER default 0  NULL    COMMENT '层级',
  WIDGET_CONFIG VARCHAR(4000) NULL    COMMENT '组件配置',
  DEL_FLAG TINYINT NULL    COMMENT '删除标记',
  VERSION BIGINT NOT NULL    COMMENT '数据版本',
  CREATED_BY VARCHAR(50) NOT NULL    COMMENT '创建人',
  CREATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '创建时间',
  UPDATED_BY VARCHAR(50) NOT NULL    COMMENT '修改人',
  UPDATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '修改时间',
  REMARK VARCHAR(200) NULL    COMMENT '备注',
  constraint PK_nop_datav_screen_widget primary key (WIDGET_ID)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs;

CREATE TABLE nop_datav_screen_snapshot(
  SNAPSHOT_ID VARCHAR(32) NOT NULL    COMMENT '快照ID',
  SCREEN_ID VARCHAR(32) NOT NULL    COMMENT '大屏ID',
  SNAPSHOT_VERSION BIGINT NOT NULL    COMMENT '快照版本',
  SNAPSHOT_CONTENT LONGTEXT NOT NULL    COMMENT '快照内容',
  PUBLISHED_BY VARCHAR(50) NULL    COMMENT '发布人',
  PUBLISHED_TIME DATETIME(3) NULL    COMMENT '发布时间',
  DEL_FLAG TINYINT NULL    COMMENT '删除标记',
  VERSION BIGINT NOT NULL    COMMENT '数据版本',
  CREATED_BY VARCHAR(50) NOT NULL    COMMENT '创建人',
  CREATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '创建时间',
  UPDATED_BY VARCHAR(50) NOT NULL    COMMENT '修改人',
  UPDATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '修改时间',
  REMARK VARCHAR(200) NULL    COMMENT '备注',
  constraint UK_NOP_DATAV_SCREEN_SNAPSHOT_SCREEN_VER unique (SCREEN_ID,SNAPSHOT_VERSION),
  constraint PK_nop_datav_screen_snapshot primary key (SNAPSHOT_ID)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs;

CREATE TABLE nop_datav_chat_message(
  MESSAGE_ID VARCHAR(32) NOT NULL    COMMENT '消息ID',
  SESSION_ID VARCHAR(32) NOT NULL    COMMENT '会话ID',
  SEQ INTEGER NOT NULL    COMMENT '消息序号',
  ROLE VARCHAR(20) NOT NULL    COMMENT '消息角色',
  CONTENT LONGTEXT NOT NULL    COMMENT '消息内容',
  RESULT_JSON LONGTEXT NULL    COMMENT '结构化结果JSON',
  DEL_FLAG TINYINT NULL    COMMENT '删除标记',
  VERSION BIGINT NOT NULL    COMMENT '数据版本',
  CREATED_BY VARCHAR(50) NOT NULL    COMMENT '创建人',
  CREATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '创建时间',
  UPDATED_BY VARCHAR(50) NOT NULL    COMMENT '修改人',
  UPDATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '修改时间',
  REMARK VARCHAR(200) NULL    COMMENT '备注',
  constraint UK_NOP_DATAV_CHAT_MSG_SESSION_SEQ unique (SESSION_ID,SEQ),
  constraint PK_nop_datav_chat_message primary key (MESSAGE_ID)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs;

CREATE TABLE nop_datav_alert_rule(
  ALERT_RULE_ID VARCHAR(32) NOT NULL    COMMENT '告警规则ID',
  RULE_NAME VARCHAR(100) NOT NULL    COMMENT '规则名',
  DISPLAY_NAME VARCHAR(200) NULL    COMMENT '显示名',
  PANEL_ID VARCHAR(32) NOT NULL    COMMENT '面板ID',
  VALUE_FIELD VARCHAR(100) NOT NULL    COMMENT '取值字段',
  AGGREGATION VARCHAR(20) NOT NULL    COMMENT '聚合方式',
  OPERATOR VARCHAR(20) NOT NULL    COMMENT '比较运算符',
  THRESHOLD_VALUE DECIMAL(20,4) NOT NULL    COMMENT '阈值',
  THRESHOLD_VALUE2 DECIMAL(20,4) NULL    COMMENT '阈值上限',
  REARM_SECONDS INTEGER default 0  NULL    COMMENT '冷静期秒数',
  NOTIFY_CHANNELS LONGTEXT NULL    COMMENT '通知渠道',
  RECIPIENTS LONGTEXT NULL    COMMENT '收件人',
  CRON_EXPR VARCHAR(100) NOT NULL    COMMENT 'cron表达式',
  PARAMS LONGTEXT NULL    COMMENT '查询参数',
  TEMPLATE_KEY VARCHAR(100) NULL    COMMENT '模板键',
  STATUS INTEGER NOT NULL    COMMENT '规则状态',
  DEL_FLAG TINYINT NULL    COMMENT '删除标记',
  VERSION BIGINT NOT NULL    COMMENT '数据版本',
  CREATED_BY VARCHAR(50) NOT NULL    COMMENT '创建人',
  CREATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '创建时间',
  UPDATED_BY VARCHAR(50) NOT NULL    COMMENT '修改人',
  UPDATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '修改时间',
  REMARK VARCHAR(200) NULL    COMMENT '备注',
  constraint PK_nop_datav_alert_rule primary key (ALERT_RULE_ID)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs;

CREATE TABLE nop_datav_report_delivery(
  DELIVERY_ID VARCHAR(32) NOT NULL    COMMENT '交付ID',
  REPORT_TASK_ID VARCHAR(32) NOT NULL    COMMENT '报告任务ID',
  STATUS INTEGER NOT NULL    COMMENT '交付状态',
  GENERATED_FILE_RECORD_ID VARCHAR(64) NULL    COMMENT '生成文件记录ID',
  DELIVERED_CHANNELS VARCHAR(200) NULL    COMMENT '已送达渠道',
  ROW_COUNT BIGINT NULL    COMMENT '导出行数',
  ERROR_MSG VARCHAR(1000) NULL    COMMENT '错误信息',
  TRIGGERED_BY VARCHAR(20) NOT NULL    COMMENT '触发来源',
  START_TIME DATETIME(3) NULL    COMMENT '开始时间',
  END_TIME DATETIME(3) NULL    COMMENT '结束时间',
  DEL_FLAG TINYINT NULL    COMMENT '删除标记',
  VERSION BIGINT NOT NULL    COMMENT '数据版本',
  CREATED_BY VARCHAR(50) NOT NULL    COMMENT '创建人',
  CREATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '创建时间',
  UPDATED_BY VARCHAR(50) NOT NULL    COMMENT '修改人',
  UPDATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '修改时间',
  REMARK VARCHAR(200) NULL    COMMENT '备注',
  constraint PK_nop_datav_report_delivery primary key (DELIVERY_ID)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs;

CREATE TABLE nop_datav_alert_state(
  ALERT_STATE_ID VARCHAR(32) NOT NULL    COMMENT '状态ID',
  ALERT_RULE_ID VARCHAR(32) NOT NULL    COMMENT '告警规则ID',
  STATE VARCHAR(20) NOT NULL    COMMENT '告警状态',
  LAST_EVAL_TIME DATETIME(3) NULL    COMMENT '最后评估时间',
  LAST_TRIGGERED_TIME DATETIME(3) NULL    COMMENT '最后触发时间',
  LAST_RESOLVED_TIME DATETIME(3) NULL    COMMENT '最后恢复时间',
  LAST_NOTIFIED_TIME DATETIME(3) NULL    COMMENT '最后通知时间',
  CONSECUTIVE_EVAL_COUNT INTEGER default 0  NULL    COMMENT '连续评估满足次数',
  ERROR_MSG VARCHAR(1000) NULL    COMMENT '错误信息',
  DEL_FLAG TINYINT NULL    COMMENT '删除标记',
  VERSION BIGINT NOT NULL    COMMENT '数据版本',
  CREATED_BY VARCHAR(50) NOT NULL    COMMENT '创建人',
  CREATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '创建时间',
  UPDATED_BY VARCHAR(50) NOT NULL    COMMENT '修改人',
  UPDATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '修改时间',
  REMARK VARCHAR(200) NULL    COMMENT '备注',
  constraint UK_NOP_DATAV_ALERT_STATE_RULE unique (ALERT_RULE_ID),
  constraint PK_nop_datav_alert_state primary key (ALERT_STATE_ID)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs;


   ALTER TABLE nop_datav_dashboard COMMENT '看板';
                
   ALTER TABLE nop_datav_export_task COMMENT '导出任务';
                
   ALTER TABLE nop_datav_screen COMMENT '大屏';
                
   ALTER TABLE nop_datav_chat_session COMMENT 'ChatBI会话';
                
   ALTER TABLE nop_datav_panel COMMENT '面板';
                
   ALTER TABLE nop_datav_tab COMMENT '页签';
                
   ALTER TABLE nop_datav_dataset_ref COMMENT '数据集引用';
                
   ALTER TABLE nop_datav_snapshot COMMENT '发布快照';
                
   ALTER TABLE nop_datav_filter_state COMMENT '筛选状态';
                
   ALTER TABLE nop_datav_share COMMENT '看板分享';
                
   ALTER TABLE nop_datav_report_task COMMENT '定时报告任务';
                
   ALTER TABLE nop_datav_screen_widget COMMENT '大屏组件';
                
   ALTER TABLE nop_datav_screen_snapshot COMMENT '大屏快照';
                
   ALTER TABLE nop_datav_chat_message COMMENT 'ChatBI会话消息';
                
   ALTER TABLE nop_datav_alert_rule COMMENT '告警规则';
                
   ALTER TABLE nop_datav_report_delivery COMMENT '报告交付历史';
                
   ALTER TABLE nop_datav_alert_state COMMENT '告警状态';
                
