
CREATE TABLE nop_datav_dashboard(
  DASHBOARD_ID VARCHAR(32) NOT NULL    COMMENT '看板ID',
  DASHBOARD_NAME VARCHAR(100) NOT NULL    COMMENT '看板名',
  DISPLAY_NAME VARCHAR(200) NOT NULL    COMMENT '显示名',
  DESCRIPTION VARCHAR(4000) NULL    COMMENT '描述',
  DASHBOARD_TYPE INTEGER NULL    COMMENT '看板类型',
  PUBLISH_STATUS INTEGER NULL    COMMENT '发布状态',
  PUBLISHED_VERSION BIGINT NULL    COMMENT '已发布版本',
  PUBLISHED_BY VARCHAR(50) NULL    COMMENT '发布人',
  PUBLISHED_TIME DATETIME(3) NULL    COMMENT '发布时间',
  LAYOUT_CONFIG VARCHAR(4000) NULL    COMMENT '布局配置',
  DEL_FLAG TINYINT NULL    COMMENT '删除标记',
  VERSION BIGINT NOT NULL    COMMENT '数据版本',
  CREATED_BY VARCHAR(50) NOT NULL    COMMENT '创建人',
  CREATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '创建时间',
  UPDATED_BY VARCHAR(50) NOT NULL    COMMENT '修改人',
  UPDATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '修改时间',
  REMARK VARCHAR(200) NULL    COMMENT '备注',
  PARAM_CONFIG LONGTEXT NULL    COMMENT '参数定义',
  constraint PK_nop_datav_dashboard primary key (DASHBOARD_ID)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs;

CREATE TABLE nop_datav_panel(
  PANEL_ID VARCHAR(32) NOT NULL    COMMENT '面板ID',
  DASHBOARD_ID VARCHAR(32) NOT NULL    COMMENT '看板ID',
  PANEL_NAME VARCHAR(100) NOT NULL    COMMENT '面板名',
  DISPLAY_NAME VARCHAR(200) NULL    COMMENT '显示名',
  PANEL_TYPE INTEGER NULL    COMMENT '面板类型',
  DATASET_REF_ID VARCHAR(32) NULL    COMMENT '数据集引用ID',
  TAB_ID VARCHAR(32) NULL    COMMENT '页签ID',
  SORT_ORDER INTEGER default 0  NULL    COMMENT '排序',
  PANEL_CONFIG VARCHAR(4000) NULL    COMMENT '面板配置',
  DEL_FLAG TINYINT NULL    COMMENT '删除标记',
  VERSION BIGINT NOT NULL    COMMENT '数据版本',
  CREATED_BY VARCHAR(50) NOT NULL    COMMENT '创建人',
  CREATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '创建时间',
  UPDATED_BY VARCHAR(50) NOT NULL    COMMENT '修改人',
  UPDATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '修改时间',
  REMARK VARCHAR(200) NULL    COMMENT '备注',
  constraint PK_nop_datav_panel primary key (PANEL_ID)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs;

CREATE TABLE nop_datav_tab(
  TAB_ID VARCHAR(32) NOT NULL    COMMENT '页签ID',
  DASHBOARD_ID VARCHAR(32) NOT NULL    COMMENT '看板ID',
  TAB_NAME VARCHAR(100) NOT NULL    COMMENT '页签名',
  DISPLAY_NAME VARCHAR(200) NULL    COMMENT '显示名',
  SORT_ORDER INTEGER default 0  NULL    COMMENT '排序',
  TAB_CONFIG VARCHAR(4000) NULL    COMMENT '页签配置',
  DEL_FLAG TINYINT NULL    COMMENT '删除标记',
  VERSION BIGINT NOT NULL    COMMENT '数据版本',
  CREATED_BY VARCHAR(50) NOT NULL    COMMENT '创建人',
  CREATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '创建时间',
  UPDATED_BY VARCHAR(50) NOT NULL    COMMENT '修改人',
  UPDATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '修改时间',
  REMARK VARCHAR(200) NULL    COMMENT '备注',
  constraint PK_nop_datav_tab primary key (TAB_ID)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs;

CREATE TABLE nop_datav_dataset_ref(
  DATASET_REF_ID VARCHAR(32) NOT NULL    COMMENT '数据集引用ID',
  DASHBOARD_ID VARCHAR(32) NOT NULL    COMMENT '看板ID',
  REF_DATASET_ID VARCHAR(100) NOT NULL    COMMENT '引用数据集ID',
  REF_DATASET_NAME VARCHAR(200) NULL    COMMENT '引用数据集名',
  PARAM_MAPPING VARCHAR(4000) NULL    COMMENT '参数映射',
  DEL_FLAG TINYINT NULL    COMMENT '删除标记',
  VERSION BIGINT NOT NULL    COMMENT '数据版本',
  CREATED_BY VARCHAR(50) NOT NULL    COMMENT '创建人',
  CREATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '创建时间',
  UPDATED_BY VARCHAR(50) NOT NULL    COMMENT '修改人',
  UPDATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '修改时间',
  REMARK VARCHAR(200) NULL    COMMENT '备注',
  constraint PK_nop_datav_dataset_ref primary key (DATASET_REF_ID)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs;

CREATE TABLE nop_datav_snapshot(
  SNAPSHOT_ID VARCHAR(32) NOT NULL    COMMENT '快照ID',
  DASHBOARD_ID VARCHAR(32) NOT NULL    COMMENT '看板ID',
  SNAPSHOT_VERSION BIGINT NOT NULL    COMMENT '快照版本',
  SNAPSHOT_CONTENT LONGTEXT NULL    COMMENT '快照内容',
  PUBLISHED_BY VARCHAR(50) NULL    COMMENT '发布人',
  PUBLISHED_TIME DATETIME(3) NULL    COMMENT '发布时间',
  DEL_FLAG TINYINT NULL    COMMENT '删除标记',
  VERSION BIGINT NOT NULL    COMMENT '数据版本',
  CREATED_BY VARCHAR(50) NOT NULL    COMMENT '创建人',
  CREATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '创建时间',
  UPDATED_BY VARCHAR(50) NOT NULL    COMMENT '修改人',
  UPDATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '修改时间',
  REMARK VARCHAR(200) NULL    COMMENT '备注',
  constraint PK_nop_datav_snapshot primary key (SNAPSHOT_ID)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs;

CREATE TABLE nop_datav_filter_state(
  STATE_ID VARCHAR(32) NOT NULL    COMMENT '状态ID',
  USER_NAME VARCHAR(50) NOT NULL    COMMENT '用户名',
  DASHBOARD_ID VARCHAR(32) NOT NULL    COMMENT '看板ID',
  STATE_CONTENT LONGTEXT NULL    COMMENT '状态内容',
  DEL_FLAG TINYINT NULL    COMMENT '删除标记',
  VERSION BIGINT NOT NULL    COMMENT '数据版本',
  CREATED_BY VARCHAR(50) NOT NULL    COMMENT '创建人',
  CREATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '创建时间',
  UPDATED_BY VARCHAR(50) NOT NULL    COMMENT '修改人',
  UPDATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '修改时间',
  REMARK VARCHAR(200) NULL    COMMENT '备注',
  constraint PK_nop_datav_filter_state primary key (STATE_ID)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs;

CREATE TABLE nop_datav_share(
  SHARE_ID VARCHAR(32) NOT NULL    COMMENT '分享ID',
  SHARE_TOKEN VARCHAR(64) NOT NULL    COMMENT '分享令牌',
  DASHBOARD_ID VARCHAR(32) NOT NULL    COMMENT '看板ID',
  PASSWORD_HASH VARCHAR(200) NULL    COMMENT '密码哈希',
  EXPIRE_TIME DATETIME(3) NULL    COMMENT '过期时间',
  ENABLED TINYINT default 1  NULL    COMMENT '启用标记',
  DEL_FLAG TINYINT NULL    COMMENT '删除标记',
  VERSION BIGINT NOT NULL    COMMENT '数据版本',
  CREATED_BY VARCHAR(50) NOT NULL    COMMENT '创建人',
  CREATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '创建时间',
  UPDATED_BY VARCHAR(50) NOT NULL    COMMENT '修改人',
  UPDATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '修改时间',
  REMARK VARCHAR(200) NULL    COMMENT '备注',
  constraint PK_nop_datav_share primary key (SHARE_ID)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs;


   ALTER TABLE nop_datav_dashboard COMMENT '看板';
                
   ALTER TABLE nop_datav_panel COMMENT '面板';
                
   ALTER TABLE nop_datav_tab COMMENT '页签';
                
   ALTER TABLE nop_datav_dataset_ref COMMENT '数据集引用';
                
   ALTER TABLE nop_datav_snapshot COMMENT '发布快照';
                
   ALTER TABLE nop_datav_filter_state COMMENT '筛选状态';
                
   ALTER TABLE nop_datav_share COMMENT '看板分享';
                
