
CREATE TABLE nop_task_definition(
  TASK_DEF_ID VARCHAR(32) NOT NULL    COMMENT '主键',
  TASK_NAME VARCHAR(500) NOT NULL    COMMENT '逻辑流名称',
  TASK_VERSION BIGINT NOT NULL    COMMENT '逻辑流版本',
  DISPLAY_NAME VARCHAR(200) NOT NULL    COMMENT '显示名称',
  DESCRIPTION VARCHAR(1000) NULL    COMMENT '描述',
  MODEL_TEXT LONGTEXT NOT NULL    COMMENT '模型文本',
  STATUS INTEGER NOT NULL    COMMENT '状态',
  VERSION INTEGER NOT NULL    COMMENT '数据版本',
  CREATED_BY VARCHAR(50) NOT NULL    COMMENT '创建人',
  CREATE_TIME TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '创建时间',
  UPDATED_BY VARCHAR(50) NOT NULL    COMMENT '修改人',
  UPDATE_TIME TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '修改时间',
  REMARK VARCHAR(200) NULL    COMMENT '备注',
  constraint PK_nop_task_definition primary key (TASK_DEF_ID)
);

CREATE TABLE nop_task_instance(
  TASK_ID VARCHAR(32) NOT NULL    COMMENT '主键',
  TASK_NAME VARCHAR(500) NOT NULL    COMMENT '逻辑流名称',
  TASK_VERSION BIGINT NOT NULL    COMMENT '逻辑流版本',
  TASK_INPUTS VARCHAR(4000) NULL    COMMENT '逻辑流参数',
  TASK_GROUP VARCHAR(100) NOT NULL    COMMENT '逻辑流分组',
  STATUS INTEGER NOT NULL    COMMENT '状态',
  START_TIME TIMESTAMP(3) NULL    COMMENT '启动时间',
  END_TIME TIMESTAMP(3) NULL    COMMENT '结束时间',
  DUE_TIME TIMESTAMP(3) NULL    COMMENT '完成时限',
  BIZ_KEY VARCHAR(200) NULL    COMMENT '业务唯一键',
  BIZ_OBJ_NAME VARCHAR(200) NULL    COMMENT '业务对象名',
  BIZ_OBJ_ID VARCHAR(200) NULL    COMMENT '业务对象ID',
  PARENT_TASK_NAME VARCHAR(500) NULL    COMMENT '父流程名称',
  PARENT_TASK_VERSION BIGINT NULL    COMMENT '父流程版本',
  PARENT_TASK_ID VARCHAR(32) NULL    COMMENT '父流程ID',
  PARENT_STEP_ID VARCHAR(200) NULL    COMMENT '父流程步骤ID',
  STARTER_ID VARCHAR(50) NULL    COMMENT '启动人ID',
  STARTER_NAME VARCHAR(50) NULL    COMMENT '启动人',
  STARTER_DEPT_ID VARCHAR(50) NULL    COMMENT '启动人单位ID',
  MANAGER_TYPE VARCHAR(50) NULL    COMMENT '管理者类型',
  MANAGER_DEPT_ID VARCHAR(50) NULL    COMMENT '管理者单位ID',
  MANAGER_NAME VARCHAR(50) NULL    COMMENT '管理者',
  MANAGER_ID VARCHAR(50) NULL    COMMENT '管理者ID',
  PRIORITY INTEGER NOT NULL    COMMENT '优先级',
  SIGNAL_TEXT VARCHAR(1000) NULL    COMMENT '信号集合',
  TAG_TEXT VARCHAR(200) NULL    COMMENT '标签',
  JOB_ID VARCHAR(32) NULL    COMMENT 'Job ID',
  ERR_CODE VARCHAR(200) NULL    COMMENT '错误码',
  ERR_MSG VARCHAR(500) NULL    COMMENT '错误消息',
  Worker_ID VARCHAR(50) NULL    COMMENT 'Worker ID',
  VERSION INTEGER NOT NULL    COMMENT '数据版本',
  CREATED_BY VARCHAR(50) NOT NULL    COMMENT '创建人',
  CREATE_TIME TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '创建时间',
  UPDATED_BY VARCHAR(50) NOT NULL    COMMENT '修改人',
  UPDATE_TIME TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '修改时间',
  REMARK VARCHAR(200) NULL    COMMENT '备注',
  constraint PK_nop_task_instance primary key (TASK_ID)
);

CREATE TABLE nop_task_definition_auth(
  SID VARCHAR(32) NOT NULL    COMMENT '主键',
  TASK_DEF_ID VARCHAR(32) NOT NULL    COMMENT '工作流定义ID',
  ACTOR_TYPE VARCHAR(10) NOT NULL    COMMENT '参与者类型',
  ACTOR_ID VARCHAR(100) NOT NULL    COMMENT '参与者ID',
  ACTOR_DEPT_ID VARCHAR(50) NULL    COMMENT '参与者部门ID',
  ACTOR_NAME VARCHAR(100) NOT NULL    COMMENT '参与者名称',
  ALLOW_EDIT BOOLEAN NOT NULL    COMMENT '允许编辑',
  ALLOW_MANAGE BOOLEAN NOT NULL    COMMENT '允许管理',
  ALLOW_START BOOLEAN NOT NULL    COMMENT '允许启动',
  VERSION INTEGER NOT NULL    COMMENT '数据版本',
  CREATED_BY VARCHAR(50) NOT NULL    COMMENT '创建人',
  CREATE_TIME TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '创建时间',
  UPDATED_BY VARCHAR(50) NOT NULL    COMMENT '修改人',
  UPDATE_TIME TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '修改时间',
  REMARK VARCHAR(200) NULL    COMMENT '备注',
  constraint PK_nop_task_definition_auth primary key (SID)
);

CREATE TABLE nop_task_step_instance(
  STEP_ID VARCHAR(32) NOT NULL    COMMENT '步骤ID',
  TASK_ID VARCHAR(32) NOT NULL    COMMENT '逻辑流实例ID',
  STEP_TYPE VARCHAR(20) NOT NULL    COMMENT '步骤类型',
  STEP_NAME VARCHAR(200) NOT NULL    COMMENT '步骤名称',
  DISPLAY_NAME VARCHAR(200) NOT NULL    COMMENT '步骤显示名称',
  STATUS INTEGER NOT NULL    COMMENT '状态',
  SUB_TASK_ID VARCHAR(32) NULL    COMMENT '子流程ID',
  SUB_TASK_NAME VARCHAR(200) NULL    COMMENT '子流程名称',
  SUB_TASK_VERSION BIGINT NULL    COMMENT '子流程版本',
  START_TIME TIMESTAMP(3) NULL    COMMENT '开始时间',
  FINISH_TIME TIMESTAMP(3) NULL    COMMENT '结束时间',
  DUE_TIME TIMESTAMP(3) NULL    COMMENT '到期时间',
  NEXT_RETRY_TIME TIMESTAMP(3) NULL    COMMENT '下次重试时间',
  RETRY_COUNT INTEGER NULL    COMMENT '已重试次数',
  ERR_CODE VARCHAR(200) NULL    COMMENT '错误码',
  ERR_MSG VARCHAR(4000) NULL    COMMENT '错误消息',
  PRIORITY INTEGER NOT NULL    COMMENT '优先级',
  TAG_TEXT VARCHAR(200) NULL    COMMENT '标签',
  PARENT_STEP_ID VARCHAR(32) NULL    COMMENT '父步骤ID',
  VERSION INTEGER NOT NULL    COMMENT '数据版本',
  CREATED_BY VARCHAR(50) NOT NULL    COMMENT '创建人',
  CREATE_TIME TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '创建时间',
  UPDATED_BY VARCHAR(50) NOT NULL    COMMENT '修改人',
  UPDATE_TIME TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '修改时间',
  REMARK VARCHAR(200) NULL    COMMENT '备注',
  constraint PK_nop_task_step_instance primary key (STEP_ID)
);


   ALTER TABLE nop_task_definition COMMENT '逻辑流模型定义';
                
   ALTER TABLE nop_task_instance COMMENT '逻辑流实例';
                
   ALTER TABLE nop_task_definition_auth COMMENT '逻辑流定义权限';
                
   ALTER TABLE nop_task_step_instance COMMENT '逻辑流步骤实例';
                
