
CREATE TABLE nop_job_definition(
  SID VARCHAR(32) NOT NULL    COMMENT 'SID',
  DISPLAY_NAME VARCHAR(200) NOT NULL    COMMENT '显示名',
  JOB_NAME VARCHAR(100) NOT NULL    COMMENT '任务名',
  JOB_GROUP VARCHAR(100) NOT NULL    COMMENT '任务组',
  JOB_PARAMS VARCHAR(4000) NULL    COMMENT '任务参数',
  JOB_INVOKER VARCHAR(200) NOT NULL    COMMENT '任务执行函数',
  DESCRIPTION VARCHAR(4000) NULL    COMMENT '任务描述',
  STATUS INTEGER NOT NULL    COMMENT '任务状态',
  CRON_EXPR VARCHAR(100) NULL    COMMENT '定时表达式',
  REPEAT_INTERVAL INTEGER NULL    COMMENT '定时执行间隔',
  IS_FIXED_DELAY TINYINT default 0  NULL    COMMENT '是否固定延时',
  MAX_EXECUTION_COUNT INTEGER NULL    COMMENT '最多执行次数',
  MIN_SCHEDULE_TIME DATETIME(3) NULL    COMMENT '最近调度时间',
  MAX_SCHEDULE_TIME DATETIME(3) NULL    COMMENT '最大调度时间',
  MISFIRE_THRESHOLD INTEGER NULL    COMMENT '超时阈值',
  MAX_FAILED_COUNT INTEGER NULL    COMMENT '最大允许失败次数',
  MAX_CONSEC_FAILED_COUNT INTEGER NULL    COMMENT '最大允许连续失败次数',
  IS_USE_DEFAULT_CALENDAR TINYINT default 0  NULL    COMMENT '使用系统内置日历',
  PAUSE_CALENDARS VARCHAR(4000) NULL    COMMENT '暂停日历',
  PARTITION_INDEX SMALLINT NOT NULL    COMMENT '分区索引',
  VERSION BIGINT NOT NULL    COMMENT '数据版本',
  CREATED_BY VARCHAR(50) NOT NULL    COMMENT '创建人',
  CREATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '创建时间',
  UPDATED_BY VARCHAR(50) NOT NULL    COMMENT '修改人',
  UPDATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '修改时间',
  REMARK VARCHAR(200) NULL    COMMENT '备注',
  constraint PK_nop_job_definition primary key (SID)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs;

CREATE TABLE nop_job_assignment(
  SERVER_ID VARCHAR(50) NOT NULL    COMMENT '服务实例ID',  ASSIGNMENT VARCHAR(1000) NOT NULL    COMMENT '任务分配',
  VERSION BIGINT NOT NULL    COMMENT '数据版本',
  CREATED_BY VARCHAR(50) NOT NULL    COMMENT '创建人',
  CREATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '创建时间',
  UPDATED_BY VARCHAR(50) NOT NULL    COMMENT '修改人',
  UPDATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '修改时间',
  REMARK VARCHAR(200) NULL    COMMENT '备注',
  constraint PK_nop_job_assignment primary key (SERVER_ID)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs;

CREATE TABLE nop_job_instance_his(
  JOB_INSTANCE_ID VARCHAR(32) NOT NULL    COMMENT '任务实例ID',  JOB_DEF_ID VARCHAR(32) NULL    COMMENT '任务定义ID',
  JOB_NAME VARCHAR(100) NOT NULL    COMMENT '任务名',
  JOB_GROUP VARCHAR(100) NOT NULL    COMMENT '任务组',
  JOB_PARAMS VARCHAR(4000) NULL    COMMENT '任务参数',
  JOB_INVOKER VARCHAR(200) NOT NULL    COMMENT '任务执行函数',
  STATUS INTEGER NOT NULL    COMMENT '任务状态',
  SCHEDULED_EXEC_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '调度执行时间',
  EXEC_COUNT BIGINT NOT NULL    COMMENT '执行次数',
  EXEC_BEGIN_TIME DATETIME(3) NULL    COMMENT '本次执行开始时间',
  EXEC_END_TIME DATETIME(3) NULL    COMMENT '本次执行完成时间',
  ONCE_TASK BOOLEAN NULL    COMMENT '是否只执行一次',
  MANUAL_FIRE BOOLEAN NULL    COMMENT '是否手工触发',
  FIRED_BY VARCHAR(50) NULL    COMMENT '触发执行的用户',
  CONSECUTIVE_FAIL_COUNT INTEGER NULL    COMMENT '连续失败次数',
  TOTAL_FAIL_COUNT INTEGER NULL    COMMENT '总失败次数',
  ERR_CODE VARCHAR(200) NULL    COMMENT '错误码',
  ERR_MSG VARCHAR(500) NULL    COMMENT '错误消息',
  LAST_JOB_INSTANCE_ID VARCHAR(32) NULL    COMMENT '上次任务实例ID',
  PARTITION_INDEX SMALLINT NOT NULL    COMMENT '分区索引',
  VERSION BIGINT NOT NULL    COMMENT '数据版本',
  CREATED_BY VARCHAR(50) NOT NULL    COMMENT '创建人',
  CREATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '创建时间',
  UPDATED_BY VARCHAR(50) NOT NULL    COMMENT '修改人',
  UPDATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '修改时间',
  REMARK VARCHAR(200) NULL    COMMENT '备注',
  constraint PK_nop_job_instance_his primary key (JOB_INSTANCE_ID)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs;

CREATE TABLE nop_job_instance(
  JOB_INSTANCE_ID VARCHAR(32) NOT NULL    COMMENT '任务实例ID',  JOB_DEF_ID VARCHAR(32) NULL    COMMENT '任务定义ID',
  JOB_NAME VARCHAR(100) NOT NULL    COMMENT '任务名',
  JOB_GROUP VARCHAR(100) NOT NULL    COMMENT '任务组',
  JOB_PARAMS VARCHAR(4000) NULL    COMMENT '任务参数',
  JOB_INVOKER VARCHAR(200) NOT NULL    COMMENT '任务执行函数',
  STATUS INTEGER NOT NULL    COMMENT '任务状态',
  SCHEDULED_EXEC_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '调度执行时间',
  EXEC_COUNT BIGINT NOT NULL    COMMENT '执行次数',
  EXEC_BEGIN_TIME DATETIME(3) NULL    COMMENT '本次执行开始时间',
  EXEC_END_TIME DATETIME(3) NULL    COMMENT '本次执行完成时间',
  ONCE_TASK BOOLEAN NULL    COMMENT '是否只执行一次',
  MANUAL_FIRE BOOLEAN NULL    COMMENT '是否手工触发',
  FIRED_BY VARCHAR(50) NULL    COMMENT '触发执行的用户',
  CONSECUTIVE_FAIL_COUNT INTEGER NULL    COMMENT '连续失败次数',
  TOTAL_FAIL_COUNT INTEGER NULL    COMMENT '总失败次数',
  ERR_CODE VARCHAR(200) NULL    COMMENT '错误码',
  ERR_MSG VARCHAR(500) NULL    COMMENT '错误消息',
  LAST_JOB_INSTANCE_ID VARCHAR(32) NULL    COMMENT '上次任务实例ID',
  PARTITION_INDEX SMALLINT NOT NULL    COMMENT '分区索引',
  VERSION BIGINT NOT NULL    COMMENT '数据版本',
  CREATED_BY VARCHAR(50) NOT NULL    COMMENT '创建人',
  CREATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '创建时间',
  UPDATED_BY VARCHAR(50) NOT NULL    COMMENT '修改人',
  UPDATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '修改时间',
  REMARK VARCHAR(200) NULL    COMMENT '备注',
  constraint PK_nop_job_instance primary key (JOB_INSTANCE_ID)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs;


   ALTER TABLE nop_job_definition COMMENT '作业定义';                
   ALTER TABLE nop_job_assignment COMMENT '任务分配';
                
   ALTER TABLE nop_job_instance_his COMMENT '任务实例历史';
                
   ALTER TABLE nop_job_instance COMMENT '任务实例';
                
