
CREATE TABLE nop_job_plan(
  SID VARCHAR(32) NOT NULL    COMMENT 'SID',
  DISPLAY_NAME VARCHAR(200) NOT NULL    COMMENT '显示名',
  JOB_NAME VARCHAR(100) NOT NULL    COMMENT '任务名',
  JOB_GROUP VARCHAR(100) NOT NULL    COMMENT '任务组',
  JOB_PARAMS VARCHAR(4000)     COMMENT '任务参数',
  JOB_INVOKER VARCHAR(200) NOT NULL    COMMENT '任务执行函数',
  DESCRIPTION VARCHAR(4000)     COMMENT '任务描述',
  STATUS INTEGER NOT NULL    COMMENT '任务状态',
  CRON_EXPR VARCHAR(100)     COMMENT '定时表达式',
  REPEAT_INTERVAL INTEGER     COMMENT '定时执行间隔',
  IS_FIXED_DELAY TINYINT     COMMENT '是否固定延时',
  MAX_EXECUTION_COUNT INTEGER     COMMENT '最多执行次数',
  MIN_SCHEDULE_TIME TIMESTAMP     COMMENT '最近调度时间',
  MAX_SCHEDULE_TIME TIMESTAMP     COMMENT '最大调度时间',
  MISFIRE_THRESHOLD INTEGER     COMMENT '超时阈值',
  MAX_FAILED_COUNT INTEGER     COMMENT '最大允许失败次数',
  IS_USE_DEFAULT_CALENDAR TINYINT     COMMENT '使用系统内置日历',
  PAUSE_CALENDARS VARCHAR(4000)     COMMENT '暂停日历',
  VERSION BIGINT NOT NULL    COMMENT '数据版本',
  CREATED_BY VARCHAR(50) NOT NULL    COMMENT '创建人',
  CREATE_TIME TIMESTAMP NOT NULL    COMMENT '创建时间',
  UPDATED_BY VARCHAR(50) NOT NULL    COMMENT '修改人',
  UPDATE_TIME TIMESTAMP NOT NULL    COMMENT '修改时间',
  REMARK VARCHAR(200)     COMMENT '备注',
  constraint PK_nop_job_plan primary key (SID)
);


   ALTER TABLE nop_job_plan COMMENT '任务调度计划';
                
