
CREATE TABLE nop_ai_project(
  ID VARCHAR(36) NOT NULL    COMMENT '主键',
  LANGUAGE VARCHAR(4) NOT NULL    COMMENT '项目语言',
  NAME VARCHAR(100) NOT NULL    COMMENT '项目名称',
  PROTOTYPE_ID VARCHAR(36) NULL    COMMENT '模板项目ID',
  PROJECT_DIR VARCHAR(400) NULL    COMMENT '项目目录',
  RUNTIME_METADATA LONGTEXT NULL    COMMENT '运行时元数据',
  VERSION INTEGER NOT NULL    COMMENT '数据版本',
  CREATED_BY VARCHAR(50) NOT NULL    COMMENT '创建人',
  CREATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '创建时间',
  UPDATED_BY VARCHAR(50) NOT NULL    COMMENT '修改人',
  UPDATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '修改时间',
  constraint PK_nop_ai_project primary key (ID)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs;

CREATE TABLE nop_ai_knowledge(
  ID VARCHAR(36) NOT NULL    COMMENT '主键',
  TITLE VARCHAR(200) NOT NULL    COMMENT '标题',
  CONTENT VARCHAR(4000) NULL    COMMENT '内容',
  FORMAT VARCHAR(4) NOT NULL    COMMENT '格式类型',
  VERSION INTEGER NOT NULL    COMMENT '数据版本',
  CREATED_BY VARCHAR(50) NOT NULL    COMMENT '创建人',
  CREATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '创建时间',
  UPDATED_BY VARCHAR(50) NOT NULL    COMMENT '修改人',
  UPDATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '修改时间',
  constraint PK_nop_ai_knowledge primary key (ID)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs;

CREATE TABLE nop_ai_model(
  ID VARCHAR(36) NOT NULL    COMMENT '主键',
  PROVIDER VARCHAR(4) NOT NULL    COMMENT '供应商',
  MODEL_NAME VARCHAR(50) NOT NULL    COMMENT '模型名称',
  BASE_URL VARCHAR(200) NULL    COMMENT 'API地址',
  API_KEY VARCHAR(100) NULL    COMMENT 'API密钥',
  VERSION INTEGER NOT NULL    COMMENT '数据版本',
  CREATED_BY VARCHAR(50) NOT NULL    COMMENT '创建人',
  CREATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '创建时间',
  UPDATED_BY VARCHAR(50) NOT NULL    COMMENT '修改人',
  UPDATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '修改时间',
  INPUT_PRICE_PER_1M DECIMAL(10,4) NULL    COMMENT '输入单价',
  OUTPUT_PRICE_PER_1M DECIMAL(10,4) NULL    COMMENT '输出单价',
  REASONING_PRICE_PER_1M DECIMAL(10,4) NULL    COMMENT '推理单价',
  CACHE_READ_PRICE_PER_1M DECIMAL(10,4) NULL    COMMENT '缓存读单价',
  CACHE_WRITE_PRICE_PER_1M DECIMAL(10,4) NULL    COMMENT '缓存写单价',
  CURRENCY VARCHAR(3) NULL    COMMENT '币种',
  constraint PK_nop_ai_model primary key (ID)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs;

CREATE TABLE nop_ai_prompt_template(
  ID VARCHAR(36) NOT NULL    COMMENT '主键',
  NAME VARCHAR(100) NOT NULL    COMMENT '模板名称',
  CONTENT VARCHAR(4000) NOT NULL    COMMENT '模板内容',
  CATEGORY VARCHAR(50) NULL    COMMENT '分类',
  INPUTS VARCHAR(1000) NULL    COMMENT '输入规范',
  OUTPUTS VARCHAR(1000) NULL    COMMENT '输出规范',
  VERSION INTEGER NOT NULL    COMMENT '数据版本',
  CREATED_BY VARCHAR(50) NOT NULL    COMMENT '创建人',
  CREATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '创建时间',
  UPDATED_BY VARCHAR(50) NOT NULL    COMMENT '修改人',
  UPDATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '修改时间',
  constraint PK_nop_ai_prompt_template primary key (ID)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs;

CREATE TABLE nop_ai_project_config(
  ID VARCHAR(36) NOT NULL    COMMENT '主键',
  PROJECT_ID VARCHAR(36) NOT NULL    COMMENT '项目ID',
  CONFIG_NAME VARCHAR(50) NOT NULL    COMMENT '配置名称',
  CONFIG_VALUE VARCHAR(200) NOT NULL    COMMENT '配置值',
  CONFIG_TYPE VARCHAR(4) NOT NULL    COMMENT '配置类型',
  VERSION INTEGER NOT NULL    COMMENT '数据版本',
  CREATED_BY VARCHAR(50) NOT NULL    COMMENT '创建人',
  CREATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '创建时间',
  UPDATED_BY VARCHAR(50) NOT NULL    COMMENT '修改人',
  UPDATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '修改时间',
  constraint PK_nop_ai_project_config primary key (ID)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs;

CREATE TABLE nop_ai_requirement(
  ID VARCHAR(36) NOT NULL    COMMENT '主键',
  PROJECT_ID VARCHAR(36) NOT NULL    COMMENT '项目ID',
  REQ_NUMBER VARCHAR(20) NOT NULL    COMMENT '需求编号',
  TITLE VARCHAR(200) NOT NULL    COMMENT '需求标题',
  CONTENT VARCHAR(4000) NULL    COMMENT '需求内容',
  VERSION LONGTEXT NOT NULL    COMMENT '当前版本',
  PARENT_ID VARCHAR(36) NULL    COMMENT '父需求ID',
  TYPE VARCHAR(4) NOT NULL    COMMENT '需求类型',
  AI_SUMMARY VARCHAR(1000) NULL    COMMENT 'AI摘要',
  STATUS VARCHAR(4) NOT NULL    COMMENT '状态',
  CREATED_BY VARCHAR(50) NOT NULL    COMMENT '创建人',
  CREATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '创建时间',
  UPDATED_BY VARCHAR(50) NOT NULL    COMMENT '修改人',
  UPDATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '修改时间',
  constraint PK_nop_ai_requirement primary key (ID)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs;

CREATE TABLE nop_ai_session(
  ID VARCHAR(36) NOT NULL    COMMENT '主键',
  PROJECT_ID VARCHAR(36) NOT NULL    COMMENT '项目ID',
  PARENT_SESSION_ID VARCHAR(36) NULL    COMMENT '父会话ID',
  AGENT_NAME VARCHAR(100) NOT NULL    COMMENT 'Agent名称',
  MODEL_PROVIDER VARCHAR(4) NULL    COMMENT '模型供应商',
  MODEL_NAME VARCHAR(50) NULL    COMMENT '模型名称',
  SLUG VARCHAR(100) NULL    COMMENT '会话Slug',
  TITLE VARCHAR(200) NULL    COMMENT '会话标题',
  DIRECTORY VARCHAR(400) NULL    COMMENT '工作目录',
  STATUS INTEGER NOT NULL    COMMENT '会话状态',
  VERSION INTEGER NOT NULL    COMMENT '数据版本',
  COST DECIMAL(10,6) NULL    COMMENT '费用',
  TOKENS_INPUT INTEGER NULL    COMMENT '输入Token数',
  TOKENS_OUTPUT INTEGER NULL    COMMENT '输出Token数',
  TOKENS_REASONING INTEGER NULL    COMMENT '推理Token数',
  TOKENS_CACHE_READ INTEGER NULL    COMMENT '缓存读取Token数',
  TOKENS_CACHE_WRITE INTEGER NULL    COMMENT '缓存写入Token数',
  TOTAL_BYTES BIGINT NULL    COMMENT '总字节数',
  CONTEXT_METADATA LONGTEXT NULL    COMMENT '上下文元数据',
  METADATA LONGTEXT NULL    COMMENT '元数据',
  CREATED_BY VARCHAR(50) NOT NULL    COMMENT '创建人',
  CREATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '创建时间',
  UPDATED_BY VARCHAR(50) NOT NULL    COMMENT '修改人',
  UPDATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '修改时间',
  COMPACTED_AT DATETIME(3) NULL    COMMENT '压缩时间',
  ARCHIVED_AT DATETIME(3) NULL    COMMENT '归档时间',
  constraint PK_nop_ai_session primary key (ID)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs;

CREATE TABLE nop_ai_project_rule(
  ID VARCHAR(36) NOT NULL    COMMENT '主键',
  PROJECT_ID VARCHAR(36) NOT NULL    COMMENT '项目ID',
  KNOWLEDGE_ID VARCHAR(36) NULL    COMMENT '知识库ID',
  RULE_NAME VARCHAR(100) NOT NULL    COMMENT '规则名称',
  RULE_CONTENT VARCHAR(4000) NOT NULL    COMMENT '规则内容',
  RULE_TYPE VARCHAR(4) NULL    COMMENT '规则类型',
  IS_ACTIVE BOOLEAN NOT NULL    COMMENT '是否启用',
  VERSION INTEGER NOT NULL    COMMENT '数据版本',
  CREATED_BY VARCHAR(50) NOT NULL    COMMENT '创建人',
  CREATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '创建时间',
  UPDATED_BY VARCHAR(50) NOT NULL    COMMENT '修改人',
  UPDATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '修改时间',
  constraint PK_nop_ai_project_rule primary key (ID)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs;

CREATE TABLE nop_ai_prompt_template_history(
  ID VARCHAR(36) NOT NULL    COMMENT '主键',
  TEMPLATE_ID VARCHAR(36) NOT NULL    COMMENT '模板ID',
  VERSION VARCHAR(10) NOT NULL    COMMENT '版本号',
  CONTENT VARCHAR(4000) NOT NULL    COMMENT '模板内容',
  CREATED_BY VARCHAR(50) NOT NULL    COMMENT '创建人',
  CREATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '创建时间',
  UPDATED_BY VARCHAR(50) NOT NULL    COMMENT '修改人',
  UPDATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '修改时间',
  constraint PK_nop_ai_prompt_template_history primary key (ID)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs;

CREATE TABLE nop_ai_chat_request(
  ID VARCHAR(36) NOT NULL    COMMENT '主键',
  TEMPLATE_ID VARCHAR(36) NULL    COMMENT '模板ID',
  SESSION_ID VARCHAR(36) NOT NULL    COMMENT '会话ID',
  SYSTEM_PROMPT MEDIUMTEXT NULL    COMMENT '系统提示词',
  USER_PROMPT MEDIUMTEXT NOT NULL    COMMENT '用户提示词',
  MESSAGE_TYPE INTEGER NOT NULL    COMMENT '消息类型',
  REQUEST_TIMESTAMP DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '请求时间戳',
  HASH VARCHAR(64) NOT NULL    COMMENT '内容哈希',
  METADATA VARCHAR(2000) NULL    COMMENT '元数据',
  VERSION INTEGER NOT NULL    COMMENT '数据版本',
  CREATED_BY VARCHAR(50) NOT NULL    COMMENT '创建人',
  CREATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '创建时间',
  UPDATED_BY VARCHAR(50) NOT NULL    COMMENT '修改人',
  UPDATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '修改时间',
  constraint PK_nop_ai_chat_request primary key (ID)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs;

CREATE TABLE nop_ai_requirement_history(
  ID VARCHAR(36) NOT NULL    COMMENT '主键',
  REQUIREMENT_ID VARCHAR(36) NOT NULL    COMMENT '需求ID',
  VERSION VARCHAR(10) NOT NULL    COMMENT '版本号',
  CONTENT VARCHAR(4000) NOT NULL    COMMENT '需求内容',
  CREATED_BY VARCHAR(50) NOT NULL    COMMENT '创建人',
  CREATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '创建时间',
  UPDATED_BY VARCHAR(50) NOT NULL    COMMENT '修改人',
  UPDATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '修改时间',
  constraint PK_nop_ai_requirement_history primary key (ID)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs;

CREATE TABLE nop_ai_session_message(
  ID VARCHAR(36) NOT NULL    COMMENT '主键',
  SESSION_ID VARCHAR(36) NOT NULL    COMMENT '会话ID',
  ROLE INTEGER NOT NULL    COMMENT '消息角色',
  SEQ BIGINT NOT NULL    COMMENT '序号',
  CONTENT LONGTEXT NULL    COMMENT '消息内容',
  TOOL_DETAILS LONGTEXT NULL    COMMENT '工具详情',
  REASONING LONGTEXT NULL    COMMENT '推理内容',
  METADATA LONGTEXT NULL    COMMENT '元数据',
  PARENT_ID VARCHAR(36) NULL    COMMENT '父消息ID',
  FINISH_REASON VARCHAR(20) NULL    COMMENT '停止原因',
  VERSION INTEGER NOT NULL    COMMENT '数据版本',
  CREATED_BY VARCHAR(50) NOT NULL    COMMENT '创建人',
  CREATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '创建时间',
  UPDATED_BY VARCHAR(50) NOT NULL    COMMENT '修改人',
  UPDATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '修改时间',
  constraint PK_nop_ai_session_message primary key (ID)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs;

CREATE TABLE nop_ai_session_input(
  ID VARCHAR(36) NOT NULL    COMMENT '主键',
  SESSION_ID VARCHAR(36) NOT NULL    COMMENT '会话ID',
  PROMPT LONGTEXT NULL    COMMENT '输入提示',
  DELIVERY INTEGER NOT NULL    COMMENT '投递方式',
  ADMITTED_SEQ BIGINT NULL    COMMENT '接纳序号',
  PROMOTED_SEQ BIGINT NULL    COMMENT '提升序号',
  VERSION INTEGER NOT NULL    COMMENT '数据版本',
  CREATED_BY VARCHAR(50) NOT NULL    COMMENT '创建人',
  CREATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '创建时间',
  UPDATED_BY VARCHAR(50) NOT NULL    COMMENT '修改人',
  UPDATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '修改时间',
  constraint PK_nop_ai_session_input primary key (ID)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs;

CREATE TABLE nop_ai_session_context(
  ID VARCHAR(36) NOT NULL    COMMENT '主键',
  SESSION_ID VARCHAR(36) NOT NULL    COMMENT '会话ID',
  BASELINE LONGTEXT NULL    COMMENT '基线内容',
  SNAPSHOT LONGTEXT NULL    COMMENT '上下文快照',
  BASELINE_SEQ BIGINT NULL    COMMENT '基线序号',
  REPLACEMENT_SEQ BIGINT NULL    COMMENT '替换序号',
  REVISION INTEGER NOT NULL    COMMENT '版本',
  CREATED_BY VARCHAR(50) NOT NULL    COMMENT '创建人',
  CREATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '创建时间',
  UPDATED_BY VARCHAR(50) NOT NULL    COMMENT '修改人',
  UPDATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '修改时间',
  constraint PK_nop_ai_session_context primary key (ID)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs;

CREATE TABLE nop_ai_todo(
  ID VARCHAR(36) NOT NULL    COMMENT '主键',
  SESSION_ID VARCHAR(36) NOT NULL    COMMENT '会话ID',
  PLAN_ID VARCHAR(36) NULL    COMMENT '计划ID',
  CONTENT VARCHAR(1000) NOT NULL    COMMENT '待办内容',
  STATUS INTEGER NOT NULL    COMMENT '状态',
  PRIORITY INTEGER NOT NULL    COMMENT '优先级',
  POSITION INTEGER NOT NULL    COMMENT '位置',
  DEPENDS_ON LONGTEXT NULL    COMMENT '依赖项',
  VERSION INTEGER NOT NULL    COMMENT '数据版本',
  CREATED_BY VARCHAR(50) NOT NULL    COMMENT '创建人',
  CREATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '创建时间',
  UPDATED_BY VARCHAR(50) NOT NULL    COMMENT '修改人',
  UPDATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '修改时间',
  constraint PK_nop_ai_todo primary key (ID)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs;

CREATE TABLE nop_ai_event(
  ID VARCHAR(36) NOT NULL    COMMENT '主键',
  SESSION_ID VARCHAR(36) NOT NULL    COMMENT '会话ID',
  SEQ BIGINT NOT NULL    COMMENT '序号',
  EVENT_TYPE INTEGER NOT NULL    COMMENT '事件类型',
  DATA LONGTEXT NULL    COMMENT '事件数据',
  CREATED_BY VARCHAR(50) NOT NULL    COMMENT '创建人',
  CREATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '创建时间',
  constraint PK_nop_ai_event primary key (ID)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs;

CREATE TABLE nop_ai_chat_response(
  ID VARCHAR(36) NOT NULL    COMMENT '主键',
  REQUEST_ID VARCHAR(36) NOT NULL    COMMENT '请求ID',
  SESSION_ID VARCHAR(36) NOT NULL    COMMENT '会话ID',
  MODEL_ID VARCHAR(36) NOT NULL    COMMENT '模型ID',
  AI_PROVIDER VARCHAR(4) NOT NULL    COMMENT '供应商',
  AI_MODEL VARCHAR(50) NOT NULL    COMMENT '模型名称',
  RESPONSE_CONTENT MEDIUMTEXT NOT NULL    COMMENT '响应内容',
  RESPONSE_TIMESTAMP DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '响应时间戳',
  PROMPT_TOKENS INTEGER NULL    COMMENT '请求Token数',
  COMPLETION_TOKENS INTEGER NULL    COMMENT '响应Token数',
  RESPONSE_DURATION_MS INTEGER NULL    COMMENT '响应耗时(毫秒)',
  CORRECTNESS_SCORE DECIMAL(5,2) NULL    COMMENT '正确性分',
  PERFORMANCE_SCORE DECIMAL(5,2) NULL    COMMENT '性能分',
  READABILITY_SCORE DECIMAL(5,2) NULL    COMMENT '可读性分',
  COMPLIANCE_SCORE DECIMAL(5,2) NULL    COMMENT '合规性分',
  VERSION INTEGER NOT NULL    COMMENT '数据版本',
  CREATED_BY VARCHAR(50) NOT NULL    COMMENT '创建人',
  CREATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '创建时间',
  UPDATED_BY VARCHAR(50) NOT NULL    COMMENT '修改人',
  UPDATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '修改时间',
  constraint PK_nop_ai_chat_response primary key (ID)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs;

CREATE TABLE nop_ai_gen_file(
  ID VARCHAR(36) NOT NULL    COMMENT '主键',
  PROJECT_ID VARCHAR(36) NOT NULL    COMMENT '项目ID',
  REQUIREMENT_ID VARCHAR(36) NULL    COMMENT '需求ID',
  MODULE_TYPE VARCHAR(4) NOT NULL    COMMENT '模块类型',
  CONTENT MEDIUMTEXT NOT NULL    COMMENT '文件内容',
  FILE_PATH VARCHAR(200) NOT NULL    COMMENT '文件路径',
  CHAT_RESPONSE_ID VARCHAR(36) NULL    COMMENT '响应ID',
  STATUS VARCHAR(4) NOT NULL    COMMENT '状态',
  VERSION INTEGER NOT NULL    COMMENT '数据版本',
  CREATED_BY VARCHAR(50) NOT NULL    COMMENT '创建人',
  CREATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '创建时间',
  UPDATED_BY VARCHAR(50) NOT NULL    COMMENT '修改人',
  UPDATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '修改时间',
  constraint PK_nop_ai_gen_file primary key (ID)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs;

CREATE TABLE nop_ai_gen_file_history(
  ID VARCHAR(36) NOT NULL    COMMENT '主键',
  GEN_FILE_ID VARCHAR(36) NOT NULL    COMMENT '文件ID',
  VERSION VARCHAR(10) NOT NULL    COMMENT '版本号',
  CONTENT MEDIUMTEXT NOT NULL    COMMENT '文件内容',
  CREATED_BY VARCHAR(50) NOT NULL    COMMENT '创建人',
  CREATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '创建时间',
  UPDATED_BY VARCHAR(50) NOT NULL    COMMENT '修改人',
  UPDATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '修改时间',
  constraint PK_nop_ai_gen_file_history primary key (ID)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs;

CREATE TABLE nop_ai_test_case(
  ID VARCHAR(36) NOT NULL    COMMENT '主键',
  REQUIREMENT_ID VARCHAR(36) NOT NULL    COMMENT '需求ID',
  TEST_CONTENT VARCHAR(2000) NOT NULL    COMMENT '测试内容',
  TEST_DATA VARCHAR(1000) NULL    COMMENT '测试数据',
  GEN_FILE_ID VARCHAR(36) NULL    COMMENT '关联文件ID',
  CHAT_RESPONSE_ID VARCHAR(36) NULL    COMMENT '响应ID',
  STATUS VARCHAR(4) NOT NULL    COMMENT '状态',
  VERSION INTEGER NOT NULL    COMMENT '数据版本',
  CREATED_BY VARCHAR(50) NOT NULL    COMMENT '创建人',
  CREATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '创建时间',
  UPDATED_BY VARCHAR(50) NOT NULL    COMMENT '修改人',
  UPDATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '修改时间',
  constraint PK_nop_ai_test_case primary key (ID)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs;

CREATE TABLE nop_ai_test_result(
  ID VARCHAR(36) NOT NULL    COMMENT '主键',
  TEST_CASE_ID VARCHAR(36) NOT NULL    COMMENT '测试用例ID',
  EXECUTION_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '执行时间',
  SUCCESS BOOLEAN NOT NULL    COMMENT '是否成功',
  ERROR_LOG VARCHAR(2000) NULL    COMMENT '错误日志',
  VERSION INTEGER NOT NULL    COMMENT '数据版本',
  CREATED_BY VARCHAR(50) NOT NULL    COMMENT '创建人',
  CREATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '创建时间',
  UPDATED_BY VARCHAR(50) NOT NULL    COMMENT '修改人',
  UPDATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '修改时间',
  constraint PK_nop_ai_test_result primary key (ID)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs;


   ALTER TABLE nop_ai_project COMMENT 'AI项目';
                
   ALTER TABLE nop_ai_knowledge COMMENT '知识库';
                
   ALTER TABLE nop_ai_model COMMENT 'AI模型';
                
   ALTER TABLE nop_ai_prompt_template COMMENT '提示词模板';
                
   ALTER TABLE nop_ai_project_config COMMENT '项目配置';
                
   ALTER TABLE nop_ai_requirement COMMENT '需求条目';
                
   ALTER TABLE nop_ai_session COMMENT 'Agent会话';
                
   ALTER TABLE nop_ai_project_rule COMMENT '项目规则';
                
   ALTER TABLE nop_ai_prompt_template_history COMMENT '模板历史';
                
   ALTER TABLE nop_ai_chat_request COMMENT '对话请求';
                
   ALTER TABLE nop_ai_requirement_history COMMENT '需求历史';
                
   ALTER TABLE nop_ai_session_message COMMENT '会话消息';
                
   ALTER TABLE nop_ai_session_input COMMENT '会话输入';
                
   ALTER TABLE nop_ai_session_context COMMENT '上下文快照';
                
   ALTER TABLE nop_ai_todo COMMENT 'Agent待办';
                
   ALTER TABLE nop_ai_event COMMENT 'Agent事件';
                
   ALTER TABLE nop_ai_chat_response COMMENT '响应结果';
                
   ALTER TABLE nop_ai_gen_file COMMENT '生成文件';
                
   ALTER TABLE nop_ai_gen_file_history COMMENT '文件历史';
                
   ALTER TABLE nop_ai_test_case COMMENT '测试用例';
                
   ALTER TABLE nop_ai_test_result COMMENT '测试结果';
                
