// Generated by scripts/build-nop-shared.mjs — host shared module facade.
// Re-exports the host instance registered at bootstrap on
// `window.__NOP_SHARED__`; only loaded by extensions (after registration).
import { getSharedModule } from './_registry.js';

const moduleRef = getSharedModule("amis-formula");

export default moduleRef.default ?? moduleRef;
export const AsyncEvaluator = moduleRef["AsyncEvaluator"];
export const Evaluator = moduleRef["Evaluator"];
export const evaluate = moduleRef["evaluate"];
export const evaluateForAsync = moduleRef["evaluateForAsync"];
export const extendsFilters = moduleRef["extendsFilters"];
export const filters = moduleRef["filters"];
export const getFilters = moduleRef["getFilters"];
export const getFunctionsDoc = moduleRef["getFunctionsDoc"];
export const lexer = moduleRef["lexer"];
export const parse = moduleRef["parse"];
export const registerFilter = moduleRef["registerFilter"];
export const registerFormula = moduleRef["registerFormula"];
export const registerFunction = moduleRef["registerFunction"];
export const registerFunctionDoc = moduleRef["registerFunctionDoc"];
