// Generated by scripts/build-nop-shared.mjs — host shared module facade.
// Re-exports the host instance registered at bootstrap on
// `window.__NOP_SHARED__`; only loaded by extensions (after registration).
import { getSharedModule } from './_registry.js';

const moduleRef = getSharedModule("@nop-chaos/flux");

export default moduleRef.default ?? moduleRef;
export const FLUX_ROOT_CLASS = moduleRef["FLUX_ROOT_CLASS"];
export const createDefaultFluxEnv = moduleRef["createDefaultFluxEnv"];
export const createFluxRendererRegistry = moduleRef["createFluxRendererRegistry"];
export const createFluxSchemaRenderer = moduleRef["createFluxSchemaRenderer"];
export const createFluxSchemaRendererWithRegistry = moduleRef["createFluxSchemaRendererWithRegistry"];
export const registerDefaultFluxRenderers = moduleRef["registerDefaultFluxRenderers"];
