// Generated by scripts/build-nop-shared.mjs — host shared module facade.
// Re-exports the host instance registered at bootstrap on
// `window.__NOP_SHARED__`; only loaded by extensions (after registration).
import { getSharedModule } from './_registry.js';

const moduleRef = getSharedModule("i18next");

export default moduleRef.default ?? moduleRef;
export const observers = moduleRef["observers"];
export const options = moduleRef["options"];
export const services = moduleRef["services"];
export const logger = moduleRef["logger"];
export const modules = moduleRef["modules"];
export const constructor = moduleRef["constructor"];
export const init = moduleRef["init"];
export const loadResources = moduleRef["loadResources"];
export const reloadResources = moduleRef["reloadResources"];
export const use = moduleRef["use"];
export const setResolvedLanguage = moduleRef["setResolvedLanguage"];
export const changeLanguage = moduleRef["changeLanguage"];
export const getFixedT = moduleRef["getFixedT"];
export const t = moduleRef["t"];
export const exists = moduleRef["exists"];
export const setDefaultNamespace = moduleRef["setDefaultNamespace"];
export const hasLoadedNamespace = moduleRef["hasLoadedNamespace"];
export const loadNamespaces = moduleRef["loadNamespaces"];
export const loadLanguages = moduleRef["loadLanguages"];
export const dir = moduleRef["dir"];
export const cloneInstance = moduleRef["cloneInstance"];
export const toJSON = moduleRef["toJSON"];
export const createInstance = moduleRef["createInstance"];
export const keyFromSelector = moduleRef["keyFromSelector"];
