// Generated by scripts/build-nop-shared.mjs — host shared module facade.
// Re-exports the host instance registered at bootstrap on
// `window.__NOP_SHARED__`; only loaded by extensions (after registration).
import { getSharedModule } from './_registry.js';

const moduleRef = getSharedModule("@nop-chaos/plugin-bridge");

export default moduleRef.default ?? moduleRef;
export const getPluginBridge = moduleRef["getPluginBridge"];
export const getPluginBridgeSnapshot = moduleRef["getPluginBridgeSnapshot"];
export const subscribePluginBridge = moduleRef["subscribePluginBridge"];
export const usePluginBridge = moduleRef["usePluginBridge"];
export const usePluginBridgeSnapshot = moduleRef["usePluginBridgeSnapshot"];
export const usePluginI18n = moduleRef["usePluginI18n"];
export const usePluginManifest = moduleRef["usePluginManifest"];
export const usePluginNotifications = moduleRef["usePluginNotifications"];
export const usePluginThemeConfig = moduleRef["usePluginThemeConfig"];
export const usePluginUser = moduleRef["usePluginUser"];
