// Generated by scripts/build-nop-shared.mjs — host shared module facade.
// Re-exports the host instance registered at bootstrap on
// `window.__NOP_SHARED__`; only loaded by extensions (after registration).
import { getSharedModule } from './_registry.js';

const moduleRef = getSharedModule("react-dom");

export default moduleRef.default ?? moduleRef;
export const __DOM_INTERNALS_DO_NOT_USE_OR_WARN_USERS_THEY_CANNOT_UPGRADE = moduleRef["__DOM_INTERNALS_DO_NOT_USE_OR_WARN_USERS_THEY_CANNOT_UPGRADE"];
export const createPortal = moduleRef["createPortal"];
export const flushSync = moduleRef["flushSync"];
export const preconnect = moduleRef["preconnect"];
export const prefetchDNS = moduleRef["prefetchDNS"];
export const preinit = moduleRef["preinit"];
export const preinitModule = moduleRef["preinitModule"];
export const preload = moduleRef["preload"];
export const preloadModule = moduleRef["preloadModule"];
export const requestFormReset = moduleRef["requestFormReset"];
export const unstable_batchedUpdates = moduleRef["unstable_batchedUpdates"];
export const useFormState = moduleRef["useFormState"];
export const useFormStatus = moduleRef["useFormStatus"];
export const version = moduleRef["version"];
