// Generated by scripts/build-nop-shared.mjs — host shared module facade.
// Re-exports the host instance registered at bootstrap on
// `window.__NOP_SHARED__`; only loaded by extensions (after registration).
import { getSharedModule } from './_registry.js';

const moduleRef = getSharedModule("react");

export default moduleRef.default ?? moduleRef;
export const Activity = moduleRef["Activity"];
export const Children = moduleRef["Children"];
export const Component = moduleRef["Component"];
export const Fragment = moduleRef["Fragment"];
export const Profiler = moduleRef["Profiler"];
export const PureComponent = moduleRef["PureComponent"];
export const StrictMode = moduleRef["StrictMode"];
export const Suspense = moduleRef["Suspense"];
export const __CLIENT_INTERNALS_DO_NOT_USE_OR_WARN_USERS_THEY_CANNOT_UPGRADE = moduleRef["__CLIENT_INTERNALS_DO_NOT_USE_OR_WARN_USERS_THEY_CANNOT_UPGRADE"];
export const __COMPILER_RUNTIME = moduleRef["__COMPILER_RUNTIME"];
export const act = moduleRef["act"];
export const cache = moduleRef["cache"];
export const cacheSignal = moduleRef["cacheSignal"];
export const captureOwnerStack = moduleRef["captureOwnerStack"];
export const cloneElement = moduleRef["cloneElement"];
export const createContext = moduleRef["createContext"];
export const createElement = moduleRef["createElement"];
export const createRef = moduleRef["createRef"];
export const forwardRef = moduleRef["forwardRef"];
export const isValidElement = moduleRef["isValidElement"];
export const lazy = moduleRef["lazy"];
export const memo = moduleRef["memo"];
export const startTransition = moduleRef["startTransition"];
export const unstable_useCacheRefresh = moduleRef["unstable_useCacheRefresh"];
export const use = moduleRef["use"];
export const useActionState = moduleRef["useActionState"];
export const useCallback = moduleRef["useCallback"];
export const useContext = moduleRef["useContext"];
export const useDebugValue = moduleRef["useDebugValue"];
export const useDeferredValue = moduleRef["useDeferredValue"];
export const useEffect = moduleRef["useEffect"];
export const useEffectEvent = moduleRef["useEffectEvent"];
export const useId = moduleRef["useId"];
export const useImperativeHandle = moduleRef["useImperativeHandle"];
export const useInsertionEffect = moduleRef["useInsertionEffect"];
export const useLayoutEffect = moduleRef["useLayoutEffect"];
export const useMemo = moduleRef["useMemo"];
export const useOptimistic = moduleRef["useOptimistic"];
export const useReducer = moduleRef["useReducer"];
export const useRef = moduleRef["useRef"];
export const useState = moduleRef["useState"];
export const useSyncExternalStore = moduleRef["useSyncExternalStore"];
export const useTransition = moduleRef["useTransition"];
export const version = moduleRef["version"];
