// Generated by scripts/build-nop-shared.mjs — host shared module facade.
// Re-exports the host instance registered at bootstrap on
// `window.__NOP_SHARED__`; only loaded by extensions (after registration).
import { getSharedModule } from './_registry.js';

const moduleRef = getSharedModule("react-i18next");

export default moduleRef.default ?? moduleRef;
export const I18nContext = moduleRef["I18nContext"];
export const I18nextProvider = moduleRef["I18nextProvider"];
export const IcuTrans = moduleRef["IcuTrans"];
export const IcuTransWithoutContext = moduleRef["IcuTransWithoutContext"];
export const Trans = moduleRef["Trans"];
export const TransWithoutContext = moduleRef["TransWithoutContext"];
export const Translation = moduleRef["Translation"];
export const composeInitialProps = moduleRef["composeInitialProps"];
export const date = moduleRef["date"];
export const getDefaults = moduleRef["getDefaults"];
export const getI18n = moduleRef["getI18n"];
export const getInitialProps = moduleRef["getInitialProps"];
export const initReactI18next = moduleRef["initReactI18next"];
export const nodesToString = moduleRef["nodesToString"];
export const number = moduleRef["number"];
export const plural = moduleRef["plural"];
export const select = moduleRef["select"];
export const selectOrdinal = moduleRef["selectOrdinal"];
export const setDefaults = moduleRef["setDefaults"];
export const setI18n = moduleRef["setI18n"];
export const time = moduleRef["time"];
export const useSSR = moduleRef["useSSR"];
export const useTranslation = moduleRef["useTranslation"];
export const withSSR = moduleRef["withSSR"];
export const withTranslation = moduleRef["withTranslation"];
