import { getSharedModule } from './_registry.js';

const shared = getSharedModule('@nop-chaos/shared');

export const appIconNames = shared.appIconNames;
export const appendQueryParams = shared.appendQueryParams;
export const clearTokens = shared.clearTokens;
export const collectBreadcrumbTrail = shared.collectBreadcrumbTrail;
export const createHttpClient = shared.createHttpClient;
export const createTokenStorage = shared.createTokenStorage;
export const decodeJwtPayload = shared.decodeJwtPayload;
export const filterMenusByRoles = shared.filterMenusByRoles;
export const findMenuItemByPath = shared.findMenuItemByPath;
export const flattenMenus = shared.flattenMenus;
export const getAccessToken = shared.getAccessToken;
export const getAuthConfig = shared.getAuthConfig;
export const getRefreshToken = shared.getRefreshToken;
export const getTokenExpiry = shared.getTokenExpiry;
export const getTokenStorage = shared.getTokenStorage;
export const getValidToken = shared.getValidToken;
export const isAbsoluteUrl = shared.isAbsoluteUrl;
export const isApiPayload = shared.isApiPayload;
export const isAppIconName = shared.isAppIconName;
export const isTokenExpired = shared.isTokenExpired;
export const isTokenExpiringSoon = shared.isTokenExpiringSoon;
export const matchMenuPath = shared.matchMenuPath;
export const normalizeAppIconName = shared.normalizeAppIconName;
export const normalizeRequestUrl = shared.normalizeRequestUrl;
export const refreshAccessToken = shared.refreshAccessToken;
export const resetAuthConfig = shared.resetAuthConfig;
export const resetTokenStorage = shared.resetTokenStorage;
export const resolveRequestUrl = shared.resolveRequestUrl;
export const setAuthConfig = shared.setAuthConfig;
export const setRefreshTokenFetcher = shared.setRefreshTokenFetcher;
export const setTokens = shared.setTokens;
export const sortMenus = shared.sortMenus;
export const unwrapApiPayload = shared.unwrapApiPayload;
export const validateMenuResponse = shared.validateMenuResponse;
