// Generated by scripts/build-nop-shared.mjs — host shared module facade.
// Re-exports the host instance registered at bootstrap on
// `window.__NOP_SHARED__`; only loaded by extensions (after registration).
import { getSharedModule } from './_registry.js';

const moduleRef = getSharedModule("@nop-chaos/shared");

export default moduleRef.default ?? moduleRef;
export const HOST_API_VERSION = moduleRef["HOST_API_VERSION"];
export const SHARED_MODULE_NAMES = moduleRef["SHARED_MODULE_NAMES"];
export const appIconNames = moduleRef["appIconNames"];
export const clearTokens = moduleRef["clearTokens"];
export const collectBreadcrumbTrail = moduleRef["collectBreadcrumbTrail"];
export const compareApiVersions = moduleRef["compareApiVersions"];
export const createHttpClient = moduleRef["createHttpClient"];
export const filterMenusByRoles = moduleRef["filterMenusByRoles"];
export const findMenuItemByPath = moduleRef["findMenuItemByPath"];
export const flattenMenus = moduleRef["flattenMenus"];
export const getAccessToken = moduleRef["getAccessToken"];
export const getAuthConfig = moduleRef["getAuthConfig"];
export const getBaseOrigin = moduleRef["getBaseOrigin"];
export const getRefreshToken = moduleRef["getRefreshToken"];
export const getValidToken = moduleRef["getValidToken"];
export const isAbsoluteUrl = moduleRef["isAbsoluteUrl"];
export const isApiPayload = moduleRef["isApiPayload"];
export const isApiVersion = moduleRef["isApiVersion"];
export const isAppIconName = moduleRef["isAppIconName"];
export const isRelativeOrRootPath = moduleRef["isRelativeOrRootPath"];
export const matchMenuPath = moduleRef["matchMenuPath"];
export const normalizeAppIconName = moduleRef["normalizeAppIconName"];
export const normalizeThemeId = moduleRef["normalizeThemeId"];
export const resetAuthConfig = moduleRef["resetAuthConfig"];
export const resetTokenStorage = moduleRef["resetTokenStorage"];
export const resolveSameOriginPath = moduleRef["resolveSameOriginPath"];
export const satisfiesMinApiVersion = moduleRef["satisfiesMinApiVersion"];
export const setAuthConfig = moduleRef["setAuthConfig"];
export const setRefreshTokenFetcher = moduleRef["setRefreshTokenFetcher"];
export const setTokens = moduleRef["setTokens"];
export const sortMenus = moduleRef["sortMenus"];
export const unwrapApiPayload = moduleRef["unwrapApiPayload"];
export const validateMenuResponse = moduleRef["validateMenuResponse"];
