// Generated by scripts/build-nop-shared.mjs — host shared module facade.
// Re-exports the host instance registered at bootstrap on
// `window.__NOP_SHARED__`; only loaded by extensions (after registration).
import { getSharedModule } from './_registry.js';

const moduleRef = getSharedModule("zustand");

export default moduleRef.default ?? moduleRef;
export const createStore = moduleRef["createStore"];
export const create = moduleRef["create"];
export const useStore = moduleRef["useStore"];
