#!/bin/bash
# Semantic comparison driver for MA4.2-05 engine-class-split.
#
# Baseline: ai-dev/audits/evidence/ma4-2-05/baseline/<file>.java
#   (snapshots of the three pre-split files, committed as baseline commit
#    662660ab0; see git log -- ai-dev/audits/evidence/ma4-2-05/baseline)
#
# Normalization whitelist (see design doc engine-class-split.md §8):
#   1. access relaxation (private -> package-private/public)
#   2. state-injection parameter appends
#   3. member relocation across classes
#   4. delegation-call rewriting (foo(x) -> helper.foo(x), field refs -> config.field)
#   5. inline-block extraction (execute()/doExecute() blocks -> new methods,
#      matched by >= 0.85 normalized-text overlap)
#
# Usage: ./compare.sh
# Outputs: react-semantic-diff.txt / engine-semantic-diff.txt / daemon-semantic-diff.txt

set -u
DIR="$(cd "$(dirname "$0")" && pwd)"
cd "$DIR"
BASELINE="$DIR/baseline"
SRC="../../../../nop-ai/nop-ai-agent/src/main/java/io/nop/ai/agent"
ENGINE_SRC="$SRC/engine"
TEAM_SRC="$SRC/team/scheduler"

run() {
    local name="$1"; shift
    local baseline="$1"; shift
    python3 "$DIR/compare.py" "$baseline" "$@" --whitelist "$DIR/whitelist.json" > "$DIR/$name" 2>&1
    local rc=$?
    # prepend the evidence header (BASE_REF SHA) so the committed artifact is self-describing
    tmp="$DIR/.$name.tmp"
    printf '%s\n' '# MA4.2-05 semantic comparison evidence'         '# Baseline commit (BASE_REF): 662660ab0 (ai-dev/audits/evidence/ma4-2-05/baseline/)'         '# Methodology + whitelist: design doc ai-dev/design/nop-ai-agent/engine-class-split.md §8'         '# compare domain = original file member set (incl. private) vs new main class ∪ extracted classes'         '# whitelist = access relaxation / state-injection param appends / member relocation /'         '#             delegation-call rewriting / inline-block extraction (containment >= 0.85)'         '# Generated by: compare.sh (python3 compare.py ... --whitelist whitelist.json)'         '' > "$tmp"
    cat "$DIR/$name" >> "$tmp"
    mv "$tmp" "$DIR/$name"
    echo "== $name: exit $rc"
    tail -3 "$DIR/$name"
}

run react-semantic-diff.txt "$BASELINE/ReActAgentExecutor.java" \
    "$ENGINE_SRC/ReActAgentExecutor.java" \
    "$ENGINE_SRC/ReActAgentExecutorBuilder.java" \
    "$ENGINE_SRC/LlmCallCoordinator.java" \
    "$ENGINE_SRC/AgentHookInvoker.java" \
    "$ENGINE_SRC/AgentSecurityConsultation.java" \
    "$ENGINE_SRC/AgentCompactionCoordinator.java" \
    "$ENGINE_SRC/AgentToolPlanResolver.java" \
    "$ENGINE_SRC/AgentPromptAssembly.java" \
    "$ENGINE_SRC/AgentToolDispatcher.java" \
    "$ENGINE_SRC/AgentLoopGuard.java"

run engine-semantic-diff.txt "$BASELINE/DefaultAgentEngine.java" \
    "$ENGINE_SRC/DefaultAgentEngine.java" \
    "$ENGINE_SRC/DefaultAgentEngineConfig.java" \
    "$ENGINE_SRC/AgentSessionLifecycle.java" \
    "$ENGINE_SRC/AgentCallDelegate.java" \
    "$ENGINE_SRC/SessionLockRenewal.java" \
    "$ENGINE_SRC/AgentExecutorResolver.java" \
    "$ENGINE_SRC/AgentSessionSupport.java" \
    "$ENGINE_SRC/AgentTeamBinder.java" \
    "$ENGINE_SRC/AgentStartupWarnings.java"

run daemon-semantic-diff.txt "$BASELINE/TeamTaskSchedulerDaemon.java" \
    "$TEAM_SRC/TeamTaskSchedulerDaemon.java" \
    "$TEAM_SRC/TaskDispatchCoordinator.java"
