
CREATE TABLE nop_batch_file(
  SID VARCHAR(32) NOT NULL    COMMENT '主键',
  FILE_NAME VARCHAR(500) NOT NULL    COMMENT '文件名',
  FILE_PATH VARCHAR(2000) NOT NULL    COMMENT '文件路径',
  FILE_LENGTH BIGINT NOT NULL    COMMENT '文件长度',
  FILE_CATEGORY VARCHAR(100) NOT NULL    COMMENT '文件分类',
  FILE_SOURCE VARCHAR(10) NOT NULL    COMMENT '文件来源',
  BATCH_TASK_ID VARCHAR(32) NOT NULL    COMMENT '批处理任务',
  PROCESS_STATE VARCHAR(10) NOT NULL    COMMENT '处理状态',
  ACCEPT_DATE DATE NOT NULL    COMMENT '文件接收时间',
  VERSION BIGINT NOT NULL    COMMENT '数据版本',
  CREATED_BY VARCHAR(50) NOT NULL    COMMENT '创建人',
  CREATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '创建时间',
  UPDATED_BY VARCHAR(50) NOT NULL    COMMENT '修改人',
  UPDATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '修改时间',
  REMARK VARCHAR(200) NULL    COMMENT '备注',
  constraint PK_nop_batch_file primary key (SID)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs;

CREATE TABLE nop_batch_task(
  SID VARCHAR(32) NOT NULL    COMMENT 'SID',  TASK_NAME VARCHAR(50) NOT NULL    COMMENT '任务名',
  TASK_KEY VARCHAR(100) NOT NULL    COMMENT '唯一Key',
  TASK_STATUS INTEGER NOT NULL    COMMENT '任务状态',
  START_TIME DATETIME(3) NULL    COMMENT '任务启动时间',
  END_TIME DATETIME(3) NULL    COMMENT '任务结束时间',
  TASK_PARAMS VARCHAR(4000) NULL    COMMENT '任务参数',
  EXEC_COUNT INTEGER NOT NULL    COMMENT '执行次数',
  WORKER_ID VARCHAR(100) NOT NULL    COMMENT '执行者',
  INPUT_FILE_ID VARCHAR(32) NULL    COMMENT '输入文件',
  FLOW_STEP_ID VARCHAR(50) NULL    COMMENT '关联流程步骤ID',
  FLOW_ID VARCHAR(50) NULL    COMMENT '关联流程ID',
  RESTART_TIME DATETIME(3) NULL    COMMENT '重启时间',
  RESULT_STATUS INTEGER NULL    COMMENT '返回状态码',
  RESULT_CODE VARCHAR(100) NULL    COMMENT '返回码',
  RESULT_MSG VARCHAR(500) NULL    COMMENT '返回消息',
  ERROR_STACK VARCHAR(4000) NULL    COMMENT '错误堆栈',
  COMPLETED_INDEX BIGINT NOT NULL    COMMENT '已完成记录下标',
  COMPLETE_ITEM_COUNT BIGINT NOT NULL    COMMENT '完成条目数量',
  LOAD_RETRY_COUNT INTEGER NOT NULL    COMMENT '重试加载次数',
  LOAD_SKIP_COUNT BIGINT NOT NULL    COMMENT '加载跳过数量',
  RETRY_ITEM_COUNT INTEGER NOT NULL    COMMENT '重试条目次数',
  PROCESS_ITEM_COUNT BIGINT NOT NULL    COMMENT '处理条目数量',
  SKIP_ITEM_COUNT BIGINT NOT NULL    COMMENT '跳过条目数量',
  WRITE_ITEM_COUNT BIGINT NOT NULL    COMMENT '写入条目数量',
  VERSION BIGINT NOT NULL    COMMENT '数据版本',
  CREATED_BY VARCHAR(50) NOT NULL    COMMENT '创建人',
  CREATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '创建时间',
  UPDATED_BY VARCHAR(50) NOT NULL    COMMENT '修改人',
  UPDATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '修改时间',
  REMARK VARCHAR(200) NULL    COMMENT '备注',
  constraint PK_nop_batch_task primary key (SID)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs;

CREATE TABLE nop_batch_task_var(
  BATCH_TASK_ID VARCHAR(32) NOT NULL    COMMENT '主键',  FIELD_NAME VARCHAR(100) NOT NULL    COMMENT '变量名',
  FIELD_TYPE INTEGER NOT NULL    COMMENT '变量类型',
  STRING_VALUE VARCHAR(4000) NULL    COMMENT '字符串值',
  DECIMAL_VALUE DECIMAL(30,6) NULL    COMMENT '浮点值',
  LONG_VALUE BIGINT NULL    COMMENT '整数型',
  DATE_VALUE DATE NULL    COMMENT '日期值',
  TIMESTAMP_VALUE DATETIME(3) NULL    COMMENT '时间点值',
  VERSION BIGINT NOT NULL    COMMENT '数据版本',
  CREATED_BY VARCHAR(50) NOT NULL    COMMENT '创建人',
  CREATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '创建时间',
  UPDATED_BY VARCHAR(50) NOT NULL    COMMENT '修改人',
  UPDATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '修改时间',
  constraint PK_nop_batch_task_var primary key (BATCH_TASK_ID,FIELD_NAME)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs;

CREATE TABLE nop_batch_record_result(
  BATCH_TASK_ID VARCHAR(32) NOT NULL    COMMENT '主键',  RECORD_KEY VARCHAR(200) NOT NULL    COMMENT '记录唯一键',
  RESULT_STATUS INTEGER NOT NULL    COMMENT '返回状态码',
  RESULT_CODE VARCHAR(100) NULL    COMMENT '返回码',
  RESULT_MSG VARCHAR(500) NULL    COMMENT '返回消息',
  ERROR_STACK VARCHAR(4000) NULL    COMMENT '错误堆栈',
  RECORD_INFO VARCHAR(2000) NULL    COMMENT '记录信息',
  RETRY_COUNT INTEGER NOT NULL    COMMENT '重试次数',
  BATCH_SIZE INTEGER NOT NULL    COMMENT '批次大小',
  HANDLE_STATUS INTEGER NOT NULL    COMMENT '处理状态',
  VERSION BIGINT NOT NULL    COMMENT '数据版本',
  CREATED_BY VARCHAR(50) NOT NULL    COMMENT '创建人',
  CREATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '创建时间',
  UPDATED_BY VARCHAR(50) NOT NULL    COMMENT '修改人',
  UPDATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '修改时间',
  constraint PK_nop_batch_record_result primary key (BATCH_TASK_ID,RECORD_KEY)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs;


   ALTER TABLE nop_batch_file COMMENT '批处理文件';                
   ALTER TABLE nop_batch_task COMMENT '批处理任务';
                
   ALTER TABLE nop_batch_task_var COMMENT '批处理任务状态变量';
                
   ALTER TABLE nop_batch_record_result COMMENT '批处理记录结果';
                
