jobName: wf-due-task-scan
enabled: "@cfg:nop.job.wf-due-task-scan.enabled|false"
displayName: Workflow Due Task Scan
jobGroup: nop-wf
trigger:
  cronExpr: "@cfg:nop.job.wf-due-task-scan.cron-expr|0 0/1 * * * ?"
invoker:
  bean: wfTaskScanner
  method: scanDueTasks
