/**
 * Copyright (c) 2017-2024 Nop Platform. All rights reserved.
 * Author: canonical_entropy@163.com
 * Blog:   https://www.zhihu.com/people/canonical-entropy
 * Gitee:  https://gitee.com/canonical-entropy/nop-entropy
 * Github: https://github.com/entropy-cloud/nop-entropy
 */
package io.nop.stream.core.execution.plan;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.Collections;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;

import io.nop.api.core.annotations.data.DataBean;

/**
 * Materialized physical subtask→node assignment, persisted inside {@link DeploymentPlan}.
 *
 * <p>Maps each {@code (vertexId, subtaskIndex)} pair to a target {@code nodeId}.
 * This allows deployment decisions to be audited and replayed independently of the runtime.
 *
 * <p>The assignment is generated by the distributed {@link io.nop.stream.core.execution.IDeploymentPlanProvider}
 * (round-robin over the active node set) and consumed by
 * {@link io.nop.stream.runtime.coordinator.JobCoordinator#assignTasks()}.
 *
 * <p>When {@code null} or empty, the runtime falls back to runtime-side round-robin assignment
 * (the {@code ClusterRegistry}-based legacy path).
 */
@DataBean
public class DeploymentAssignment implements Serializable {

    private static final long serialVersionUID = 1L;

    private final Map<String, List<String>> vertexAssignments;

    public DeploymentAssignment(Map<String, List<String>> vertexAssignments) {
        if (vertexAssignments != null) {
            Map<String, List<String>> copy = new LinkedHashMap<>();
            for (Map.Entry<String, List<String>> entry : vertexAssignments.entrySet()) {
                copy.put(entry.getKey(),
                        Collections.unmodifiableList(new ArrayList<>(entry.getValue())));
            }
            this.vertexAssignments = Collections.unmodifiableMap(copy);
        } else {
            this.vertexAssignments = Collections.emptyMap();
        }
    }

    public DeploymentAssignment() {
        this(null);
    }

    /**
     * Returns the nodeId assigned to the given subtask, or {@code null} if no assignment exists.
     *
     * @param vertexId     the vertex identifier
     * @param subtaskIndex the subtask index within the vertex
     * @return the target nodeId, or null if not assigned
     */
    public String getNodeForSubtask(String vertexId, int subtaskIndex) {
        List<String> nodes = vertexAssignments.get(vertexId);
        if (nodes == null || subtaskIndex < 0 || subtaskIndex >= nodes.size()) {
            return null;
        }
        return nodes.get(subtaskIndex);
    }

    /**
     * @return true if this assignment contains no vertex mappings.
     */
    public boolean isEmpty() {
        return vertexAssignments.isEmpty();
    }

    /**
     * @return an immutable map of vertexId → ordered list of nodeIds (index = subtaskIndex).
     */
    public Map<String, List<String>> getVertexAssignments() {
        return vertexAssignments;
    }
}
