
CREATE TABLE nop_report_definition(
  RPT_ID VARCHAR(32) NOT NULL    COMMENT '主键',
  RPT_NO VARCHAR(200) NOT NULL    COMMENT '报表编号',
  RPT_NAME VARCHAR(200) NOT NULL    COMMENT '报表名称',
  DESCRIPTION VARCHAR(1000) NULL    COMMENT '描述',
  RPT_TEXT MEDIUMTEXT NOT NULL    COMMENT '报表文件',
  STATUS INTEGER NOT NULL    COMMENT '状态',
  VERSION INTEGER NOT NULL    COMMENT '数据版本',
  CREATED_BY VARCHAR(50) NOT NULL    COMMENT '创建人',
  CREATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '创建时间',
  UPDATED_BY VARCHAR(50) NOT NULL    COMMENT '修改人',
  UPDATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '修改时间',
  REMARK VARCHAR(200) NULL    COMMENT '备注',
  constraint PK_nop_report_definition primary key (RPT_ID)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs;

CREATE TABLE nop_report_dataset(
  SID VARCHAR(200) NOT NULL    COMMENT '主键',
  DS_NAME VARCHAR(200) NOT NULL    COMMENT '数据集名称',
  IS_SINGLE_ROW BOOLEAN NOT NULL    COMMENT '是否单行',
  DESCRIPTION VARCHAR(1000) NULL    COMMENT '描述',
  DS_TYPE VARCHAR(100) NOT NULL    COMMENT '数据集类型',
  DATASOURCE_ID VARCHAR(32) NULL    COMMENT '数据源ID',
  DS_TEXT MEDIUMTEXT NOT NULL    COMMENT '数据集文本',
  DS_META MEDIUMTEXT NOT NULL    COMMENT '数据集元数据',
  DS_CONFIG MEDIUMTEXT NULL    COMMENT '数据集配置',
  FILTER_RULE VARCHAR(4000) NULL    COMMENT '过滤规则',
  STATUS INTEGER NOT NULL    COMMENT '状态',
  VERSION INTEGER NOT NULL    COMMENT '数据版本',
  CREATED_BY VARCHAR(50) NOT NULL    COMMENT '创建人',
  CREATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '创建时间',
  UPDATED_BY VARCHAR(50) NOT NULL    COMMENT '修改人',
  UPDATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '修改时间',
  REMARK VARCHAR(200) NULL    COMMENT '备注',
  constraint PK_nop_report_dataset primary key (SID)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs;

CREATE TABLE nop_report_datasource(
  SID VARCHAR(32) NOT NULL    COMMENT '主键ID',
  NAME VARCHAR(100) NOT NULL    COMMENT '数据源名称',
  DATASOURCE_TYPE VARCHAR(20) NOT NULL    COMMENT '数据源类型',
  DATASOURCE_CONFIG VARCHAR(4000) NOT NULL    COMMENT '数据源配置',
  STATUS INTEGER NULL    COMMENT '状态',
  REMARK VARCHAR(500) NULL    COMMENT '备注说明',
  VERSION INTEGER NOT NULL    COMMENT '数据版本',
  CREATED_BY VARCHAR(50) NOT NULL    COMMENT '创建人',
  CREATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '创建时间',
  UPDATED_BY VARCHAR(50) NOT NULL    COMMENT '修改人',
  UPDATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '修改时间',
  constraint PK_nop_report_datasource primary key (SID)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs;

CREATE TABLE nop_report_definition_auth(
  SID VARCHAR(32) NOT NULL    COMMENT '主键',
  RPT_ID VARCHAR(32) NOT NULL    COMMENT '报表ID',
  ROLE_ID VARCHAR(200) NOT NULL    COMMENT '角色ID',
  VERSION INTEGER NOT NULL    COMMENT '数据版本',
  CREATED_BY VARCHAR(50) NOT NULL    COMMENT '创建人',
  CREATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '创建时间',
  UPDATED_BY VARCHAR(50) NOT NULL    COMMENT '修改人',
  UPDATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '修改时间',
  REMARK VARCHAR(200) NULL    COMMENT '备注',
  constraint PK_nop_report_definition_auth primary key (SID)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs;

CREATE TABLE nop_report_dataset_ref(
  RPT_ID VARCHAR(32) NOT NULL    COMMENT '报表主键',
  DS_ID VARCHAR(32) NOT NULL    COMMENT '数据集ID',
  VERSION INTEGER NOT NULL    COMMENT '数据版本',
  CREATED_BY VARCHAR(50) NOT NULL    COMMENT '创建人',
  CREATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '创建时间',
  UPDATED_BY VARCHAR(50) NOT NULL    COMMENT '修改人',
  UPDATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '修改时间',
  REMARK VARCHAR(200) NULL    COMMENT '备注',
  constraint PK_nop_report_dataset_ref primary key (RPT_ID,DS_ID)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs;

CREATE TABLE nop_report_result_file(
  SID VARCHAR(50) NOT NULL    COMMENT '主键',
  FILE_NAME VARCHAR(200) NOT NULL    COMMENT '文件名称',
  FILE_TYPE VARCHAR(10) NOT NULL    COMMENT '文件类型',
  FILE_PATH VARCHAR(100) NOT NULL    COMMENT '文件路径',
  FILE_LENGTH BIGINT NOT NULL    COMMENT '文件长度',
  BIZ_DATE DATE NULL    COMMENT '业务日期',
  RPT_ID VARCHAR(200) NOT NULL    COMMENT '报表ID',
  RPT_PARAMS VARCHAR(4000) NOT NULL    COMMENT '报表参数',
  STATUS INTEGER NOT NULL    COMMENT '状态',
  DESCRIPTION VARCHAR(1000) NULL    COMMENT '描述',
  VERSION INTEGER NOT NULL    COMMENT '数据版本',
  CREATED_BY VARCHAR(50) NOT NULL    COMMENT '创建人',
  CREATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '创建时间',
  UPDATED_BY VARCHAR(50) NOT NULL    COMMENT '修改人',
  UPDATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '修改时间',
  REMARK VARCHAR(200) NULL    COMMENT '备注',
  constraint PK_nop_report_result_file primary key (SID)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs;

CREATE TABLE nop_report_sub_dataset(
  SID VARCHAR(32) NOT NULL    COMMENT '主键',
  DS_ID VARCHAR(32) NOT NULL    COMMENT '数据集ID',
  SUB_DS_ID VARCHAR(32) NOT NULL    COMMENT '子数据集ID',
  JOIN_FIELDS VARCHAR(500) NOT NULL    COMMENT '关联字段',
  DS_PARAMS VARCHAR(500) NULL    COMMENT '子数据集参数',
  VERSION INTEGER NOT NULL    COMMENT '数据版本',
  CREATED_BY VARCHAR(50) NOT NULL    COMMENT '创建人',
  CREATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '创建时间',
  UPDATED_BY VARCHAR(50) NOT NULL    COMMENT '修改人',
  UPDATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '修改时间',
  REMARK VARCHAR(200) NULL    COMMENT '备注',
  constraint PK_nop_report_sub_dataset primary key (SID)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs;

CREATE TABLE nop_report_datasource_auth(
  SID VARCHAR(32) NOT NULL    COMMENT '主键',
  DATASOURCE_ID VARCHAR(32) NOT NULL    COMMENT '数据源ID',
  ROLE_ID VARCHAR(200) NOT NULL    COMMENT '角色ID',
  VERSION INTEGER NOT NULL    COMMENT '数据版本',
  CREATED_BY VARCHAR(50) NOT NULL    COMMENT '创建人',
  CREATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '创建时间',
  UPDATED_BY VARCHAR(50) NOT NULL    COMMENT '修改人',
  UPDATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '修改时间',
  REMARK VARCHAR(200) NULL    COMMENT '备注',
  constraint PK_nop_report_datasource_auth primary key (SID)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs;


   ALTER TABLE nop_report_definition COMMENT '报表定义';
                
   ALTER TABLE nop_report_dataset COMMENT '数据集定义';
                
   ALTER TABLE nop_report_datasource COMMENT '数据源定义';
                
   ALTER TABLE nop_report_definition_auth COMMENT 'Report访问权限';
                
   ALTER TABLE nop_report_dataset_ref COMMENT '报表引用数据源';
                
   ALTER TABLE nop_report_result_file COMMENT '报表结果文件';
                
   ALTER TABLE nop_report_sub_dataset COMMENT '子数据源';
                
   ALTER TABLE nop_report_datasource_auth COMMENT '数据源访问权限';
                
