/*
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */

package io.nop.stream.fraud.model;

import java.io.Serializable;
import java.util.List;
import java.util.Objects;

/**
 * FraudAlert represents a fraud detection alert generated by the fraud detection system.
 */
public class FraudAlert implements Serializable {
    private static final long serialVersionUID = 1L;

    private final String alertId;
    private final String fraudType;
    private final String userId;
    private final String description;
    private final long timestamp;
    private final List<TransactionEvent> triggeringEvents;

    /**
     * Creates a new FraudAlert.
     *
     * @param alertId unique alert identifier
     * @param fraudType type of fraud detected
     * @param userId user who triggered the alert
     * @param description human-readable description
     * @param timestamp when alert was generated (epoch millis)
     * @param triggeringEvents events that triggered this alert
     */
    public FraudAlert(String alertId, String fraudType, String userId, String description, 
                     long timestamp, List<TransactionEvent> triggeringEvents) {
        this.alertId = alertId;
        this.fraudType = fraudType;
        this.userId = userId;
        this.description = description;
        this.timestamp = timestamp;
        this.triggeringEvents = triggeringEvents;
    }

    /**
     * @return unique alert identifier
     */
    public String getAlertId() {
        return alertId;
    }

    /**
     * @return type of fraud detected
     */
    public String getFraudType() {
        return fraudType;
    }

    /**
     * @return user who triggered the alert
     */
    public String getUserId() {
        return userId;
    }

    /**
     * @return human-readable description
     */
    public String getDescription() {
        return description;
    }

    /**
     * @return when alert was generated (epoch millis)
     */
    public long getTimestamp() {
        return timestamp;
    }

    /**
     * @return events that triggered this alert
     */
    public List<TransactionEvent> getTriggeringEvents() {
        return triggeringEvents;
    }

    @Override
    public String toString() {
        return "FraudAlert{" +
                "alertId='" + alertId + '\'' +
                ", fraudType='" + fraudType + '\'' +
                ", userId='" + userId + '\'' +
                ", description='" + description + '\'' +
                ", timestamp=" + timestamp +
                ", triggeringEvents=" + triggeringEvents +
                '}';
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        FraudAlert that = (FraudAlert) o;
        return timestamp == that.timestamp &&
                Objects.equals(alertId, that.alertId) &&
                Objects.equals(fraudType, that.fraudType) &&
                Objects.equals(userId, that.userId) &&
                Objects.equals(description, that.description) &&
                Objects.equals(triggeringEvents, that.triggeringEvents);
    }

    @Override
    public int hashCode() {
        return Objects.hash(alertId, fraudType, userId, description, timestamp, triggeringEvents);
    }
}