nop:
  application:
    name: demo-service

  cluster:
    discovery:
      sys-dao-naming-service:
        enabled: true
    registration:
      enabled: true

  orm:
    init-database-schema: true
    enable-tenant-by-default: false

  dao:
    use-parent-data-source: true

  server:
    port: 8082

spring:
  datasource:
    driver-class-name: org.h2.Driver
    # AUTO_SERVER=TRUE 允许多个进程同时访问同一个数据库文件
    # 第一个连接自动启动内嵌TCP服务器，其他连接作为客户端
    url: jdbc:h2:./db/demo-service;AUTO_SERVER=TRUE
    username: sa
    password:

server:
  port: ${nop.server.port}
  http2:
    enabled: true

logging:
  level:
    ROOT: INFO
    io.nop: DEBUG

management:
  health:
    probes:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health

"%dev":
  nop:
    debug: true

  logging:
    level:
      ROOT: DEBUG
      io.nop: TRACE
