
CREATE TABLE nop_dyn_app(
  APP_ID VARCHAR(32) NOT NULL    COMMENT '应用ID',
  APP_NAME VARCHAR(200) NOT NULL    COMMENT '应用名',
  DISPLAY_NAME VARCHAR(200) NOT NULL    COMMENT '显示名',
  STATUS INTEGER NOT NULL    COMMENT '状态',
  VERSION INTEGER NOT NULL    COMMENT '数据版本',
  CREATED_BY VARCHAR(50) NOT NULL    COMMENT '创建人',
  CREATE_TIME TIMESTAMP NOT NULL  DEFAULT CURRENT_TIMESTAMP    COMMENT '创建时间',
  UPDATED_BY VARCHAR(50) NOT NULL    COMMENT '修改人',
  UPDATE_TIME TIMESTAMP NOT NULL  DEFAULT CURRENT_TIMESTAMP    COMMENT '修改时间',
  constraint PK_nop_dyn_app primary key (APP_ID)
);

CREATE TABLE nop_dyn_module(
  MODULE_ID VARCHAR(32) NOT NULL    COMMENT '模块ID',
  MODULE_NAME VARCHAR(100) NOT NULL    COMMENT '模块名',
  MODULE_VERSION INTEGER NOT NULL    COMMENT '模块版本',
  DISPLAY_NAME VARCHAR(200) NOT NULL    COMMENT '显示名',
  BASE_MODULE_ID VARCHAR(100) NULL    COMMENT '基础模块ID',
  BASE_PACKAGE_NAME VARCHAR(200) NULL    COMMENT 'Java包名',
  MAVEN_GROUP_ID VARCHAR(200) NULL    COMMENT 'Maven组名',
  STATUS INTEGER NOT NULL    COMMENT '状态',
  VERSION INTEGER NOT NULL    COMMENT '数据版本',
  CREATED_BY VARCHAR(50) NOT NULL    COMMENT '创建人',
  CREATE_TIME TIMESTAMP NOT NULL  DEFAULT CURRENT_TIMESTAMP    COMMENT '创建时间',
  UPDATED_BY VARCHAR(50) NOT NULL    COMMENT '修改人',
  UPDATE_TIME TIMESTAMP NOT NULL  DEFAULT CURRENT_TIMESTAMP    COMMENT '修改时间',
  constraint PK_nop_dyn_module primary key (MODULE_ID)
);

CREATE TABLE nop_dyn_domain(
  DOMAIN_ID VARCHAR(32) NOT NULL    COMMENT '数据域ID',
  DOMAIN_NAME VARCHAR(50) NOT NULL    COMMENT '数据域名称',
  DISPLAY_NAME VARCHAR(100) NOT NULL    COMMENT '显示名',
  STD_DOMAIN_NAME VARCHAR(50) NULL    COMMENT '标准域',
  STD_SQL_TYPE VARCHAR(10) NOT NULL    COMMENT '标准SQL数据类型',
  `PRECISION` INTEGER NULL    COMMENT '长度',
  SCALE INTEGER NULL    COMMENT '小数位数',
  VERSION INTEGER NOT NULL    COMMENT '数据版本',
  CREATED_BY VARCHAR(50) NOT NULL    COMMENT '创建人',
  CREATE_TIME TIMESTAMP NOT NULL  DEFAULT CURRENT_TIMESTAMP    COMMENT '创建时间',
  UPDATED_BY VARCHAR(50) NOT NULL    COMMENT '修改人',
  UPDATE_TIME TIMESTAMP NOT NULL  DEFAULT CURRENT_TIMESTAMP    COMMENT '修改时间',
  REMARK VARCHAR(200) NULL    COMMENT '备注',
  constraint PK_nop_dyn_domain primary key (DOMAIN_ID)
);

CREATE TABLE nop_dyn_entity(
  SID VARCHAR(32) NOT NULL    COMMENT '主键',
  NOP_OBJ_TYPE VARCHAR(100) NOT NULL    COMMENT '对象类型',
  NOP_NAME VARCHAR(100) NULL    COMMENT '名称',
  NOP_DISPLAY_NAME VARCHAR(500) NULL    COMMENT '显示名称',
  NOP_SORT_ORDER INTEGER NULL    COMMENT '排序',
  NOP_FLOW_ID VARCHAR(32) NULL    COMMENT '工作流实例ID',
  NOP_STATUS INTEGER NULL    COMMENT '业务状态码',
  NOP_BIZ_STATE VARCHAR(50) NULL    COMMENT '业务状态',
  NOP_PARENT_ID VARCHAR(32) NULL    COMMENT '父ID',
  NOP_OWNER_NAME VARCHAR(50) NULL    COMMENT '拥有者姓名',
  NOP_OWNER_ID VARCHAR(50) NULL    COMMENT '拥有者ID',
  NOP_DEPT_ID VARCHAR(50) NULL    COMMENT '部门ID',
  NOP_STRING_FLD1 VARCHAR(4000) NULL    COMMENT '字符串字段1',
  NOP_DECIMAL_FLD1 DECIMAL(30,6) NULL    COMMENT '浮点型字段1',
  NOP_INT_FLD1 INTEGER NULL    COMMENT '整数型字段1',
  NOP_LONG_FLD1 BIGINT NULL    COMMENT '长整型字段1',
  NOP_DATE_FLD1 DATE NULL    COMMENT '日期字段1',
  NOP_TIMESTAMP_FLD1 TIMESTAMP NULL    COMMENT '时间戳字段1',
  NOP_FILE_FLD1 VARCHAR(200) NULL    COMMENT '文件字段1',
  NOP_STRING_FLD2 VARCHAR(4000) NULL    COMMENT '字符串字段2',
  NOP_DECIMAL_FLD2 DECIMAL(30,6) NULL    COMMENT '浮点型字段2',
  NOP_INT_FLD2 INTEGER NULL    COMMENT '整数型字段2',
  NOP_LONG_FLD2 BIGINT NULL    COMMENT '长整型字段2',
  NOP_DATE_FLD2 DATE NULL    COMMENT '日期字段2',
  NOP_TIMESTAMP_FLD2 TIMESTAMP NULL    COMMENT '时间戳字段2',
  NOP_FILE_FLD2 VARCHAR(200) NULL    COMMENT '文件字段2',
  VERSION INTEGER NOT NULL    COMMENT '数据版本',
  CREATED_BY VARCHAR(50) NOT NULL    COMMENT '创建人',
  CREATE_TIME TIMESTAMP NOT NULL  DEFAULT CURRENT_TIMESTAMP    COMMENT '创建时间',
  UPDATED_BY VARCHAR(50) NOT NULL    COMMENT '修改人',
  UPDATE_TIME TIMESTAMP NOT NULL  DEFAULT CURRENT_TIMESTAMP    COMMENT '修改时间',
  REMARK VARCHAR(200) NULL    COMMENT '备注',
  constraint PK_nop_dyn_entity primary key (SID)
);

CREATE TABLE nop_dyn_entity_relation(
  SID VARCHAR(32) NOT NULL    COMMENT '主键',
  RELATION_NAME VARCHAR(50) NOT NULL    COMMENT '关联名称',
  ENTITY_NAME1 VARCHAR(100) NOT NULL    COMMENT '实体名称1',
  ENTITY_ID1 VARCHAR(50) NOT NULL    COMMENT '实体ID1',
  ENTITY_NAME2 VARCHAR(100) NOT NULL    COMMENT '实体名称2',
  ENTITY_ID2 VARCHAR(50) NOT NULL    COMMENT '实体ID2',
  VERSION INTEGER NOT NULL    COMMENT '数据版本',
  CREATED_BY VARCHAR(50) NOT NULL    COMMENT '创建人',
  CREATE_TIME TIMESTAMP NOT NULL  DEFAULT CURRENT_TIMESTAMP    COMMENT '创建时间',
  UPDATED_BY VARCHAR(50) NOT NULL    COMMENT '修改人',
  UPDATE_TIME TIMESTAMP NOT NULL  DEFAULT CURRENT_TIMESTAMP    COMMENT '修改时间',
  REMARK VARCHAR(200) NULL    COMMENT '备注',
  constraint PK_nop_dyn_entity_relation primary key (SID)
);

CREATE TABLE nop_dyn_module_dep(
  MODULE_ID VARCHAR(32) NOT NULL    COMMENT '模块ID',
  DEP_MODULE_ID VARCHAR(32) NOT NULL    COMMENT '被依赖模块ID',
  VERSION INTEGER NOT NULL    COMMENT '数据版本',
  CREATED_BY VARCHAR(50) NOT NULL    COMMENT '创建人',
  CREATE_TIME TIMESTAMP NOT NULL  DEFAULT CURRENT_TIMESTAMP    COMMENT '创建时间',
  UPDATED_BY VARCHAR(50) NOT NULL    COMMENT '修改人',
  UPDATE_TIME TIMESTAMP NOT NULL  DEFAULT CURRENT_TIMESTAMP    COMMENT '修改时间',
  constraint PK_nop_dyn_module_dep primary key (MODULE_ID,DEP_MODULE_ID)
);

CREATE TABLE nop_dyn_app_module(
  APP_ID VARCHAR(32) NOT NULL    COMMENT '应用ID',
  MODULE_ID VARCHAR(32) NOT NULL    COMMENT '模块ID',
  VERSION INTEGER NOT NULL    COMMENT '数据版本',
  CREATED_BY VARCHAR(50) NOT NULL    COMMENT '创建人',
  CREATE_TIME TIMESTAMP NOT NULL  DEFAULT CURRENT_TIMESTAMP    COMMENT '创建时间',
  UPDATED_BY VARCHAR(50) NOT NULL    COMMENT '修改人',
  UPDATE_TIME TIMESTAMP NOT NULL  DEFAULT CURRENT_TIMESTAMP    COMMENT '修改时间',
  constraint PK_nop_dyn_app_module primary key (APP_ID,MODULE_ID)
);

CREATE TABLE nop_dyn_sql(
  SQL_ID VARCHAR(32) NOT NULL    COMMENT 'SQL ID',
  MODULE_ID VARCHAR(32) NOT NULL    COMMENT '模块ID',
  NAME VARCHAR(100) NOT NULL    COMMENT 'SQL名称',
  DISPLAY_NAME VARCHAR(200) NULL    COMMENT '显示名称',
  SQL_METHOD VARCHAR(10) NULL    COMMENT 'SQL方法',
  ROW_TYPE VARCHAR(100) NULL    COMMENT '行类型',
  DESCRIPTION VARCHAR(2000) NULL    COMMENT '描述',
  CACHE_NAME VARCHAR(100) NULL    COMMENT '缓存名称',
  CACHE_KEY_EXPR VARCHAR(200) NULL    COMMENT '缓存键表达式',
  BATCH_LOAD_SELECTION VARCHAR(200) NULL    COMMENT '批量加载选择集',
  SQL_KIND VARCHAR(10) NULL    COMMENT '类型',
  QUERY_SPACE VARCHAR(100) NULL    COMMENT '查询空间',
  SOURCE VARCHAR(8000) NULL    COMMENT 'SQL文本',
  FETCH_SIZE INTEGER NULL    COMMENT '读取块大小',
  TIMEOUT INTEGER NULL    COMMENT '超时时间',
  DISABLE_LOGICAL_DELETE TINYINT NULL    COMMENT '禁用逻辑删除',
  ENABLE_FILTER TINYINT NULL    COMMENT '启用数据权限',
  REFRESH_BEHAVIOR VARCHAR(10) NULL    COMMENT '实体刷新规则',
  COL_NAME_CAMEL_CASE TINYINT NULL    COMMENT '列名需要转换为驼峰',
  ARGS VARCHAR(4000) NULL    COMMENT '参数列表',
  STATUS INTEGER NOT NULL    COMMENT '状态',
  VERSION INTEGER NOT NULL    COMMENT '数据版本',
  CREATED_BY VARCHAR(50) NOT NULL    COMMENT '创建人',
  CREATE_TIME TIMESTAMP NOT NULL  DEFAULT CURRENT_TIMESTAMP    COMMENT '创建时间',
  UPDATED_BY VARCHAR(50) NOT NULL    COMMENT '修改人',
  UPDATE_TIME TIMESTAMP NOT NULL  DEFAULT CURRENT_TIMESTAMP    COMMENT '修改时间',
  REMARK VARCHAR(200) NULL    COMMENT '备注',
  constraint PK_nop_dyn_sql primary key (SQL_ID)
);

CREATE TABLE nop_dyn_file(
  FILE_ID VARCHAR(32) NOT NULL    COMMENT '文件ID',
  MODULE_ID VARCHAR(32) NOT NULL    COMMENT '模块ID',
  FILE_NAME VARCHAR(200) NOT NULL    COMMENT '文件名称',
  FILE_PATH VARCHAR(800) NOT NULL    COMMENT '文件路径',
  FILE_TYPE VARCHAR(50) NOT NULL    COMMENT '文件类型',
  FILE_LENGTH INTEGER NOT NULL    COMMENT '文件大小',
  STATUS INTEGER NOT NULL    COMMENT '状态',
  VERSION INTEGER NOT NULL    COMMENT '数据版本',
  CREATED_BY VARCHAR(50) NOT NULL    COMMENT '创建人',
  CREATE_TIME TIMESTAMP NOT NULL  DEFAULT CURRENT_TIMESTAMP    COMMENT '创建时间',
  UPDATED_BY VARCHAR(50) NOT NULL    COMMENT '修改人',
  UPDATE_TIME TIMESTAMP NOT NULL  DEFAULT CURRENT_TIMESTAMP    COMMENT '修改时间',
  REMARK VARCHAR(200) NULL    COMMENT '备注',
  constraint PK_nop_dyn_file primary key (FILE_ID)
);

CREATE TABLE nop_dyn_page(
  PAGE_ID VARCHAR(32) NOT NULL    COMMENT '页面ID',
  MODULE_ID VARCHAR(32) NOT NULL    COMMENT '模块ID',
  PAGE_NAME VARCHAR(200) NOT NULL    COMMENT '页面名称',
  PAGE_GROUP VARCHAR(100) NOT NULL    COMMENT '页面分组',
  PAGE_SCHEMA_TYPE VARCHAR(100) NOT NULL    COMMENT '页面类型',
  PAGE_CONTENT LONGTEXT NOT NULL    COMMENT '页面内容',
  STATUS INTEGER NOT NULL    COMMENT '状态',
  VERSION INTEGER NOT NULL    COMMENT '数据版本',
  CREATED_BY VARCHAR(50) NOT NULL    COMMENT '创建人',
  CREATE_TIME TIMESTAMP NOT NULL  DEFAULT CURRENT_TIMESTAMP    COMMENT '创建时间',
  UPDATED_BY VARCHAR(50) NOT NULL    COMMENT '修改人',
  UPDATE_TIME TIMESTAMP NOT NULL  DEFAULT CURRENT_TIMESTAMP    COMMENT '修改时间',
  REMARK VARCHAR(200) NULL    COMMENT '备注',
  constraint PK_nop_dyn_page primary key (PAGE_ID)
);

CREATE TABLE nop_dyn_entity_meta(
  ENTITY_META_ID VARCHAR(32) NOT NULL    COMMENT '实体定义ID',
  MODULE_ID VARCHAR(32) NOT NULL    COMMENT '模块ID',
  ENTITY_NAME VARCHAR(200) NOT NULL    COMMENT '实体名',
  DISPLAY_NAME VARCHAR(100) NOT NULL    COMMENT '显示名',
  TABLE_NAME VARCHAR(100) NULL    COMMENT '表名',
  QUERY_SPACE VARCHAR(100) NULL    COMMENT '查询空间',
  STORE_TYPE INTEGER NOT NULL    COMMENT '存储类型',
  TAGS_TEXT VARCHAR(200) NULL    COMMENT '标签',
  IS_EXTERNAL BOOLEAN NOT NULL    COMMENT '是否外部实体',
  STATUS INTEGER NOT NULL    COMMENT '状态',
  EXT_CONFIG VARCHAR(1000) NULL    COMMENT '扩展配置',
  VERSION INTEGER NOT NULL    COMMENT '数据版本',
  CREATED_BY VARCHAR(50) NOT NULL    COMMENT '创建人',
  CREATE_TIME TIMESTAMP NOT NULL  DEFAULT CURRENT_TIMESTAMP    COMMENT '创建时间',
  UPDATED_BY VARCHAR(50) NOT NULL    COMMENT '修改人',
  UPDATE_TIME TIMESTAMP NOT NULL  DEFAULT CURRENT_TIMESTAMP    COMMENT '修改时间',
  REMARK VARCHAR(200) NULL    COMMENT '备注',
  constraint PK_nop_dyn_entity_meta primary key (ENTITY_META_ID)
);

CREATE TABLE nop_dyn_prop_meta(
  PROP_META_ID VARCHAR(32) NOT NULL    COMMENT '属性定义ID',
  ENTITY_META_ID VARCHAR(32) NOT NULL    COMMENT '实体定义ID',
  IS_MANDATORY BOOLEAN NOT NULL    COMMENT '是否非空',
  PROP_NAME VARCHAR(50) NOT NULL    COMMENT '属性名',
  DISPLAY_NAME VARCHAR(100) NOT NULL    COMMENT '显示名',
  STD_SQL_TYPE VARCHAR(10) NOT NULL    COMMENT '标准SQL数据类型',
  `PRECISION` INTEGER NULL    COMMENT '长度',
  SCALE INTEGER NULL    COMMENT '小数位数',
  PROP_ID INTEGER NOT NULL    COMMENT '属性编号',
  UI_SHOW VARCHAR(10) NULL    COMMENT '显示控制',
  UI_CONTROL VARCHAR(100) NULL    COMMENT '显示控件',
  DOMAIN_ID VARCHAR(32) NULL    COMMENT '数据域ID',
  STD_DOMAIN_NAME VARCHAR(50) NULL    COMMENT '标准域',
  DICT_NAME VARCHAR(100) NULL    COMMENT '数据字典',
  DYN_PROP_MAPPING VARCHAR(100) NULL    COMMENT '动态字段映射',
  TAGS_TEXT VARCHAR(200) NULL    COMMENT '标签',
  DEFAULT_VALUE VARCHAR(100) NULL    COMMENT '缺省值',
  REF_ENTITY_NAME VARCHAR(200) NULL    COMMENT '关联实体名',
  REF_PROP_NAME VARCHAR(100) NULL    COMMENT '关联属性名',
  REF_PROP_DISPLAY_NAME VARCHAR(100) NULL    COMMENT '关联属性显示名',
  REF_SET_SORT VARCHAR(200) NULL    COMMENT '关联集合排序条件',
  REF_TAGS_TEXT VARCHAR(200) NULL    COMMENT '关联属性标签',
  EXT_CONFIG VARCHAR(1000) NULL    COMMENT '扩展配置',
  STATUS INTEGER NOT NULL    COMMENT '状态',
  VERSION INTEGER NOT NULL    COMMENT '数据版本',
  CREATED_BY VARCHAR(50) NOT NULL    COMMENT '创建人',
  CREATE_TIME TIMESTAMP NOT NULL  DEFAULT CURRENT_TIMESTAMP    COMMENT '创建时间',
  UPDATED_BY VARCHAR(50) NOT NULL    COMMENT '修改人',
  UPDATE_TIME TIMESTAMP NOT NULL  DEFAULT CURRENT_TIMESTAMP    COMMENT '修改时间',
  REMARK VARCHAR(200) NULL    COMMENT '备注',
  constraint PK_nop_dyn_prop_meta primary key (PROP_META_ID)
);

CREATE TABLE nop_dyn_entity_relation_meta(
  REL_META_ID VARCHAR(32) NOT NULL    COMMENT '关联定义ID',
  ENTITY1_META_ID VARCHAR(32) NOT NULL    COMMENT '实体1元数据',
  ENTITY2_META_ID VARCHAR(32) NOT NULL    COMMENT '实体2元数据',
  RELATION_NAME VARCHAR(100) NOT NULL    COMMENT '关联名',
  ENTITY1_PROP_NAME VARCHAR(100) NOT NULL    COMMENT '实体1上属性名',
  ENTITY1_DISPLAY_NAME VARCHAR(100) NOT NULL    COMMENT '实体1上属性显示名',
  ENTITY2_PROP_NAME VARCHAR(100) NULL    COMMENT '实体2上属性名',
  ENTITY2_DISPLAY_NAME VARCHAR(100) NULL    COMMENT '实体2上属性显示名',
  TABLE_NAME VARCHAR(100) NULL    COMMENT '中间表表名',
  TAGS_TEXT VARCHAR(200) NULL    COMMENT '标签',
  STATUS INTEGER NOT NULL    COMMENT '状态',
  EXT_CONFIG VARCHAR(1000) NULL    COMMENT '扩展配置',
  VERSION INTEGER NOT NULL    COMMENT '数据版本',
  CREATED_BY VARCHAR(50) NOT NULL    COMMENT '创建人',
  CREATE_TIME TIMESTAMP NOT NULL  DEFAULT CURRENT_TIMESTAMP    COMMENT '创建时间',
  UPDATED_BY VARCHAR(50) NOT NULL    COMMENT '修改人',
  UPDATE_TIME TIMESTAMP NOT NULL  DEFAULT CURRENT_TIMESTAMP    COMMENT '修改时间',
  REMARK VARCHAR(200) NULL    COMMENT '备注',
  constraint PK_nop_dyn_entity_relation_meta primary key (REL_META_ID)
);

CREATE TABLE nop_dyn_function_meta(
  FUNC_META_ID VARCHAR(32) NOT NULL    COMMENT '函数定义ID',
  ENTITY_META_ID VARCHAR(32) NOT NULL    COMMENT '实体定义ID',
  NAME VARCHAR(50) NOT NULL    COMMENT '函数名',
  DISPLAY_NAME VARCHAR(100) NOT NULL    COMMENT '显示名',
  FUNCTION_TYPE VARCHAR(10) NOT NULL    COMMENT '函数类型',
  RETURN_TYPE VARCHAR(100) NULL    COMMENT '返回类型',
  RETURN_GQL_TYPE VARCHAR(100) NULL    COMMENT 'GraphQL返回类型',
  STATUS INTEGER NOT NULL    COMMENT '状态',
  TAGS_TEXT VARCHAR(200) NULL    COMMENT '标签',
  FUNC_META VARCHAR(4000) NULL    COMMENT '函数元数据',
  SOURCE VARCHAR(4000) NOT NULL    COMMENT '源码',
  VERSION INTEGER NOT NULL    COMMENT '数据版本',
  CREATED_BY VARCHAR(50) NOT NULL    COMMENT '创建人',
  CREATE_TIME TIMESTAMP NOT NULL  DEFAULT CURRENT_TIMESTAMP    COMMENT '创建时间',
  UPDATED_BY VARCHAR(50) NOT NULL    COMMENT '修改人',
  UPDATE_TIME TIMESTAMP NOT NULL  DEFAULT CURRENT_TIMESTAMP    COMMENT '修改时间',
  REMARK VARCHAR(200) NULL    COMMENT '备注',
  constraint PK_nop_dyn_function_meta primary key (FUNC_META_ID)
);


   ALTER TABLE nop_dyn_app COMMENT '应用定义';
                
   ALTER TABLE nop_dyn_module COMMENT '模块定义';
                
   ALTER TABLE nop_dyn_domain COMMENT '数据域';
                
   ALTER TABLE nop_dyn_entity COMMENT '动态实体';
                
   ALTER TABLE nop_dyn_entity_relation COMMENT '实体关联';
                
   ALTER TABLE nop_dyn_module_dep COMMENT '模块依赖';
                
   ALTER TABLE nop_dyn_app_module COMMENT '应用模块映射';
                
   ALTER TABLE nop_dyn_sql COMMENT 'SQL定义';
                
   ALTER TABLE nop_dyn_file COMMENT '模块文件';
                
   ALTER TABLE nop_dyn_page COMMENT '页面定义';
                
   ALTER TABLE nop_dyn_entity_meta COMMENT '实体元数据';
                
   ALTER TABLE nop_dyn_prop_meta COMMENT '属性元数据';
                
   ALTER TABLE nop_dyn_entity_relation_meta COMMENT '实体关联元数据';
                
   ALTER TABLE nop_dyn_function_meta COMMENT '实体函数定义';
                
