
CREATE TABLE nop_oauth_authorization(
  SID VARCHAR(100) NOT NULL    COMMENT 'Id',
  REGISTERED_CLIENT_ID VARCHAR(100) NOT NULL    COMMENT '客户端ID',
  PRINCIPAL_NAME VARCHAR(200) NOT NULL    COMMENT '客户端名称',
  AUTHORIZATION_GRANT_TYPE VARCHAR(100) NOT NULL    COMMENT '授权类型',
  AUTHORIZED_SCOPES VARCHAR(1000) NULL    COMMENT '授权范围',
  ATTRIBUTES TEXT NULL    COMMENT '扩展属性',
  STATE VARCHAR(500) NULL    COMMENT '状态码',
  AUTHORIZATION_CODE_VALUE TEXT NULL    COMMENT 'AuthorizationCode值',
  AUTHORIZATION_CODE_ISSUED_AT TIMESTAMP NULL    COMMENT 'AuthorizationCode发放时间',
  AUTHORIZATION_CODE_EXPIRES_AT TIMESTAMP NULL    COMMENT 'AuthorizationCode过期使劲按',
  AUTHORIZATION_CODE_METADATA TEXT NULL    COMMENT 'AuthorizationCode元数据',
  ACCESS_TOKEN_VALUE TEXT NULL    COMMENT 'AccessToken',
  ACCESS_TOKEN_ISSUED_AT TIMESTAMP NULL    COMMENT 'AccessToken发放时间',
  ACCESS_TOKEN_EXPIRES_AT TIMESTAMP NULL    COMMENT 'AccessToken过期时间',
  ACCESS_TOKEN_METADATA TEXT NULL    COMMENT 'AccessToken元数据',
  ACCESS_TOKEN_TYPE VARCHAR(100) NULL    COMMENT 'AccessToken类型',
  ACCESS_TOKEN_SCOPES VARCHAR(1000) NULL    COMMENT 'AccessToken权限范围',
  OIDC_ID_TOKEN_VALUE TEXT NULL    COMMENT 'OidcIdToken值',
  OIDC_ID_TOKEN_ISSUED_AT TIMESTAMP NULL    COMMENT 'OidcIdToken发放时间',
  OIDC_ID_TOKEN_EXPIRES_AT TIMESTAMP NULL    COMMENT 'OidcIdToken过期时间',
  OIDC_ID_TOKEN_METADATA TEXT NULL    COMMENT 'OidcIdToken元数据',
  REFRESH_TOKEN_VALUE TEXT NULL    COMMENT 'RefreshToken值',
  REFRESH_TOKEN_ISSUED_AT TIMESTAMP NULL    COMMENT 'RefreshToken发放时间',
  REFRESH_TOKEN_EXPIRES_AT TIMESTAMP NULL    COMMENT 'RefreshToken过期时间',
  REFRESH_TOKEN_METADATA TEXT NULL    COMMENT 'RefreshToken元数据',
  USER_CODE_VALUE TEXT NULL    COMMENT 'UserCode值',
  USER_CODE_ISSUED_AT TIMESTAMP NULL    COMMENT 'UserCode发放时间',
  USER_CODE_EXPIRES_AT TIMESTAMP NULL    COMMENT 'UserCode过期时间',
  USER_CODE_METADATA TEXT NULL    COMMENT 'UserCode元数据',
  DEVICE_CODE_VALUE TEXT NULL    COMMENT 'DeviceCode值',
  DEVICE_CODE_ISSUED_AT TIMESTAMP NULL    COMMENT 'DeviceCode发放时间',
  DEVICE_CODE_EXPIRES_AT TIMESTAMP NULL    COMMENT 'DeviceCode过期时间',
  DEVICE_CODE_METADATA TEXT NULL    COMMENT 'DeviceCode元数据',
  constraint PK_nop_oauth_authorization primary key (SID)
);

CREATE TABLE nop_oauth_authorization_consent(
  REGISTERED_CLIENT_ID VARCHAR(100) NOT NULL    COMMENT '注册客户端ID',
  PRINCIPAL_NAME VARCHAR(200) NOT NULL    COMMENT '客户端名称',
  AUTHORITIES VARCHAR(1000) NOT NULL    COMMENT '扩展属性',
  constraint PK_nop_oauth_authorization_consent primary key (REGISTERED_CLIENT_ID,PRINCIPAL_NAME)
);

CREATE TABLE nop_oauth_registered_client(
  SID VARCHAR(100) NOT NULL    COMMENT 'Id',
  CLIENT_ID VARCHAR(100) NOT NULL    COMMENT '客户端ID',
  CLIENT_ID_ISSUED_AT TIMESTAMP NOT NULL  DEFAULT CURRENT_TIMESTAMP    COMMENT '客户端ID发放时间',
  CLIENT_SECRET VARCHAR(200) NULL    COMMENT '客户端密码',
  CLIENT_SECRET_EXPIRES_AT TIMESTAMP NULL    COMMENT '客户端密码过期时间',
  CLIENT_NAME VARCHAR(200) NOT NULL    COMMENT '客户端名称',
  CLIENT_AUTHENTICATION_METHODS VARCHAR(1000) NOT NULL    COMMENT '客户端授权方法',
  AUTHORIZATION_GRANT_TYPES VARCHAR(1000) NOT NULL    COMMENT '客户端认证类型',
  REDIRECT_URIS VARCHAR(1000) NULL    COMMENT '重定向URI',
  POST_LOGOUT_REDIRECT_URIS VARCHAR(1000) NULL    COMMENT 'Logout重定向URI',
  SCOPES VARCHAR(1000) NOT NULL    COMMENT '授权范围',
  CLIENT_SETTINGS VARCHAR(2000) NOT NULL    COMMENT '客户端设置',
  TOKEN_SETTINGS VARCHAR(2000) NOT NULL    COMMENT 'Token设置',
  constraint PK_nop_oauth_registered_client primary key (SID)
);


   ALTER TABLE nop_oauth_authorization COMMENT 'Oauth认证记录';
                
   ALTER TABLE nop_oauth_authorization_consent COMMENT 'Oauth许可';
                
   ALTER TABLE nop_oauth_registered_client COMMENT 'Oauth注册客户端';
                
