
CREATE TABLE nop_meta_module(
  META_MODULE_ID VARCHAR(32) NOT NULL    COMMENT '模块版本ID',
  MODULE_ID VARCHAR(100) NOT NULL    COMMENT '模块标识',
  MODULE_NAME VARCHAR(100) NOT NULL    COMMENT '模块名',
  DISPLAY_NAME VARCHAR(200) NULL    COMMENT '显示名',
  VERSION BIGINT NOT NULL    COMMENT '模块版本号',
  BASE_MODULE_ID VARCHAR(32) NULL    COMMENT '基线模块版本ID',
  STATUS LONGTEXT NOT NULL    COMMENT '模块状态',
  MAVEN_GROUP_ID VARCHAR(100) NULL    COMMENT 'Maven GroupId',
  MAVEN_ARTIFACT_ID VARCHAR(100) NULL    COMMENT 'Maven ArtifactId',
  MAVEN_VERSION VARCHAR(50) NULL    COMMENT 'Maven版本',
  GIT_REPO_PATH VARCHAR(500) NULL    COMMENT 'Git仓库路径',
  GIT_BRANCH VARCHAR(100) NULL    COMMENT 'Git分支',
  GIT_COMMIT_ID VARCHAR(64) NULL    COMMENT 'Git提交',
  IMPORTED_AT DATETIME(3) NULL    COMMENT '导入时间',
  EXT_CONFIG VARCHAR(4000) NULL    COMMENT '扩展配置',
  DEL_VERSION BIGINT NOT NULL    COMMENT '数据版本',
  CREATED_BY VARCHAR(50) NOT NULL    COMMENT '创建人',
  CREATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '创建时间',
  UPDATED_BY VARCHAR(50) NOT NULL    COMMENT '修改人',
  UPDATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '修改时间',
  REMARK VARCHAR(200) NULL    COMMENT '备注',
  constraint PK_nop_meta_module primary key (META_MODULE_ID)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs;

CREATE TABLE nop_meta_data_source(
  DATA_SOURCE_ID VARCHAR(32) NOT NULL    COMMENT '数据源ID',
  QUERY_SPACE VARCHAR(100) NOT NULL    COMMENT '查询空间',
  NAME VARCHAR(100) NOT NULL    COMMENT '名称',
  DISPLAY_NAME VARCHAR(200) NULL    COMMENT '显示名',
  DATASOURCE_TYPE VARCHAR(30) NOT NULL    COMMENT '数据源类型',
  CONNECTION_CONFIG VARCHAR(4000) NULL    COMMENT '连接配置',
  STATUS LONGTEXT NOT NULL    COMMENT '状态',
  DEL_VERSION BIGINT NOT NULL    COMMENT '数据版本',
  CREATED_BY VARCHAR(50) NOT NULL    COMMENT '创建人',
  CREATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '创建时间',
  UPDATED_BY VARCHAR(50) NOT NULL    COMMENT '修改人',
  UPDATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '修改时间',
  REMARK VARCHAR(200) NULL    COMMENT '备注',
  constraint PK_nop_meta_data_source primary key (DATA_SOURCE_ID)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs;

CREATE TABLE nop_meta_semantic_type(
  SEMANTIC_TYPE_ID VARCHAR(32) NOT NULL    COMMENT '语义类型ID',
  TYPE_NAME VARCHAR(50) NOT NULL    COMMENT '类型名',
  DISPLAY_NAME VARCHAR(200) NULL    COMMENT '显示名',
  DESCRIPTION VARCHAR(1000) NULL    COMMENT '描述',
  APPLICABLE_TO VARCHAR(1000) NULL    COMMENT '适用数据类型',
  EXT_CONFIG VARCHAR(4000) NULL    COMMENT '扩展配置',
  DEL_VERSION BIGINT NOT NULL    COMMENT '数据版本',
  CREATED_BY VARCHAR(50) NOT NULL    COMMENT '创建人',
  CREATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '创建时间',
  UPDATED_BY VARCHAR(50) NOT NULL    COMMENT '修改人',
  UPDATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '修改时间',
  REMARK VARCHAR(200) NULL    COMMENT '备注',
  constraint PK_nop_meta_semantic_type primary key (SEMANTIC_TYPE_ID)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs;

CREATE TABLE nop_meta_lineage_edge(
  LINEAGE_EDGE_ID VARCHAR(32) NOT NULL    COMMENT '血缘边ID',
  SOURCE_TABLE_ID VARCHAR(32) NOT NULL    COMMENT '源表ID',
  TARGET_TABLE_ID VARCHAR(32) NOT NULL    COMMENT '目标表ID',
  SOURCE_COLUMN VARCHAR(100) NULL    COMMENT '源列名',
  TARGET_COLUMN VARCHAR(100) NULL    COMMENT '目标列名',
  TRANSFORM_TYPE VARCHAR(20) NULL    COMMENT '转换类型',
  TRANSFORM_EXPR VARCHAR(1000) NULL    COMMENT '转换表达式',
  LINEAGE_SOURCE VARCHAR(30) NULL    COMMENT '血缘来源',
  PIPELINE_ID VARCHAR(32) NULL    COMMENT '管道ID',
  CONFIDENCE DOUBLE NULL    COMMENT '置信度',
  EXT_CONFIG VARCHAR(4000) NULL    COMMENT '扩展配置',
  DEL_VERSION BIGINT NOT NULL    COMMENT '数据版本',
  CREATED_BY VARCHAR(50) NOT NULL    COMMENT '创建人',
  CREATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '创建时间',
  UPDATED_BY VARCHAR(50) NOT NULL    COMMENT '修改人',
  UPDATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '修改时间',
  REMARK VARCHAR(200) NULL    COMMENT '备注',
  constraint PK_nop_meta_lineage_edge primary key (LINEAGE_EDGE_ID)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs;

CREATE TABLE nop_meta_quality_rule(
  QUALITY_RULE_ID VARCHAR(32) NOT NULL    COMMENT '规则ID',
  RULE_NAME VARCHAR(100) NOT NULL    COMMENT '规则名',
  DISPLAY_NAME VARCHAR(200) NULL    COMMENT '显示名',
  RULE_TYPE VARCHAR(30) NOT NULL    COMMENT '规则类型',
  ENTITY_TYPE VARCHAR(20) NOT NULL    COMMENT '对象类型',
  ENTITY_ID VARCHAR(32) NOT NULL    COMMENT '挂载对象ID',
  SEVERITY LONGTEXT NOT NULL    COMMENT '严重级别',
  SQL_EXPRESSION LONGTEXT NULL    COMMENT 'SQL表达式',
  THRESHOLD DOUBLE NULL    COMMENT '阈值',
  PARAMS VARCHAR(4000) NULL    COMMENT '参数',
  EXT_CONFIG VARCHAR(4000) NULL    COMMENT '扩展配置',
  DEL_VERSION BIGINT NOT NULL    COMMENT '数据版本',
  CREATED_BY VARCHAR(50) NOT NULL    COMMENT '创建人',
  CREATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '创建时间',
  UPDATED_BY VARCHAR(50) NOT NULL    COMMENT '修改人',
  UPDATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '修改时间',
  REMARK VARCHAR(200) NULL    COMMENT '备注',
  constraint PK_nop_meta_quality_rule primary key (QUALITY_RULE_ID)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs;

CREATE TABLE nop_meta_orm_model(
  ORM_MODEL_ID VARCHAR(32) NOT NULL    COMMENT '模型ID',
  META_MODULE_ID VARCHAR(32) NOT NULL    COMMENT '模块版本ID',
  MODEL_NAME VARCHAR(100) NOT NULL    COMMENT '模型名',
  IS_DELTA TINYINT default 0  NOT NULL    COMMENT '是否Delta',
  SOURCE_CONTENT LONGTEXT NULL    COMMENT '原始内容',
  IMPORTED_AT DATETIME(3) NULL    COMMENT '导入时间',
  DEL_VERSION BIGINT NOT NULL    COMMENT '数据版本',
  CREATED_BY VARCHAR(50) NOT NULL    COMMENT '创建人',
  CREATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '创建时间',
  UPDATED_BY VARCHAR(50) NOT NULL    COMMENT '修改人',
  UPDATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '修改时间',
  REMARK VARCHAR(200) NULL    COMMENT '备注',
  constraint PK_nop_meta_orm_model primary key (ORM_MODEL_ID)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs;

CREATE TABLE nop_meta_table(
  META_TABLE_ID VARCHAR(32) NOT NULL    COMMENT '逻辑表ID',
  META_MODULE_ID VARCHAR(32) NOT NULL    COMMENT '模块版本ID',
  TABLE_NAME VARCHAR(100) NOT NULL    COMMENT '表名',
  DISPLAY_NAME VARCHAR(200) NULL    COMMENT '显示名',
  TABLE_TYPE VARCHAR(20) NOT NULL    COMMENT '表类型',
  QUERY_SPACE VARCHAR(100) NULL    COMMENT '查询空间',
  SOURCE_SQL LONGTEXT NULL    COMMENT '来源SQL',
  BASE_ENTITY_ID VARCHAR(32) NULL    COMMENT '主要实体ID',
  DESCRIPTION VARCHAR(1000) NULL    COMMENT '描述',
  BUILD_SQL LONGTEXT NULL    COMMENT '合成SQL',
  DEL_VERSION BIGINT NOT NULL    COMMENT '数据版本',
  CREATED_BY VARCHAR(50) NOT NULL    COMMENT '创建人',
  CREATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '创建时间',
  UPDATED_BY VARCHAR(50) NOT NULL    COMMENT '修改人',
  UPDATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '修改时间',
  REMARK VARCHAR(200) NULL    COMMENT '备注',
  constraint PK_nop_meta_table primary key (META_TABLE_ID)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs;

CREATE TABLE nop_meta_pipeline(
  PIPELINE_ID VARCHAR(32) NOT NULL    COMMENT '管道ID',
  META_MODULE_ID VARCHAR(32) NOT NULL    COMMENT '模块版本ID',
  PIPELINE_NAME VARCHAR(100) NOT NULL    COMMENT '管道名',
  DISPLAY_NAME VARCHAR(200) NULL    COMMENT '显示名',
  PIPELINE_TYPE VARCHAR(20) NOT NULL    COMMENT '管道类型',
  SOURCE_SQL LONGTEXT NULL    COMMENT '处理SQL',
  SCHEDULE VARCHAR(200) NULL    COMMENT '调度表达式',
  EXT_CONFIG VARCHAR(4000) NULL    COMMENT '扩展配置',
  DEL_VERSION BIGINT NOT NULL    COMMENT '数据版本',
  CREATED_BY VARCHAR(50) NOT NULL    COMMENT '创建人',
  CREATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '创建时间',
  UPDATED_BY VARCHAR(50) NOT NULL    COMMENT '修改人',
  UPDATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '修改时间',
  REMARK VARCHAR(200) NULL    COMMENT '备注',
  constraint PK_nop_meta_pipeline primary key (PIPELINE_ID)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs;

CREATE TABLE nop_meta_quality_result(
  QUALITY_RESULT_ID VARCHAR(32) NOT NULL    COMMENT '结果ID',
  QUALITY_RULE_ID VARCHAR(32) NOT NULL    COMMENT '规则ID',
  EXECUTE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '执行时间',
  STATUS LONGTEXT NOT NULL    COMMENT '状态',
  ACTUAL_VALUE DOUBLE NULL    COMMENT '实际值',
  EXPECTED_VALUE DOUBLE NULL    COMMENT '期望值',
  MESSAGE VARCHAR(1000) NULL    COMMENT '结果描述',
  DETAILS VARCHAR(4000) NULL    COMMENT '详情',
  DEL_VERSION BIGINT NOT NULL    COMMENT '数据版本',
  CREATED_BY VARCHAR(50) NOT NULL    COMMENT '创建人',
  CREATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '创建时间',
  UPDATED_BY VARCHAR(50) NOT NULL    COMMENT '修改人',
  UPDATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '修改时间',
  REMARK VARCHAR(200) NULL    COMMENT '备注',
  constraint PK_nop_meta_quality_result primary key (QUALITY_RESULT_ID)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs;

CREATE TABLE nop_meta_entity(
  META_ENTITY_ID VARCHAR(32) NOT NULL    COMMENT '实体ID',
  ORM_MODEL_ID VARCHAR(32) NOT NULL    COMMENT '模型ID',
  IS_DELTA TINYINT default 0  NOT NULL    COMMENT '是否Delta',
  ENTITY_NAME VARCHAR(200) NOT NULL    COMMENT '实体名',
  TABLE_NAME VARCHAR(100) NULL    COMMENT '表名',
  DISPLAY_NAME VARCHAR(200) NULL    COMMENT '显示名',
  CLASS_NAME VARCHAR(300) NULL    COMMENT '类名',
  TAG_SET VARCHAR(500) NULL    COMMENT '标签集',
  QUERY_SPACE VARCHAR(100) NULL    COMMENT '查询空间',
  PERSIST_DRIVER VARCHAR(50) NULL    COMMENT '持久化驱动',
  USE_TENANT TINYINT default 0  NULL    COMMENT '使用租户',
  USE_REVISION TINYINT default 0  NULL    COMMENT '使用版本',
  USE_LOGICAL_DELETE TINYINT default 0  NULL    COMMENT '逻辑删除',
  NOT_GEN_CODE TINYINT default 0  NULL    COMMENT '不生成代码',
  CREATER_PROP VARCHAR(50) NULL    COMMENT '创建人属性',
  CREATE_TIME_PROP VARCHAR(50) NULL    COMMENT '创建时间属性',
  UPDATER_PROP VARCHAR(50) NULL    COMMENT '修改人属性',
  UPDATE_TIME_PROP VARCHAR(50) NULL    COMMENT '修改时间属性',
  VERSION_PROP VARCHAR(50) NULL    COMMENT '版本属性',
  DEL_FLAG_PROP VARCHAR(50) NULL    COMMENT '删除标记属性',
  DEL_VERSION_PROP VARCHAR(50) NULL    COMMENT '删除版本属性',
  DB_CATALOG VARCHAR(100) NULL    COMMENT '数据库目录',
  DB_SCHEMA VARCHAR(100) NULL    COMMENT '数据库Schema',
  EXT_CONFIG VARCHAR(4000) NULL    COMMENT '扩展配置',
  DEL_VERSION BIGINT NOT NULL    COMMENT '数据版本',
  CREATED_BY VARCHAR(50) NOT NULL    COMMENT '创建人',
  CREATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '创建时间',
  UPDATED_BY VARCHAR(50) NOT NULL    COMMENT '修改人',
  UPDATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '修改时间',
  REMARK VARCHAR(200) NULL    COMMENT '备注',
  constraint PK_nop_meta_entity primary key (META_ENTITY_ID)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs;

CREATE TABLE nop_meta_domain(
  META_DOMAIN_ID VARCHAR(32) NOT NULL    COMMENT '域ID',
  ORM_MODEL_ID VARCHAR(32) NOT NULL    COMMENT '模型ID',
  IS_DELTA TINYINT default 0  NOT NULL    COMMENT '是否Delta',
  DOMAIN_NAME VARCHAR(100) NOT NULL    COMMENT '域名',
  DISPLAY_NAME VARCHAR(200) NULL    COMMENT '显示名',
  DESCRIPTION VARCHAR(1000) NULL    COMMENT '描述',
  STD_DOMAIN VARCHAR(100) NULL    COMMENT '标准域',
  STD_DATA_TYPE VARCHAR(30) NULL    COMMENT '数据类型',
  STD_SQL_TYPE VARCHAR(30) NULL    COMMENT 'SQL类型',
  `PRECISION` INTEGER NULL    COMMENT '精度',
  SCALE INTEGER NULL    COMMENT '标度',
  VALIDATION_PATTERN VARCHAR(500) NULL    COMMENT '校验正则',
  DEFAULT_VALUE VARCHAR(500) NULL    COMMENT '默认值',
  IS_GLOBAL TINYINT default 0  NULL    COMMENT '全局通用域',
  SOURCE_MODULE_ID VARCHAR(32) NULL    COMMENT '来源模块版本ID',
  TAG_SET VARCHAR(500) NULL    COMMENT '标签集',
  EXT_CONFIG VARCHAR(4000) NULL    COMMENT '扩展配置',
  DEL_VERSION BIGINT NOT NULL    COMMENT '数据版本',
  CREATED_BY VARCHAR(50) NOT NULL    COMMENT '创建人',
  CREATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '创建时间',
  UPDATED_BY VARCHAR(50) NOT NULL    COMMENT '修改人',
  UPDATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '修改时间',
  REMARK VARCHAR(200) NULL    COMMENT '备注',
  constraint PK_nop_meta_domain primary key (META_DOMAIN_ID)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs;

CREATE TABLE nop_meta_dict(
  META_DICT_ID VARCHAR(32) NOT NULL    COMMENT '字典ID',
  ORM_MODEL_ID VARCHAR(32) NOT NULL    COMMENT '模型ID',
  IS_DELTA TINYINT default 0  NOT NULL    COMMENT '是否Delta',
  DICT_NAME VARCHAR(100) NOT NULL    COMMENT '字典名',
  LABEL VARCHAR(200) NULL    COMMENT '字典标签',
  VALUE_TYPE VARCHAR(20) NULL    COMMENT '值类型',
  LOCALE VARCHAR(20) NULL    COMMENT '区域',
  IS_STATIC TINYINT default 0  NULL    COMMENT '静态字典',
  NORMALIZED TINYINT default 0  NULL    COMMENT '已标准化',
  DEPRECATED TINYINT default 0  NULL    COMMENT '已废弃',
  INTERNAL TINYINT default 0  NULL    COMMENT '内部使用',
  TAG_SET VARCHAR(500) NULL    COMMENT '标签集',
  DEL_VERSION BIGINT NOT NULL    COMMENT '数据版本',
  CREATED_BY VARCHAR(50) NOT NULL    COMMENT '创建人',
  CREATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '创建时间',
  UPDATED_BY VARCHAR(50) NOT NULL    COMMENT '修改人',
  UPDATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '修改时间',
  REMARK VARCHAR(200) NULL    COMMENT '备注',
  constraint PK_nop_meta_dict primary key (META_DICT_ID)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs;

CREATE TABLE nop_meta_table_dimension(
  DIMENSION_ID VARCHAR(32) NOT NULL    COMMENT '维度ID',
  META_TABLE_ID VARCHAR(32) NOT NULL    COMMENT '逻辑表ID',
  DIMENSION_NAME VARCHAR(100) NOT NULL    COMMENT '维度名',
  DISPLAY_NAME VARCHAR(200) NULL    COMMENT '显示名',
  ENTITY_FIELD_ID VARCHAR(32) NULL    COMMENT '实体字段ID',
  DIMENSION_TYPE VARCHAR(30) NULL    COMMENT '维度类型',
  GRANULARITY VARCHAR(20) NULL    COMMENT '时间粒度',
  FORMAT VARCHAR(100) NULL    COMMENT '显示格式',
  SORT_ORDER INTEGER NULL    COMMENT '排序',
  EXT_CONFIG VARCHAR(4000) NULL    COMMENT '扩展配置',
  DEL_VERSION BIGINT NOT NULL    COMMENT '数据版本',
  CREATED_BY VARCHAR(50) NOT NULL    COMMENT '创建人',
  CREATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '创建时间',
  UPDATED_BY VARCHAR(50) NOT NULL    COMMENT '修改人',
  UPDATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '修改时间',
  REMARK VARCHAR(200) NULL    COMMENT '备注',
  constraint PK_nop_meta_table_dimension primary key (DIMENSION_ID)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs;

CREATE TABLE nop_meta_table_measure(
  MEASURE_ID VARCHAR(32) NOT NULL    COMMENT '指标ID',
  META_TABLE_ID VARCHAR(32) NOT NULL    COMMENT '逻辑表ID',
  MEASURE_NAME VARCHAR(100) NOT NULL    COMMENT '指标名',
  DISPLAY_NAME VARCHAR(200) NULL    COMMENT '显示名',
  ENTITY_FIELD_ID VARCHAR(32) NULL    COMMENT '实体字段ID',
  AGG_FUNC VARCHAR(30) NULL    COMMENT '聚合函数',
  EXPRESSION VARCHAR(1000) NULL    COMMENT '表达式',
  FORMAT VARCHAR(100) NULL    COMMENT '显示格式',
  CURRENCY_UNIT VARCHAR(20) NULL    COMMENT '货币单位',
  DESCRIPTION VARCHAR(1000) NULL    COMMENT '描述',
  EXT_CONFIG VARCHAR(4000) NULL    COMMENT '扩展配置',
  DEL_VERSION BIGINT NOT NULL    COMMENT '数据版本',
  CREATED_BY VARCHAR(50) NOT NULL    COMMENT '创建人',
  CREATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '创建时间',
  UPDATED_BY VARCHAR(50) NOT NULL    COMMENT '修改人',
  UPDATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '修改时间',
  REMARK VARCHAR(200) NULL    COMMENT '备注',
  constraint PK_nop_meta_table_measure primary key (MEASURE_ID)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs;

CREATE TABLE nop_meta_table_filter(
  FILTER_ID VARCHAR(32) NOT NULL    COMMENT '过滤器ID',
  META_TABLE_ID VARCHAR(32) NOT NULL    COMMENT '逻辑表ID',
  FILTER_NAME VARCHAR(100) NOT NULL    COMMENT '过滤器名',
  DISPLAY_NAME VARCHAR(200) NULL    COMMENT '显示名',
  DEFINITION VARCHAR(4000) NOT NULL    COMMENT '筛选条件',
  DESCRIPTION VARCHAR(1000) NULL    COMMENT '描述',
  IS_DEFAULT TINYINT default 0  NULL    COMMENT '默认过滤器',
  EXT_CONFIG VARCHAR(4000) NULL    COMMENT '扩展配置',
  DEL_VERSION BIGINT NOT NULL    COMMENT '数据版本',
  CREATED_BY VARCHAR(50) NOT NULL    COMMENT '创建人',
  CREATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '创建时间',
  UPDATED_BY VARCHAR(50) NOT NULL    COMMENT '修改人',
  UPDATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '修改时间',
  REMARK VARCHAR(200) NULL    COMMENT '备注',
  constraint PK_nop_meta_table_filter primary key (FILTER_ID)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs;

CREATE TABLE nop_meta_entity_field(
  ENTITY_FIELD_ID VARCHAR(32) NOT NULL    COMMENT '字段ID',
  META_ENTITY_ID VARCHAR(32) NOT NULL    COMMENT '实体ID',
  IS_DELTA TINYINT default 0  NOT NULL    COMMENT '是否Delta',
  FIELD_NAME VARCHAR(100) NOT NULL    COMMENT '属性名',
  COLUMN_CODE VARCHAR(100) NULL    COMMENT '列名',
  PROP_ID INTEGER NULL    COMMENT '属性序号',
  STD_DATA_TYPE VARCHAR(30) NULL    COMMENT '数据类型',
  STD_SQL_TYPE VARCHAR(30) NULL    COMMENT 'SQL类型',
  `PRECISION` INTEGER NULL    COMMENT '精度',
  SCALE INTEGER NULL    COMMENT '标度',
  MANDATORY TINYINT default 0  NULL    COMMENT '必填',
  `PRIMARY` TINYINT default 0  NULL    COMMENT '主键',
  LAZY TINYINT default 0  NULL    COMMENT '懒加载',
  INSERTABLE TINYINT default 0  NULL    COMMENT '可插入',
  UPDATABLE TINYINT default 0  NULL    COMMENT '可更新',
  DOMAIN VARCHAR(100) NULL    COMMENT '域',
  STD_DOMAIN VARCHAR(100) NULL    COMMENT '标准域',
  FIXED_VALUE VARCHAR(500) NULL    COMMENT '固定值',
  DEFAULT_VALUE VARCHAR(500) NULL    COMMENT '默认值',
  SEMANTIC_TYPE VARCHAR(50) NULL    COMMENT '语义类型',
  TAG_SET VARCHAR(500) NULL    COMMENT '标签集',
  DISPLAY_NAME VARCHAR(200) NULL    COMMENT '显示名',
  COMMENT VARCHAR(1000) NULL    COMMENT '注释',
  NATIVE_SQL_TYPE VARCHAR(100) NULL    COMMENT '原生SQL类型',
  EXT_CONFIG VARCHAR(4000) NULL    COMMENT '扩展配置',
  DEL_VERSION BIGINT NOT NULL    COMMENT '数据版本',
  CREATED_BY VARCHAR(50) NOT NULL    COMMENT '创建人',
  CREATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '创建时间',
  UPDATED_BY VARCHAR(50) NOT NULL    COMMENT '修改人',
  UPDATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '修改时间',
  REMARK VARCHAR(200) NULL    COMMENT '备注',
  constraint PK_nop_meta_entity_field primary key (ENTITY_FIELD_ID)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs;

CREATE TABLE nop_meta_entity_relation(
  RELATION_ID VARCHAR(32) NOT NULL    COMMENT '关系ID',
  META_ENTITY_ID VARCHAR(32) NOT NULL    COMMENT '实体ID',
  IS_DELTA TINYINT default 0  NOT NULL    COMMENT '是否Delta',
  RELATION_NAME VARCHAR(100) NOT NULL    COMMENT '关系名',
  RELATION_TYPE VARCHAR(20) NOT NULL    COMMENT '关系类型',
  REF_ENTITY_NAME VARCHAR(200) NULL    COMMENT '引用实体名',
  REF_PROP_NAME VARCHAR(100) NULL    COMMENT '引用属性名',
  CASCADE_DELETE TINYINT default 0  NULL    COMMENT '级联删除',
  AUTO_CASCADE_DELETE TINYINT default 0  NULL    COMMENT '自动级联删除',
  QUERYABLE TINYINT default 0  NULL    COMMENT '可查询',
  EMBEDDED TINYINT default 0  NULL    COMMENT '内嵌',
  NOT_GEN_CODE TINYINT default 0  NULL    COMMENT '不生成代码',
  TAG_SET VARCHAR(500) NULL    COMMENT '标签集',
  JOIN_CONDITIONS VARCHAR(4000) NULL    COMMENT '关联条件',
  DEL_VERSION BIGINT NOT NULL    COMMENT '数据版本',
  CREATED_BY VARCHAR(50) NOT NULL    COMMENT '创建人',
  CREATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '创建时间',
  UPDATED_BY VARCHAR(50) NOT NULL    COMMENT '修改人',
  UPDATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '修改时间',
  REMARK VARCHAR(200) NULL    COMMENT '备注',
  constraint PK_nop_meta_entity_relation primary key (RELATION_ID)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs;

CREATE TABLE nop_meta_entity_unique_key(
  UNIQUE_KEY_ID VARCHAR(32) NOT NULL    COMMENT '唯一键ID',
  META_ENTITY_ID VARCHAR(32) NOT NULL    COMMENT '实体ID',
  IS_DELTA TINYINT default 0  NOT NULL    COMMENT '是否Delta',
  UK_NAME VARCHAR(100) NOT NULL    COMMENT '唯一键名',
  DISPLAY_NAME VARCHAR(200) NULL    COMMENT '显示名',
  COLUMNS VARCHAR(1000) NOT NULL    COMMENT '字段列表',
  `CONSTRAINT` VARCHAR(100) NULL    COMMENT '约束名',
  TAG_SET VARCHAR(500) NULL    COMMENT '标签集',
  DEL_VERSION BIGINT NOT NULL    COMMENT '数据版本',
  CREATED_BY VARCHAR(50) NOT NULL    COMMENT '创建人',
  CREATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '创建时间',
  UPDATED_BY VARCHAR(50) NOT NULL    COMMENT '修改人',
  UPDATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '修改时间',
  REMARK VARCHAR(200) NULL    COMMENT '备注',
  constraint PK_nop_meta_entity_unique_key primary key (UNIQUE_KEY_ID)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs;

CREATE TABLE nop_meta_entity_index(
  INDEX_ID VARCHAR(32) NOT NULL    COMMENT '索引ID',
  META_ENTITY_ID VARCHAR(32) NOT NULL    COMMENT '实体ID',
  IS_DELTA TINYINT default 0  NOT NULL    COMMENT '是否Delta',
  INDEX_NAME VARCHAR(100) NOT NULL    COMMENT '索引名',
  DISPLAY_NAME VARCHAR(200) NULL    COMMENT '显示名',
  INDEX_TYPE VARCHAR(30) NULL    COMMENT '索引类型',
  `UNIQUE` TINYINT default 0  NULL    COMMENT '唯一索引',
  INDEX_COLUMNS VARCHAR(4000) NOT NULL    COMMENT '索引列',
  DEL_VERSION BIGINT NOT NULL    COMMENT '数据版本',
  CREATED_BY VARCHAR(50) NOT NULL    COMMENT '创建人',
  CREATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '创建时间',
  UPDATED_BY VARCHAR(50) NOT NULL    COMMENT '修改人',
  UPDATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '修改时间',
  REMARK VARCHAR(200) NULL    COMMENT '备注',
  constraint PK_nop_meta_entity_index primary key (INDEX_ID)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs;

CREATE TABLE nop_meta_table_join(
  JOIN_ID VARCHAR(32) NOT NULL    COMMENT '关联ID',
  META_TABLE_ID VARCHAR(32) NOT NULL    COMMENT '逻辑表ID',
  JOIN_TYPE VARCHAR(20) NOT NULL    COMMENT '关联类型',
  LEFT_ENTITY_ID VARCHAR(32) NULL    COMMENT '左实体ID',
  RIGHT_ENTITY_ID VARCHAR(32) NULL    COMMENT '右实体ID',
  LEFT_FIELD VARCHAR(100) NULL    COMMENT '左关联字段',
  RIGHT_FIELD VARCHAR(100) NULL    COMMENT '右关联字段',
  ALIAS VARCHAR(100) NULL    COMMENT '右表别名',
  DEL_VERSION BIGINT NOT NULL    COMMENT '数据版本',
  CREATED_BY VARCHAR(50) NOT NULL    COMMENT '创建人',
  CREATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '创建时间',
  UPDATED_BY VARCHAR(50) NOT NULL    COMMENT '修改人',
  UPDATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '修改时间',
  REMARK VARCHAR(200) NULL    COMMENT '备注',
  constraint PK_nop_meta_table_join primary key (JOIN_ID)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs;

CREATE TABLE nop_meta_dict_item(
  DICT_ITEM_ID VARCHAR(32) NOT NULL    COMMENT '字典项ID',
  META_DICT_ID VARCHAR(32) NOT NULL    COMMENT '字典ID',
  ITEM_VALUE VARCHAR(100) NOT NULL    COMMENT '字典值',
  ITEM_LABEL VARCHAR(200) NULL    COMMENT '字典标签',
  ITEM_CODE VARCHAR(100) NULL    COMMENT '字典编码',
  ITEM_GROUP VARCHAR(100) NULL    COMMENT '分组',
  DESCRIPTION VARCHAR(1000) NULL    COMMENT '描述',
  SORT_ORDER INTEGER NULL    COMMENT '排序',
  DEPRECATED TINYINT default 0  NULL    COMMENT '已废弃',
  INTERNAL TINYINT default 0  NULL    COMMENT '内部使用',
  DEL_VERSION BIGINT NOT NULL    COMMENT '数据版本',
  CREATED_BY VARCHAR(50) NOT NULL    COMMENT '创建人',
  CREATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '创建时间',
  UPDATED_BY VARCHAR(50) NOT NULL    COMMENT '修改人',
  UPDATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '修改时间',
  REMARK VARCHAR(200) NULL    COMMENT '备注',
  constraint PK_nop_meta_dict_item primary key (DICT_ITEM_ID)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs;


   ALTER TABLE nop_meta_module COMMENT '元数据模块';
                
   ALTER TABLE nop_meta_data_source COMMENT '数据源';
                
   ALTER TABLE nop_meta_semantic_type COMMENT '语义类型';
                
   ALTER TABLE nop_meta_lineage_edge COMMENT '血缘边';
                
   ALTER TABLE nop_meta_quality_rule COMMENT '质量规则';
                
   ALTER TABLE nop_meta_orm_model COMMENT 'ORM模型';
                
   ALTER TABLE nop_meta_table COMMENT '逻辑表';
                
   ALTER TABLE nop_meta_pipeline COMMENT '数据管道';
                
   ALTER TABLE nop_meta_quality_result COMMENT '质量结果';
                
   ALTER TABLE nop_meta_entity COMMENT '元数据实体';
                
   ALTER TABLE nop_meta_domain COMMENT '域定义';
                
   ALTER TABLE nop_meta_dict COMMENT '元数据字典';
                
   ALTER TABLE nop_meta_table_dimension COMMENT '表维度';
                
   ALTER TABLE nop_meta_table_measure COMMENT '表指标';
                
   ALTER TABLE nop_meta_table_filter COMMENT '表过滤器';
                
   ALTER TABLE nop_meta_entity_field COMMENT '实体字段';
                
   ALTER TABLE nop_meta_entity_relation COMMENT '实体关系';
                
   ALTER TABLE nop_meta_entity_unique_key COMMENT '实体唯一键';
                
   ALTER TABLE nop_meta_entity_index COMMENT '实体索引';
                
   ALTER TABLE nop_meta_table_join COMMENT '表关联';
                
   ALTER TABLE nop_meta_dict_item COMMENT '字典项';
                
