CREATE TABLE nop_auth_mfa_trusted_device(
  SID VARCHAR(32) NOT NULL    COMMENT '主键',
  USER_ID VARCHAR(50) NOT NULL    COMMENT '用户ID',
  DEVICE_HASH VARCHAR(64) NOT NULL    COMMENT '设备指纹',
  DEVICE_NAME VARCHAR(100) NULL    COMMENT '设备名称',
  EXPIRE_AT DATETIME(3) NULL    COMMENT '到期时间',
  LAST_USED_AT DATETIME(3) NULL    COMMENT '最近使用时间',
  TENANT_ID VARCHAR(32) NULL    COMMENT '租户ID',
  CREATED_BY VARCHAR(50) NOT NULL    COMMENT '创建人',
  CREATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '创建时间',
  UPDATED_BY VARCHAR(50) NOT NULL    COMMENT '修改人',
  UPDATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '修改时间',
  constraint UK_NOP_AUTH_MFA_TRUSTED_DEVICE_UH unique (USER_ID,DEVICE_HASH),
  constraint PK_nop_auth_mfa_trusted_device primary key (SID)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs;

ALTER TABLE nop_auth_mfa_trusted_device COMMENT 'MFA可信设备';
