
CREATE TABLE nop_auth_mfa_credential(
  SID VARCHAR(32) NOT NULL    COMMENT '主键',
  USER_ID VARCHAR(50) NOT NULL    COMMENT '用户ID',
  CREDENTIAL_ID VARCHAR(1400) NOT NULL    COMMENT '凭证ID',
  PUBLIC_KEY VARCHAR(1000) NOT NULL    COMMENT 'COSE公钥',
  SIGN_COUNT BIGINT default 0  NULL    COMMENT '签名计数',
  TRANSPORTS VARCHAR(100) NULL    COMMENT '传输方式',
  NAME VARCHAR(100) NULL    COMMENT '设备名称',
  STATUS VARCHAR(20) default 'enabled'  NOT NULL    COMMENT '凭证状态',
  LAST_USED_AT DATETIME(3) NULL    COMMENT '最近使用时间',
  DEL_FLAG TINYINT NOT NULL    COMMENT '删除标识',
  VERSION INTEGER NOT NULL    COMMENT '数据版本',
  TENANT_ID VARCHAR(32) NULL    COMMENT '租户ID',
  CREATED_BY VARCHAR(50) NOT NULL    COMMENT '创建人',
  CREATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '创建时间',
  UPDATED_BY VARCHAR(50) NOT NULL    COMMENT '修改人',
  UPDATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '修改时间',
  REMARK VARCHAR(200) NULL    COMMENT '备注',
  constraint UK_NOP_AUTH_MFA_CREDENTIAL_CRED unique (CREDENTIAL_ID),
  constraint PK_nop_auth_mfa_credential primary key (SID)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs;

ALTER TABLE nop_auth_mfa_credential COMMENT 'WebAuthn凭证';
