CREATE TABLE nop_auth_email_code(
  CODE_KEY VARCHAR(100) NOT NULL    COMMENT '验证码Key',
  EMAIL VARCHAR(100) NULL    COMMENT '邮箱',
  CODE VARCHAR(20) NULL    COMMENT '验证码',
  EXPIRE_AT BIGINT NULL    COMMENT '过期时间',
  FAIL_COUNT INTEGER default 0  NULL    COMMENT '失败计数',
  CREATED_BY VARCHAR(50) NOT NULL    COMMENT '创建人',
  CREATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '创建时间',
  UPDATED_BY VARCHAR(50) NULL    COMMENT '修改人',
  UPDATE_TIME DATETIME(3) NULL    COMMENT '修改时间',
  constraint PK_nop_auth_email_code primary key (CODE_KEY)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs;

ALTER TABLE nop_auth_email_code COMMENT '邮件验证码';
