/**
 * Copyright (c) 2017-2024 Nop Platform. All rights reserved.
 * Author: canonical-entropy@163.com
 * Blog:   https://www.zhihu.com/people/canonical-entropy
 * Gitee:  https://gitee.com/entropy-cloud/nop-entropy
 * Github: https://github.com/entropy-cloud/nop-entropy
 */
package io.nop.db.migration.executor;

import io.nop.api.core.exceptions.NopException;
import io.nop.commons.util.StringHelper;
import io.nop.dao.dialect.IDialect;

import java.util.ArrayList;
import java.util.Collections;
import java.util.List;
import java.util.Locale;
import java.util.Set;

import static io.nop.db.migration.DbMigrationErrors.ARG_COLUMN_NAME;
import static io.nop.db.migration.DbMigrationErrors.ARG_DEFAULT_VALUE;
import static io.nop.db.migration.DbMigrationErrors.ARG_TABLE_NAME;
import static io.nop.db.migration.DbMigrationErrors.ERR_DB_MIGRATION_INVALID_DEFAULT_VALUE;

/**
 * Dialect-family helpers for the DDL generated by the change executors.
 *
 * <p>The executors previously hardcoded MySQL/H2/PostgreSQL syntax
 * (AUTO_INCREMENT, inline COMMENT, "ALTER COLUMN x TYPE y",
 * "DROP INDEX i ON t"), which made every other registered dialect fail with
 * a syntax error. This helper centralizes the per-family variants.
 */
final class DdlSyntax {

    /** Dialect families with distinct DDL syntax for the constructs used here. */
    static final String FAMILY_MYSQL = "mysql";
    static final String FAMILY_POSTGRES = "postgres";
    static final String FAMILY_ORACLE = "oracle";
    static final String FAMILY_MSSQL = "mssql";
    static final String FAMILY_H2 = "h2";
    static final String FAMILY_OTHER = "other";

    private static final Set<String> MYSQL_LIKE = Set.of("mysql", "mysql5.7", "mariadb");
    private static final Set<String> POSTGRES_LIKE = Set.of("postgresql", "postgis");

    private DdlSyntax() {
    }

    static String family(IDialect dialect) {
        if (dialect == null || dialect.getName() == null) {
            return FAMILY_OTHER;
        }
        String name = dialect.getName().toLowerCase(Locale.ROOT);
        if (MYSQL_LIKE.contains(name)) {
            return FAMILY_MYSQL;
        }
        if (POSTGRES_LIKE.contains(name)) {
            return FAMILY_POSTGRES;
        }
        switch (name) {
            case "oracle":
                return FAMILY_ORACLE;
            case "mssql":
                return FAMILY_MSSQL;
            case "h2":
            case "h2gis":
                return FAMILY_H2;
            default:
                return FAMILY_OTHER;
        }
    }

    /**
     * Auto-increment column clause. MySQL/H2 use AUTO_INCREMENT, PostgreSQL and
     * Oracle use the standard GENERATED ... AS IDENTITY form, SQL Server uses
     * IDENTITY(1,1). Dialects in the "other" family get no clause (the caller
     * still emits a valid type declaration).
     */
    static String autoIncrementClause(IDialect dialect) {
        switch (family(dialect)) {
            case FAMILY_MYSQL:
            case FAMILY_H2:
                return " AUTO_INCREMENT";
            case FAMILY_POSTGRES:
            case FAMILY_ORACLE:
                return " GENERATED BY DEFAULT AS IDENTITY";
            case FAMILY_MSSQL:
                return " IDENTITY(1,1)";
            default:
                return "";
        }
    }

    /**
     * Only the MySQL family supports the inline table/column COMMENT clause.
     * PostgreSQL/H2/Oracle need separate COMMENT ON statements.
     */
    static boolean supportsInlineComment(IDialect dialect) {
        return family(dialect) == FAMILY_MYSQL;
    }

    /**
     * COMMENT ON statements work on PostgreSQL/H2/Oracle. SQL Server has no
     * COMMENT syntax at all (comments would need sp_addextendedproperty), so
     * the remark is silently skipped there.
     */
    static boolean supportsCommentOn(IDialect dialect) {
        String family = family(dialect);
        return family == FAMILY_POSTGRES || family == FAMILY_H2 || family == FAMILY_ORACLE
            || family == FAMILY_OTHER;
    }

    static List<String> buildTableCommentSql(IDialect dialect, String tableName, String remark) {
        if (StringHelper.isBlank(remark) || !supportsCommentOn(dialect)) {
            return Collections.emptyList();
        }
        return Collections.singletonList(
            "COMMENT ON TABLE " + dialect.escapeSQLName(tableName) + " IS '" + escapeComment(remark) + "'");
    }

    static List<String> buildColumnCommentSql(IDialect dialect, String tableName, String columnName, String remark) {
        if (StringHelper.isBlank(remark) || !supportsCommentOn(dialect)) {
            return Collections.emptyList();
        }
        return Collections.singletonList("COMMENT ON COLUMN " + dialect.escapeSQLName(tableName)
            + "." + dialect.escapeSQLName(columnName) + " IS '" + escapeComment(remark) + "'");
    }

    static String escapeComment(String comment) {
        return comment.replace("'", "''");
    }

    /**
     * "ALTER TABLE t ADD COLUMN c ..." keyword: Oracle only accepts
     * "ADD (c ...)" without the COLUMN keyword.
     */
    static String addColumnPrefix(IDialect dialect) {
        return family(dialect) == FAMILY_ORACLE ? " ADD (" : " ADD COLUMN ";
    }

    static String addColumnSuffix(IDialect dialect) {
        return family(dialect) == FAMILY_ORACLE ? ")" : "";
    }

    /**
     * "DROP INDEX i ON t" is MySQL syntax; every other dialect drops the index
     * by name alone (PostgreSQL/H2/Oracle/MSSQL).
     */
    static boolean dropIndexNeedsOnTable(IDialect dialect) {
        return family(dialect) == FAMILY_MYSQL;
    }

    /**
     * Reject default values that could break out of the DDL statement:
     * line breaks, statement separators and SQL comment markers. This mirrors
     * the validation performed on the nop-dyn side for dynamically generated
     * models whose app.orm.xml is executed by this module.
     */
    static void checkDefaultValue(String defaultValue, String tableName, String columnName) {
        if (StringHelper.isEmpty(defaultValue)) {
            return;
        }
        if (defaultValue.indexOf('\n') >= 0 || defaultValue.indexOf('\r') >= 0
            || defaultValue.indexOf(';') >= 0
            || defaultValue.contains("--") || defaultValue.contains("/*")) {
            throw new NopException(ERR_DB_MIGRATION_INVALID_DEFAULT_VALUE)
                .param(ARG_DEFAULT_VALUE, defaultValue)
                .param(ARG_TABLE_NAME, tableName)
                .param(ARG_COLUMN_NAME, columnName);
        }
    }

    static List<String> of(String statement) {
        List<String> list = new ArrayList<>(1);
        list.add(statement);
        return list;
    }
}
