(program (class_declaration (modifiers) name: (identifier) body: (class_body (line_comment) (field_declaration (modifiers) type: (integral_type) declarator: (variable_declarator name: (identifier) value: (decimal_integer_literal))) (field_declaration (modifiers) type: (integral_type) declarator: (variable_declarator name: (identifier) value: (decimal_integer_literal))) (field_declaration (modifiers) type: (integral_type) declarator: (variable_declarator name: (identifier) value: (decimal_integer_literal))) (field_declaration (modifiers) type: (integral_type) declarator: (variable_declarator name: (identifier) value: (decimal_integer_literal))) (field_declaration (modifiers) type: (integral_type) declarator: (variable_declarator name: (identifier) value: (decimal_integer_literal))) (field_declaration (modifiers) type: (integral_type) declarator: (variable_declarator name: (identifier) value: (decimal_integer_literal))) (field_declaration (modifiers) type: (integral_type) declarator: (variable_declarator name: (identifier) value: (decimal_integer_literal))) (field_declaration (modifiers) type: (integral_type) declarator: (variable_declarator name: (identifier) value: (decimal_integer_literal))) (field_declaration (modifiers) type: (integral_type) declarator: (variable_declarator name: (identifier) value: (decimal_integer_literal))) (field_declaration (modifiers) type: (integral_type) declarator: (variable_declarator name: (identifier) value: (decimal_integer_literal))) (field_declaration (modifiers) type: (integral_type) declarator: (variable_declarator name: (identifier) value: (decimal_integer_literal))) (field_declaration (modifiers) type: (integral_type) declarator: (variable_declarator name: (identifier) value: (decimal_integer_literal))) (block_comment) (method_declaration (modifiers) type: (integral_type) name: (identifier) parameters: (formal_parameters (formal_parameter type: (integral_type) name: (identifier)) (formal_parameter type: (integral_type) name: (identifier)) (formal_parameter type: (integral_type) name: (identifier)) (formal_parameter type: (integral_type) name: (identifier)) (formal_parameter type: (integral_type) name: (identifier)) (formal_parameter type: (integral_type) name: (identifier)) (formal_parameter type: (integral_type) name: (identifier)) (formal_parameter type: (integral_type) name: (identifier)) (formal_parameter type: (integral_type) name: (identifier))) body: (block (return_statement (decimal_integer_literal)))))))
---
(program
  (class_declaration
    (modifiers)
    (identifier)
    (class_body
      (line_comment)
      (field_declaration
        (modifiers)
        (integral_type)
        (variable_declarator
          (identifier)
          (decimal_integer_literal)))
      (field_declaration
        (modifiers)
        (integral_type)
        (variable_declarator
          (identifier)
          (decimal_integer_literal)))
      (field_declaration
        (modifiers)
        (integral_type)
        (variable_declarator
          (identifier)
          (decimal_integer_literal)))
      (field_declaration
        (modifiers)
        (integral_type)
        (variable_declarator
          (identifier)
          (decimal_integer_literal)))
      (field_declaration
        (modifiers)
        (integral_type)
        (variable_declarator
          (identifier)
          (decimal_integer_literal)))
      (field_declaration
        (modifiers)
        (integral_type)
        (variable_declarator
          (identifier)
          (decimal_integer_literal)))
      (field_declaration
        (modifiers)
        (integral_type)
        (variable_declarator
          (identifier)
          (decimal_integer_literal)))
      (field_declaration
        (modifiers)
        (integral_type)
        (variable_declarator
          (identifier)
          (decimal_integer_literal)))
      (field_declaration
        (modifiers)
        (integral_type)
        (variable_declarator
          (identifier)
          (decimal_integer_literal)))
      (field_declaration
        (modifiers)
        (integral_type)
        (variable_declarator
          (identifier)
          (decimal_integer_literal)))
      (field_declaration
        (modifiers)
        (integral_type)
        (variable_declarator
          (identifier)
          (decimal_integer_literal)))
      (field_declaration
        (modifiers)
        (integral_type)
        (variable_declarator
          (identifier)
          (decimal_integer_literal)))
      (block_comment)
      (method_declaration
        (modifiers)
        (integral_type)
        (identifier)
        (formal_parameters
          (formal_parameter
            (integral_type)
            (identifier))
          (formal_parameter
            (integral_type)
            (identifier))
          (formal_parameter
            (integral_type)
            (identifier))
          (formal_parameter
            (integral_type)
            (identifier))
          (formal_parameter
            (integral_type)
            (identifier))
          (formal_parameter
            (integral_type)
            (identifier))
          (formal_parameter
            (integral_type)
            (identifier))
          (formal_parameter
            (integral_type)
            (identifier))
          (formal_parameter
            (integral_type)
            (identifier)))
        (block
          (return_statement
            (decimal_integer_literal)))))))
