(program (comment) (lexical_declaration (variable_declarator name: (identifier) value: (object (pair key: (property_identifier) value: (number)) (pair key: (property_identifier) value: (number)) (pair key: (property_identifier) value: (number)) (pair key: (property_identifier) value: (number)) (pair key: (property_identifier) value: (number)) (pair key: (property_identifier) value: (number)) (pair key: (property_identifier) value: (number)) (pair key: (property_identifier) value: (number)) (pair key: (property_identifier) value: (number)) (pair key: (property_identifier) value: (number)) (pair key: (property_identifier) value: (number)) (pair key: (property_identifier) value: (number))))) (function_declaration name: (identifier) parameters: (formal_parameters) body: (statement_block (return_statement (call_expression function: (identifier) arguments: (arguments (number) (number) (number) (number) (number) (number) (number) (number) (number)))))))
---
(program
  (comment)
  (lexical_declaration
    (variable_declarator
      (identifier)
      (object
        (pair
          (property_identifier)
          (number))
        (pair
          (property_identifier)
          (number))
        (pair
          (property_identifier)
          (number))
        (pair
          (property_identifier)
          (number))
        (pair
          (property_identifier)
          (number))
        (pair
          (property_identifier)
          (number))
        (pair
          (property_identifier)
          (number))
        (pair
          (property_identifier)
          (number))
        (pair
          (property_identifier)
          (number))
        (pair
          (property_identifier)
          (number))
        (pair
          (property_identifier)
          (number))
        (pair
          (property_identifier)
          (number)))))
  (function_declaration
    (identifier)
    (formal_parameters)
    (statement_block
      (return_statement
        (call_expression
          (identifier)
          (arguments
            (number)
            (number)
            (number)
            (number)
            (number)
            (number)
            (number)
            (number)
            (number)))))))
