(document (object (pair key: (string (string_content)) value: (array (object (pair key: (string (string_content)) value: (number)) (pair key: (string (string_content)) value: (string (string_content)))) (object (pair key: (string (string_content)) value: (number)) (pair key: (string (string_content)) value: (string (string_content)))) (object (pair key: (string (string_content)) value: (number)) (pair key: (string (string_content)) value: (string (string_content)))) (object (pair key: (string (string_content)) value: (number)) (pair key: (string (string_content)) value: (string (string_content)))) (object (pair key: (string (string_content)) value: (number)) (pair key: (string (string_content)) value: (string (string_content)))) (object (pair key: (string (string_content)) value: (number)) (pair key: (string (string_content)) value: (string (string_content)))) (object (pair key: (string (string_content)) value: (number)) (pair key: (string (string_content)) value: (string (string_content)))) (object (pair key: (string (string_content)) value: (number)) (pair key: (string (string_content)) value: (string (string_content)))) (object (pair key: (string (string_content)) value: (number)) (pair key: (string (string_content)) value: (string (string_content)))) (object (pair key: (string (string_content)) value: (number)) (pair key: (string (string_content)) value: (string (string_content)))) (object (pair key: (string (string_content)) value: (number)) (pair key: (string (string_content)) value: (string (string_content)))) (object (pair key: (string (string_content)) value: (number)) (pair key: (string (string_content)) value: (string (string_content)))) (object (pair key: (string (string_content)) value: (number)) (pair key: (string (string_content)) value: (string (string_content)))) (object (pair key: (string (string_content)) value: (number)) (pair key: (string (string_content)) value: (string (string_content)))) (object (pair key: (string (string_content)) value: (number)) (pair key: (string (string_content)) value: (string (string_content)))) (object (pair key: (string (string_content)) value: (number)) (pair key: (string (string_content)) value: (string (string_content)))) (object (pair key: (string (string_content)) value: (number)) (pair key: (string (string_content)) value: (string (string_content)))) (object (pair key: (string (string_content)) value: (number)) (pair key: (string (string_content)) value: (string (string_content)))) (object (pair key: (string (string_content)) value: (number)) (pair key: (string (string_content)) value: (string (string_content)))) (object (pair key: (string (string_content)) value: (number)) (pair key: (string (string_content)) value: (string (string_content)))) (object (pair key: (string (string_content)) value: (number)) (pair key: (string (string_content)) value: (string (string_content)))) (object (pair key: (string (string_content)) value: (number)) (pair key: (string (string_content)) value: (string (string_content)))) (object (pair key: (string (string_content)) value: (number)) (pair key: (string (string_content)) value: (string (string_content)))) (object (pair key: (string (string_content)) value: (number)) (pair key: (string (string_content)) value: (string (string_content)))) (object (pair key: (string (string_content)) value: (number)) (pair key: (string (string_content)) value: (string (string_content)))) (object (pair key: (string (string_content)) value: (number)) (pair key: (string (string_content)) value: (string (string_content)))) (object (pair key: (string (string_content)) value: (number)) (pair key: (string (string_content)) value: (string (string_content)))) (object (pair key: (string (string_content)) value: (number)) (pair key: (string (string_content)) value: (string (string_content)))) (object (pair key: (string (string_content)) value: (number)) (pair key: (string (string_content)) value: (string (string_content)))) (object (pair key: (string (string_content)) value: (number)) (pair key: (string (string_content)) value: (string (string_content)))))) (pair key: (string (string_content)) value: (object (pair key: (string (string_content)) value: (number)) (pair key: (string (string_content)) value: (number)) (pair key: (string (string_content)) value: (number)) (pair key: (string (string_content)) value: (number)) (pair key: (string (string_content)) value: (number)) (pair key: (string (string_content)) value: (number)) (pair key: (string (string_content)) value: (number)) (pair key: (string (string_content)) value: (number)) (pair key: (string (string_content)) value: (number)) (pair key: (string (string_content)) value: (number)) (pair key: (string (string_content)) value: (number)) (pair key: (string (string_content)) value: (number))))))
---
(document
  (object
    (pair
      (string
        (string_content))
      (array
        (object
          (pair
            (string
              (string_content))
            (number))
          (pair
            (string
              (string_content))
            (string
              (string_content))))
        (object
          (pair
            (string
              (string_content))
            (number))
          (pair
            (string
              (string_content))
            (string
              (string_content))))
        (object
          (pair
            (string
              (string_content))
            (number))
          (pair
            (string
              (string_content))
            (string
              (string_content))))
        (object
          (pair
            (string
              (string_content))
            (number))
          (pair
            (string
              (string_content))
            (string
              (string_content))))
        (object
          (pair
            (string
              (string_content))
            (number))
          (pair
            (string
              (string_content))
            (string
              (string_content))))
        (object
          (pair
            (string
              (string_content))
            (number))
          (pair
            (string
              (string_content))
            (string
              (string_content))))
        (object
          (pair
            (string
              (string_content))
            (number))
          (pair
            (string
              (string_content))
            (string
              (string_content))))
        (object
          (pair
            (string
              (string_content))
            (number))
          (pair
            (string
              (string_content))
            (string
              (string_content))))
        (object
          (pair
            (string
              (string_content))
            (number))
          (pair
            (string
              (string_content))
            (string
              (string_content))))
        (object
          (pair
            (string
              (string_content))
            (number))
          (pair
            (string
              (string_content))
            (string
              (string_content))))
        (object
          (pair
            (string
              (string_content))
            (number))
          (pair
            (string
              (string_content))
            (string
              (string_content))))
        (object
          (pair
            (string
              (string_content))
            (number))
          (pair
            (string
              (string_content))
            (string
              (string_content))))
        (object
          (pair
            (string
              (string_content))
            (number))
          (pair
            (string
              (string_content))
            (string
              (string_content))))
        (object
          (pair
            (string
              (string_content))
            (number))
          (pair
            (string
              (string_content))
            (string
              (string_content))))
        (object
          (pair
            (string
              (string_content))
            (number))
          (pair
            (string
              (string_content))
            (string
              (string_content))))
        (object
          (pair
            (string
              (string_content))
            (number))
          (pair
            (string
              (string_content))
            (string
              (string_content))))
        (object
          (pair
            (string
              (string_content))
            (number))
          (pair
            (string
              (string_content))
            (string
              (string_content))))
        (object
          (pair
            (string
              (string_content))
            (number))
          (pair
            (string
              (string_content))
            (string
              (string_content))))
        (object
          (pair
            (string
              (string_content))
            (number))
          (pair
            (string
              (string_content))
            (string
              (string_content))))
        (object
          (pair
            (string
              (string_content))
            (number))
          (pair
            (string
              (string_content))
            (string
              (string_content))))
        (object
          (pair
            (string
              (string_content))
            (number))
          (pair
            (string
              (string_content))
            (string
              (string_content))))
        (object
          (pair
            (string
              (string_content))
            (number))
          (pair
            (string
              (string_content))
            (string
              (string_content))))
        (object
          (pair
            (string
              (string_content))
            (number))
          (pair
            (string
              (string_content))
            (string
              (string_content))))
        (object
          (pair
            (string
              (string_content))
            (number))
          (pair
            (string
              (string_content))
            (string
              (string_content))))
        (object
          (pair
            (string
              (string_content))
            (number))
          (pair
            (string
              (string_content))
            (string
              (string_content))))
        (object
          (pair
            (string
              (string_content))
            (number))
          (pair
            (string
              (string_content))
            (string
              (string_content))))
        (object
          (pair
            (string
              (string_content))
            (number))
          (pair
            (string
              (string_content))
            (string
              (string_content))))
        (object
          (pair
            (string
              (string_content))
            (number))
          (pair
            (string
              (string_content))
            (string
              (string_content))))
        (object
          (pair
            (string
              (string_content))
            (number))
          (pair
            (string
              (string_content))
            (string
              (string_content))))
        (object
          (pair
            (string
              (string_content))
            (number))
          (pair
            (string
              (string_content))
            (string
              (string_content))))))
    (pair
      (string
        (string_content))
      (object
        (pair
          (string
            (string_content))
          (number))
        (pair
          (string
            (string_content))
          (number))
        (pair
          (string
            (string_content))
          (number))
        (pair
          (string
            (string_content))
          (number))
        (pair
          (string
            (string_content))
          (number))
        (pair
          (string
            (string_content))
          (number))
        (pair
          (string
            (string_content))
          (number))
        (pair
          (string
            (string_content))
          (number))
        (pair
          (string
            (string_content))
          (number))
        (pair
          (string
            (string_content))
          (number))
        (pair
          (string
            (string_content))
          (number))
        (pair
          (string
            (string_content))
          (number))))))
