(module (comment) (ERROR (assignment left: (identifier) (ERROR (integer) (assignment left: (identifier) right: (integer)) (assignment left: (identifier) (ERROR (integer) (assignment left: (identifier) right: (integer))) right: (assignment left: (identifier) right: (integer)))) right: (assignment left: (identifier) (ERROR (integer) (assignment left: (identifier) right: (integer)) (assignment left: (identifier) (ERROR (integer) (assignment left: (identifier) right: (integer))) right: (assignment left: (identifier) (ERROR (integer) (assignment left: (identifier) right: (integer))) right: (assignment left: (identifier) right: (integer)))) (identifier)) right: (call function: (identifier) arguments: (argument_list (identifier) (identifier) (identifier) (identifier) (identifier) (identifier) (identifier) (identifier) (identifier))))) (return_statement (none))))
---
(module
  (comment)
  (ERROR
    (assignment
      (identifier)
      (ERROR
        (integer)
        (assignment
          (identifier)
          (integer))
        (assignment
          (identifier)
          (ERROR
            (integer)
            (assignment
              (identifier)
              (integer)))
          (assignment
            (identifier)
            (integer))))
      (assignment
        (identifier)
        (ERROR
          (integer)
          (assignment
            (identifier)
            (integer))
          (assignment
            (identifier)
            (ERROR
              (integer)
              (assignment
                (identifier)
                (integer)))
            (assignment
              (identifier)
              (ERROR
                (integer)
                (assignment
                  (identifier)
                  (integer)))
              (assignment
                (identifier)
                (integer))))
          (identifier))
        (call
          (identifier)
          (argument_list
            (identifier)
            (identifier)
            (identifier)
            (identifier)
            (identifier)
            (identifier)
            (identifier)
            (identifier)
            (identifier)))))
    (return_statement
      (none))))
