(program (comment) (lexical_declaration (variable_declarator name: (identifier) value: (jsx_element open_tag: (jsx_opening_element name: (identifier) attribute: (jsx_attribute (property_identifier) (string (string_fragment))) attribute: (jsx_attribute (property_identifier) (string (string_fragment))) attribute: (jsx_attribute (property_identifier) (string (string_fragment))) attribute: (jsx_attribute (property_identifier) (string (string_fragment))) attribute: (jsx_attribute (property_identifier) (string (string_fragment))) attribute: (jsx_attribute (property_identifier) (string (string_fragment))) attribute: (jsx_attribute (property_identifier) (string (string_fragment))) attribute: (jsx_attribute (property_identifier) (string (string_fragment))) attribute: (jsx_attribute (property_identifier) (string (string_fragment))) attribute: (jsx_attribute (property_identifier) (string (string_fragment))) attribute: (jsx_attribute (property_identifier) (string (string_fragment))) attribute: (jsx_attribute (property_identifier) (string (string_fragment)))) (jsx_text) close_tag: (jsx_closing_element name: (identifier))))))
---
(program
  (comment)
  (lexical_declaration
    (variable_declarator
      (identifier)
      (jsx_element
        (jsx_opening_element
          (identifier)
          (jsx_attribute
            (property_identifier)
            (string
              (string_fragment)))
          (jsx_attribute
            (property_identifier)
            (string
              (string_fragment)))
          (jsx_attribute
            (property_identifier)
            (string
              (string_fragment)))
          (jsx_attribute
            (property_identifier)
            (string
              (string_fragment)))
          (jsx_attribute
            (property_identifier)
            (string
              (string_fragment)))
          (jsx_attribute
            (property_identifier)
            (string
              (string_fragment)))
          (jsx_attribute
            (property_identifier)
            (string
              (string_fragment)))
          (jsx_attribute
            (property_identifier)
            (string
              (string_fragment)))
          (jsx_attribute
            (property_identifier)
            (string
              (string_fragment)))
          (jsx_attribute
            (property_identifier)
            (string
              (string_fragment)))
          (jsx_attribute
            (property_identifier)
            (string
              (string_fragment)))
          (jsx_attribute
            (property_identifier)
            (string
              (string_fragment))))
        (jsx_text)
        (jsx_closing_element
          (identifier))))))
