(program (comment) (interface_declaration name: (type_identifier) body: (interface_body (property_signature name: (property_identifier) type: (type_annotation (predefined_type))) (property_signature name: (property_identifier) type: (type_annotation (predefined_type))) (property_signature name: (property_identifier) type: (type_annotation (predefined_type))) (property_signature name: (property_identifier) type: (type_annotation (predefined_type))) (property_signature name: (property_identifier) type: (type_annotation (predefined_type))) (property_signature name: (property_identifier) type: (type_annotation (predefined_type))) (property_signature name: (property_identifier) type: (type_annotation (predefined_type))) (property_signature name: (property_identifier) type: (type_annotation (predefined_type))) (property_signature name: (property_identifier) type: (type_annotation (predefined_type))) (property_signature name: (property_identifier) type: (type_annotation (predefined_type))) (property_signature name: (property_identifier) type: (type_annotation (predefined_type))) (property_signature name: (property_identifier) type: (type_annotation (predefined_type))))) (type_alias_declaration name: (type_identifier) value: (union_type (union_type (union_type (union_type (union_type (union_type (union_type (union_type (union_type (literal_type (string (string_fragment))) (literal_type (string (string_fragment)))) (literal_type (string (string_fragment)))) (literal_type (string (string_fragment)))) (literal_type (string (string_fragment)))) (literal_type (string (string_fragment)))) (literal_type (string (string_fragment)))) (literal_type (string (string_fragment)))) (literal_type (string (string_fragment)))) (literal_type (string (string_fragment))))))
---
(program
  (comment)
  (interface_declaration
    (type_identifier)
    (interface_body
      (property_signature
        (property_identifier)
        (type_annotation
          (predefined_type)))
      (property_signature
        (property_identifier)
        (type_annotation
          (predefined_type)))
      (property_signature
        (property_identifier)
        (type_annotation
          (predefined_type)))
      (property_signature
        (property_identifier)
        (type_annotation
          (predefined_type)))
      (property_signature
        (property_identifier)
        (type_annotation
          (predefined_type)))
      (property_signature
        (property_identifier)
        (type_annotation
          (predefined_type)))
      (property_signature
        (property_identifier)
        (type_annotation
          (predefined_type)))
      (property_signature
        (property_identifier)
        (type_annotation
          (predefined_type)))
      (property_signature
        (property_identifier)
        (type_annotation
          (predefined_type)))
      (property_signature
        (property_identifier)
        (type_annotation
          (predefined_type)))
      (property_signature
        (property_identifier)
        (type_annotation
          (predefined_type)))
      (property_signature
        (property_identifier)
        (type_annotation
          (predefined_type)))))
  (type_alias_declaration
    (type_identifier)
    (union_type
      (union_type
        (union_type
          (union_type
            (union_type
              (union_type
                (union_type
                  (union_type
                    (union_type
                      (literal_type
                        (string
                          (string_fragment)))
                      (literal_type
                        (string
                          (string_fragment))))
                    (literal_type
                      (string
                        (string_fragment))))
                  (literal_type
                    (string
                      (string_fragment))))
                (literal_type
                  (string
                    (string_fragment))))
              (literal_type
                (string
                  (string_fragment))))
            (literal_type
              (string
                (string_fragment))))
          (literal_type
            (string
              (string_fragment))))
        (literal_type
          (string
            (string_fragment))))
      (literal_type
        (string
          (string_fragment))))))
