
CREATE TABLE nop_credential(
  CREDENTIAL_ID VARCHAR(50) NOT NULL    COMMENT '凭证ID',
  CREDENTIAL_NAME VARCHAR(100) NULL    COMMENT '凭证名',
  TYPE_NAME VARCHAR(100) NULL    COMMENT '凭证类型',
  DATA VARCHAR(4000) NULL    COMMENT '加密数据',
  STATUS VARCHAR(20) default 'enabled'  NULL    COMMENT '状态',
  DEL_FLAG TINYINT NOT NULL    COMMENT '删除标识',
  USAGE_SCOPE VARCHAR(50) NULL    COMMENT '使用范围',
  LAST_USED_AT DATETIME(3) NULL    COMMENT '最后使用时间',
  EXPIRE_AT DATETIME(3) NULL    COMMENT '过期时间',
  TEST_RESULT VARCHAR(500) NULL    COMMENT '连通性测试结果',
  VERSION INTEGER NOT NULL    COMMENT '版本',
  CREATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '创建时间',
  CREATED_BY VARCHAR(50) NOT NULL    COMMENT '创建人',
  UPDATE_TIME DATETIME(3) NULL    COMMENT '更新时间',
  UPDATED_BY VARCHAR(50) NULL    COMMENT '更新人',
  REMARK VARCHAR(200) NULL    COMMENT '备注',
  constraint PK_nop_credential primary key (CREDENTIAL_ID)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs;

CREATE TABLE nop_credential_oauth_state(
  STATE VARCHAR(64) NOT NULL    COMMENT 'State令牌',
  CREDENTIAL_ID VARCHAR(50) NOT NULL    COMMENT '凭证ID',
  USER_ID VARCHAR(50) NOT NULL    COMMENT '发起人',
  EXPIRE_AT BIGINT NULL    COMMENT '过期时间',
  CONSUMED TINYINT default 0  NOT NULL    COMMENT '已消费',
  CREATE_TIME DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)  NOT NULL    COMMENT '创建时间',
  CREATED_BY VARCHAR(50) NOT NULL    COMMENT '创建人',
  constraint PK_nop_credential_oauth_state primary key (STATE)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs;

CREATE TABLE nop_credential_usage(
  USAGE_ID VARCHAR(50) NOT NULL    COMMENT '使用记录ID',
  CREDENTIAL_ID VARCHAR(50) NOT NULL    COMMENT '凭证ID',
  CONSUMER_REF VARCHAR(200) NOT NULL    COMMENT '消费者引用',
  CREATE_TIME DATETIME(3) NULL    COMMENT '创建时间',
  constraint UK_NOP_CREDENTIAL_USAGE_CRED_CONSUMER unique (CREDENTIAL_ID,CONSUMER_REF),
  constraint PK_nop_credential_usage primary key (USAGE_ID)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_as_cs;


   ALTER TABLE nop_credential COMMENT '加密凭证';
                
   ALTER TABLE nop_credential_oauth_state COMMENT 'OAuth授权State绑定';
                
   ALTER TABLE nop_credential_usage COMMENT '凭证使用记录';
                
