package io.nop.ai.toolkit.compact;

import io.nop.ai.toolkit.model.AiToolCall;

import java.util.Objects;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

/**
 * Reference pointer embedded in a chat message in place of original content
 * that was archived by reference-style compaction. The LLM sees the serialized
 * form and uses it to issue a {@code read-ref} tool call to read back the
 * original content.
 *
 * <p>Fields (data contract per design §8.2 Decision E):
 * <ul>
 *   <li>{@code type} — content source category ({@code file} | {@code search} |
 *       {@code grep} | {@code glob}, mapped from the producing tool name)</li>
 *   <li>{@code path} — locating info (file path / search dir); may be {@code null}</li>
 *   <li>{@code range} — range info (e.g. line range {@code "1-100"}); may be {@code null}</li>
 *   <li>{@code hash} — content hash ({@code "sha256:<hex>"}); the read-back key</li>
 * </ul>
 *
 * <p>Serialized form (single line, space-separated, fixed field order):
 * <pre>
 *   [SHORT_REF type=file path=/foo/bar.txt range=1-100 hash=sha256:&lt;hex&gt;]
 * </pre>
 * This format is parseable — distinct from Layer 3's {@code SUMMARY_MARKER}
 * (system-side flag) which is only detected via {@code startsWith}. The
 * {@code SHORT_REF} marker is generated by the reference compaction strategy
 * and parsed back (here) to support round-tripping and the {@code read-ref}
 * input contract.
 *
 * <p>Design ref: {@code ai-dev/design/nop-ai-agent/nop-ai-agent-context-model.md}
 * §8.2 Decision E.
 */
public final class ShortRef {

    public static final String MARKER = "[SHORT_REF";
    public static final String MARKER_END = "]";

    public static final String TYPE_FILE = "file";
    public static final String TYPE_SEARCH = "search";
    public static final String TYPE_GREP = "grep";
    public static final String TYPE_GLOB = "glob";

    private final String type;
    private final String path;
    private final String range;
    private final String hash;

    public ShortRef(String type, String path, String range, String hash) {
        this.type = type;
        this.path = path;
        this.range = range;
        this.hash = Objects.requireNonNull(hash, "hash must not be null");
    }

    public String getType() {
        return type;
    }

    public String getPath() {
        return path;
    }

    public String getRange() {
        return range;
    }

    public String getHash() {
        return hash;
    }

    /**
     * Serialize to the canonical single-line form embedded in chat message content.
     */
    public String serialize() {
        StringBuilder sb = new StringBuilder(MARKER);
        if (type != null) {
            sb.append(" type=").append(type);
        }
        if (path != null) {
            sb.append(" path=").append(escapeSpaces(path));
        }
        if (range != null) {
            sb.append(" range=").append(range);
        }
        sb.append(" hash=").append(hash).append(MARKER_END);
        return sb.toString();
    }

    /**
     * Parse the FIRST {@code [SHORT_REF ...]} occurrence in {@code content}.
     * Returns {@code null} if no marker is present. Throws
     * {@link IllegalArgumentException} if a marker is present but malformed
     * (missing {@code hash} field or unparseable) — callers must surface this
     * rather than silently degrade (Minimum Rules #24).
     *
     * @param content the chat message content to scan; may be null
     * @return the parsed ShortRef, or null if no marker present
     */
    public static ShortRef parseFirst(String content) {
        if (content == null) {
            return null;
        }
        int start = content.indexOf(MARKER);
        if (start < 0) {
            return null;
        }
        int end = content.indexOf(MARKER_END, start);
        if (end < 0) {
            throw new IllegalArgumentException("Malformed SHORT_REF: missing closing ']' in: "
                    + content.substring(start));
        }
        String body = content.substring(start + MARKER.length(), end).trim();
        String type = extractField(body, "type");
        String path = extractField(body, "path");
        String range = extractField(body, "range");
        String hash = extractField(body, "hash");
        if (hash == null) {
            throw new IllegalArgumentException("Malformed SHORT_REF: missing required 'hash' field in: "
                    + body);
        }
        return new ShortRef(type, path, range, hash);
    }

    private static String extractField(String body, String fieldName) {
        Pattern p = Pattern.compile(fieldName + "=([^\\s]+)");
        Matcher m = p.matcher(body);
        if (m.find()) {
            return unescapeSpaces(m.group(1));
        }
        return null;
    }

    /**
     * Replace spaces in path with {@code %20} so the serialized form stays
     * single-line space-separated and parseable.
     */
    private static String escapeSpaces(String s) {
        return s.replace(" ", "%20");
    }

    private static String unescapeSpaces(String s) {
        return s.replace("%20", " ");
    }

    /**
     * Map a producing tool name to a {@code type} value. Returns {@code null}
     * if the tool is not referenceable.
     */
    public static String typeForTool(String toolName) {
        if (toolName == null) {
            return null;
        }
        switch (toolName) {
            case "read-file":
            case "read_file":
            case "cat":
            case "head":
            case "tail":
            case "type":
            case "get-content":
                return TYPE_FILE;
            case "grep":
            case "select-string":
            case "rg":
            case "find":
                return TYPE_GREP;
            case "glob":
            case "ls":
            case "dir":
            case "list-dir":
            case "list_directory":
                return TYPE_GLOB;
            case "search":
            case "search-engine":
            case "search-files":
                return TYPE_SEARCH;
            default:
                return null;
        }
    }

    /**
     * Convenience: copy ShortRef fields into the {@code read-ref} tool call's
     * node attributes so {@code ReadRefExecutor} can read them via
     * {@link AiToolCall#attrText(String, String)}.
     */
    public void applyToCall(io.nop.core.lang.xml.XNode node) {
        node.setAttr("hash", hash);
        if (type != null) {
            node.setAttr("type", type);
        }
        if (path != null) {
            node.setAttr("path", path);
        }
        if (range != null) {
            node.setAttr("range", range);
        }
    }

    @Override
    public String toString() {
        return serialize();
    }
}
