
CREATE TABLE nop_sys_sequence(
  SEQ_NAME VARCHAR(150) NOT NULL    COMMENT '名称',
  SEQ_TYPE VARCHAR(10)     COMMENT '类型',
  IS_UUID TINYINT NOT NULL    COMMENT '是否UUID',
  NEXT_VALUE BIGINT NOT NULL    COMMENT '下一个值',
  STEP_SIZE INTEGER NOT NULL    COMMENT '步长',
  CACHE_SIZE INTEGER     COMMENT '缓存个数',
  MAX_VALUE BIGINT     COMMENT '最大值',
  RESET_TYPE INTEGER     COMMENT '重置方式',
  DEL_FLAG TINYINT NOT NULL    COMMENT '删除标识',
  VERSION INTEGER NOT NULL    COMMENT '数据版本',
  CREATED_BY VARCHAR(50) NOT NULL    COMMENT '创建人',
  CREATE_TIME TIMESTAMP NOT NULL  DEFAULT CURRENT_TIMESTAMP    COMMENT '创建时间',
  UPDATED_BY VARCHAR(50) NOT NULL    COMMENT '修改人',
  UPDATE_TIME TIMESTAMP NOT NULL  DEFAULT CURRENT_TIMESTAMP    COMMENT '修改时间',
  REMARK VARCHAR(200)     COMMENT '备注',
  constraint PK_nop_sys_sequence primary key (SEQ_NAME)
);

CREATE TABLE nop_sys_dict_option(
  SID VARCHAR(32) NOT NULL    COMMENT '主键',
  DICT_ID VARCHAR(32) NOT NULL    COMMENT '字典ID',
  LABEL VARCHAR(150) NOT NULL    COMMENT '显示名',
  VALUE VARCHAR(150) NOT NULL    COMMENT '值',
  CODE_VALUE VARCHAR(100)     COMMENT '内部编码',
  GROUP_NAME VARCHAR(50)     COMMENT '分组名',
  IS_INTERNAL TINYINT NOT NULL    COMMENT '是否内部',
  IS_DEPRECATED TINYINT NOT NULL    COMMENT '是否已废弃',
  DEL_FLAG TINYINT NOT NULL    COMMENT '删除标识',
  VERSION INTEGER NOT NULL    COMMENT '数据版本',
  CREATED_BY VARCHAR(50) NOT NULL    COMMENT '创建人',
  CREATE_TIME TIMESTAMP NOT NULL  DEFAULT CURRENT_TIMESTAMP    COMMENT '创建时间',
  UPDATED_BY VARCHAR(50) NOT NULL    COMMENT '修改人',
  UPDATE_TIME TIMESTAMP NOT NULL  DEFAULT CURRENT_TIMESTAMP    COMMENT '修改时间',
  REMARK VARCHAR(200)     COMMENT '备注',
  constraint PK_nop_sys_dict_option primary key (SID)
);

CREATE TABLE nop_sys_i18n(
  I18N_KEY VARCHAR(300) NOT NULL    COMMENT '字符串Key',
  I18N_LOCALE VARCHAR(50) NOT NULL    COMMENT '语言',
  VALUE VARCHAR(300) NOT NULL    COMMENT '值',
  VERSION INTEGER NOT NULL    COMMENT '数据版本',
  CREATED_BY VARCHAR(50) NOT NULL    COMMENT '创建人',
  CREATE_TIME TIMESTAMP NOT NULL  DEFAULT CURRENT_TIMESTAMP    COMMENT '创建时间',
  UPDATED_BY VARCHAR(50) NOT NULL    COMMENT '修改人',
  UPDATE_TIME TIMESTAMP NOT NULL  DEFAULT CURRENT_TIMESTAMP    COMMENT '修改时间',
  REMARK VARCHAR(200)     COMMENT '备注',
  constraint PK_nop_sys_i18n primary key (I18N_KEY,I18N_LOCALE)
);

CREATE TABLE nop_sys_maker_checker_record(
  SID VARCHAR(32) NOT NULL    COMMENT '主键',
  BIZ_OBJ_NAME VARCHAR(200) NOT NULL    COMMENT '业务对象名',
  BIZ_OBJ_ID VARCHAR(100)     COMMENT '业务对象ID',
  MAKER_ID VARCHAR(50) NOT NULL    COMMENT '请求发起人ID',
  MAKER_NAME VARCHAR(150) NOT NULL    COMMENT '请求发起人',
  REQUEST_ACTION VARCHAR(100) NOT NULL    COMMENT '请求操作',
  REQUEST_DATA MEDIUMTEXT     COMMENT '请求数据',
  REQUEST_TIME DATETIME NOT NULL    COMMENT '请求时间',
  CHECKER_ID VARCHAR(50)     COMMENT '审批人ID',
  CHECKER_NAME VARCHAR(150)     COMMENT '审批人',
  CHECK_TIME DATETIME     COMMENT '审批时间',
  TRY_RESULT MEDIUMTEXT     COMMENT '请求结果',
  INPUT_PAGE VARCHAR(1000)     COMMENT '输入页面',
  STATUS INTEGER NOT NULL    COMMENT '审批状态',
  CANCEL_ACTION VARCHAR(200)     COMMENT '取消方法',
  CB_ERR_CODE VARCHAR(150)     COMMENT '回调错误码',
  CE_ERR_MSG VARCHAR(1000)     COMMENT '回调错误消息',
  VERSION INTEGER NOT NULL    COMMENT '数据版本',
  CREATED_BY VARCHAR(50) NOT NULL    COMMENT '创建人',
  CREATE_TIME TIMESTAMP NOT NULL  DEFAULT CURRENT_TIMESTAMP    COMMENT '创建时间',
  UPDATED_BY VARCHAR(50) NOT NULL    COMMENT '修改人',
  UPDATE_TIME TIMESTAMP NOT NULL  DEFAULT CURRENT_TIMESTAMP    COMMENT '修改时间',
  REMARK VARCHAR(200)     COMMENT '备注',
  constraint PK_nop_sys_maker_checker_record primary key (SID)
);

CREATE TABLE nop_sys_code_rule(
  SID VARCHAR(32) NOT NULL    COMMENT '主键',
  NAME VARCHAR(100) NOT NULL    COMMENT '名称',
  DISPLAY_NAME VARCHAR(100) NOT NULL    COMMENT '显示名称',
  CODE_PATTERN VARCHAR(200) NOT NULL    COMMENT '编码模式',
  SEQ_NAME VARCHAR(100)     COMMENT '序列号名称',
  DEL_FLAG TINYINT NOT NULL    COMMENT '删除标识',
  VERSION INTEGER NOT NULL    COMMENT '数据版本',
  CREATED_BY VARCHAR(50) NOT NULL    COMMENT '创建人',
  CREATE_TIME TIMESTAMP NOT NULL  DEFAULT CURRENT_TIMESTAMP    COMMENT '创建时间',
  UPDATED_BY VARCHAR(50) NOT NULL    COMMENT '修改人',
  UPDATE_TIME TIMESTAMP NOT NULL  DEFAULT CURRENT_TIMESTAMP    COMMENT '修改时间',
  REMARK VARCHAR(200)     COMMENT '备注',
  constraint PK_nop_sys_code_rule primary key (SID)
);

CREATE TABLE nop_sys_notice_template(
  SID VARCHAR(32) NOT NULL    COMMENT '主键',
  NAME VARCHAR(100) NOT NULL    COMMENT '名称',
  TPL_TYPE VARCHAR(10) NOT NULL    COMMENT '模板类型',
  CONTENT VARCHAR(4000) NOT NULL    COMMENT '模板内容',
  DEL_FLAG TINYINT NOT NULL    COMMENT '删除标识',
  VERSION INTEGER NOT NULL    COMMENT '数据版本',
  CREATED_BY VARCHAR(50) NOT NULL    COMMENT '创建人',
  CREATE_TIME TIMESTAMP NOT NULL  DEFAULT CURRENT_TIMESTAMP    COMMENT '创建时间',
  UPDATED_BY VARCHAR(50) NOT NULL    COMMENT '修改人',
  UPDATE_TIME TIMESTAMP NOT NULL  DEFAULT CURRENT_TIMESTAMP    COMMENT '修改时间',
  REMARK VARCHAR(200)     COMMENT '备注',
  constraint PK_nop_sys_notice_template primary key (SID)
);

CREATE TABLE nop_sys_user_variable(
  USER_ID VARCHAR(32) NOT NULL    COMMENT '用户ID',
  VAR_NAME VARCHAR(32) NOT NULL    COMMENT '变量名',
  VAR_VALUE VARCHAR(4000)     COMMENT '变量值',
  STD_DOMAIN VARCHAR(100)     COMMENT '变量域',
  VAR_TYPE VARCHAR(100)     COMMENT '变量类型',
  VERSION INTEGER NOT NULL    COMMENT '数据版本',
  CREATED_BY VARCHAR(50) NOT NULL    COMMENT '创建人',
  CREATE_TIME TIMESTAMP NOT NULL  DEFAULT CURRENT_TIMESTAMP    COMMENT '创建时间',
  UPDATED_BY VARCHAR(50) NOT NULL    COMMENT '修改人',
  UPDATE_TIME TIMESTAMP NOT NULL  DEFAULT CURRENT_TIMESTAMP    COMMENT '修改时间',
  REMARK VARCHAR(200)     COMMENT '备注',
  constraint PK_nop_sys_user_variable primary key (USER_ID,VAR_NAME)
);

CREATE TABLE nop_sys_variable(
  VAR_NAME VARCHAR(32) NOT NULL    COMMENT '变量名',
  VAR_VALUE VARCHAR(4000)     COMMENT '变量值',
  STD_DOMAIN VARCHAR(100)     COMMENT '变量域',
  VAR_TYPE VARCHAR(100)     COMMENT '变量类型',
  VERSION INTEGER NOT NULL    COMMENT '数据版本',
  CREATED_BY VARCHAR(50) NOT NULL    COMMENT '创建人',
  CREATE_TIME TIMESTAMP NOT NULL  DEFAULT CURRENT_TIMESTAMP    COMMENT '创建时间',
  UPDATED_BY VARCHAR(50) NOT NULL    COMMENT '修改人',
  UPDATE_TIME TIMESTAMP NOT NULL  DEFAULT CURRENT_TIMESTAMP    COMMENT '修改时间',
  REMARK VARCHAR(200)     COMMENT '备注',
  constraint PK_nop_sys_variable primary key (VAR_NAME)
);

CREATE TABLE nop_sys_dict(
  SID VARCHAR(32) NOT NULL    COMMENT '主键',
  DICT_NAME VARCHAR(150) NOT NULL    COMMENT '字典名',
  DISPLAY_NAME VARCHAR(50) NOT NULL    COMMENT '显示名',
  DEL_FLAG TINYINT NOT NULL    COMMENT '删除标识',
  VERSION INTEGER NOT NULL    COMMENT '数据版本',
  CREATED_BY VARCHAR(50) NOT NULL    COMMENT '创建人',
  CREATE_TIME TIMESTAMP NOT NULL  DEFAULT CURRENT_TIMESTAMP    COMMENT '创建时间',
  UPDATED_BY VARCHAR(50) NOT NULL    COMMENT '修改人',
  UPDATE_TIME TIMESTAMP NOT NULL  DEFAULT CURRENT_TIMESTAMP    COMMENT '修改时间',
  REMARK VARCHAR(200)     COMMENT '备注',
  constraint PK_nop_sys_dict primary key (SID)
);


   ALTER TABLE nop_sys_sequence COMMENT '序列号';
                
   ALTER TABLE nop_sys_dict_option COMMENT '字典明细';
                
   ALTER TABLE nop_sys_i18n COMMENT '多语言消息';
                
   ALTER TABLE nop_sys_maker_checker_record COMMENT 'MakerChecker审批记录';
                
   ALTER TABLE nop_sys_code_rule COMMENT '编码规则';
                
   ALTER TABLE nop_sys_notice_template COMMENT '通知模板';
                
   ALTER TABLE nop_sys_user_variable COMMENT '用户变量';
                
   ALTER TABLE nop_sys_variable COMMENT '系统变量';
                
   ALTER TABLE nop_sys_dict COMMENT '字典表';
                
