
CREATE TABLE voyage(
  ID BIGINT NOT NULL    COMMENT 'Id',
  VOYAGE_NUMBER VARCHAR(255) NULL    COMMENT '航程号',
  constraint PK_voyage primary key (ID)
);

CREATE TABLE location(
  ID BIGINT NOT NULL    COMMENT 'Id',
  NAME VARCHAR(255) NOT NULL    COMMENT '名称',
  UNLOCODE VARCHAR(255) NOT NULL    COMMENT 'UN编码',
  constraint PK_location primary key (ID)
);

CREATE TABLE cargo(
  ID BIGINT NOT NULL    COMMENT 'Id',
  CALCULATED_AT DATETIME NULL    COMMENT '计算时间',
  ETA DATETIME NULL    COMMENT '预计到达时间',
  UNLOADED_AT_DEST BOOLEAN NULL    COMMENT '目的地卸载时间',
  MISDIRECTED BOOLEAN NULL    COMMENT '路线错误',
  NEXT_EXPECTED_HANDLING_EVENT_TYPE VARCHAR(255) NULL    COMMENT '下一步预期处理事件类型',
  ROUTING_STATUS VARCHAR(255) NULL    COMMENT '路由状态',
  TRANSPORT_STATUS VARCHAR(255) NULL    COMMENT '运输状态',
  SPEC_ARRIVAL_DEADLINE DATETIME NOT NULL    COMMENT '指定到达期限',
  TRACKING_ID VARCHAR(255) NULL    COMMENT '跟踪ID',
  CURRENT_VOYAGE_ID BIGINT NULL    COMMENT '当前航程ID',
  LAST_EVENT_ID BIGINT NULL    COMMENT '最后事件ID',
  LAST_KNOWN_LOCATION_ID BIGINT NULL    COMMENT '最后已知位置ID',
  NEXT_EXPECTED_LOCATION_ID BIGINT NULL    COMMENT '下一个预期位置ID',
  NEXT_EXPECTED_VOYAGE_ID BIGINT NULL    COMMENT '下一个预期航程ID',
  ORIGIN_ID BIGINT NULL    COMMENT '出发地ID',
  SPEC_DESTINATION_ID BIGINT NULL    COMMENT '指定目的地ID',
  SPEC_ORIGIN_ID BIGINT NULL    COMMENT '指定出发地ID',
  constraint PK_cargo primary key (ID)
);

CREATE TABLE carrier_movement(
  ID BIGINT NOT NULL    COMMENT 'Id',
  ARRIVAL_TIME DATETIME NOT NULL    COMMENT '到达时间',
  DEPARTURE_TIME DATETIME NOT NULL    COMMENT '出发时间',
  ARRIVAL_LOCATION_ID BIGINT NOT NULL    COMMENT '到达地点ID',
  DEPARTURE_LOCATION_ID BIGINT NOT NULL    COMMENT '出发地点ID',
  VOYAGE_ID BIGINT NULL    COMMENT '航程ID',
  constraint PK_carrier_movement primary key (ID)
);

CREATE TABLE handling_event(
  ID BIGINT NOT NULL    COMMENT 'Id',
  COMPLETION_TIME DATETIME NULL    COMMENT '完成时间',
  REGISTRATION_TIME DATETIME NULL    COMMENT '注册时间',
  TYPE VARCHAR(255) NULL    COMMENT '类型',
  CARGO_ID BIGINT NULL    COMMENT '货物ID',
  LOCATION_ID BIGINT NULL    COMMENT '位置ID',
  VOYAGE_ID BIGINT NULL    COMMENT '航程ID',
  constraint PK_handling_event primary key (ID)
);

CREATE TABLE leg(
  ID BIGINT NOT NULL    COMMENT 'Id',
  LOAD_TIME DATETIME NULL    COMMENT '装货时间',
  UNLOAD_TIME DATETIME NULL    COMMENT '卸货时间',
  LOAD_LOCATION_ID BIGINT NULL    COMMENT '装货地点',
  UNLOAD_LOCATION_ID BIGINT NULL    COMMENT '卸货地点',
  VOYAGE_ID BIGINT NULL    COMMENT '航程ID',
  CARGO_ID BIGINT NULL    COMMENT '货物ID',
  constraint PK_leg primary key (ID)
);


   ALTER TABLE voyage COMMENT '航程';
                
   ALTER TABLE location COMMENT '位置';
                
   ALTER TABLE cargo COMMENT '货物';
                
   ALTER TABLE carrier_movement COMMENT '运输动作';
                
   ALTER TABLE handling_event COMMENT '业务时间';
                
   ALTER TABLE leg COMMENT '航段';
                
